### ISSUE TITLE
(De)activating a raider upgrade that gives skillbooks

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#100]
I just bought the saving throw raider upgrade. I saw that you could activate the upgrade, which stroke me as odd. But it took an upgrade slot. But I couldn't deactivate it again.

![image](https://cloud.githubusercontent.com/assets/4981659/15790300/e9958d48-29d0-11e6-9ccc-1dcabb80a8d3.png)

I'll add that clicking the "Deactivate Upgrade" button toggles the text size (as if I hovered the button) which I doubt is intended.

I'm not sure if I like the idea that I can never deactivate an upgrade. Since I still only have 3 upgrades maximum, and have no idea how to get more, I think it should only be fair that I could deactivate the upgrade, as long as this is how you want it to function. For that to work, you'd just have to check both inventory and equipped skills for the books, and remove them.

Note, that **I found a bugged way to deactivate them** for now, and still keep the skills:
1. Click the deactivate button once.
2. Close the raider upgrades window and open it again.

![image](https://camo.githubusercontent.com/645a54ee1808dd84f3242480ee1029de8b62fdd7/68747470733a2f2f692e6779617a6f2e636f6d2f36623033656466306139346366336332643566626365303230326363303565302e676966)

**Comment by Muskar** [comment]
Okay, bought the "Concentrate Attack" skill too, and noticed that I didn't get it before activation - so it's probably intended.

But I'm not sure if I like the idea that I can never deactivate an upgrade. Since I still only have 3 maximum, and have no idea how to get more, I think it should only be fair that I could deactivate the upgrade, as long as this is how you want it to function.

You'd have to check both inventory and equipped skills for the books, and remove them.

**Comment by Muskar** [comment]
Hmm, now after a soft reset, Saving Throw is suddenly deactivated, but I still have the upgrades. I don't know if they still work yet:

![image](https://cloud.githubusercontent.com/assets/4981659/15791971/b6361a3a-29da-11e6-8b0e-4a34e2cea1af.png)

**Comment by Muskar** [comment]
Also, the command skill doesn't seem to work. All raiders get an exclamation mark above their heads, but after half a second, they return to attack whatever they were attacking before.

**Comment by Muskar** [comment]
Okay, I figured a way to abuse this:

1. Click the deactivate button once.
2. Close the raider upgrades window and open it again.

![image](https://i.gyazo.com/6b03edf0a94cf3c2d5fbce0202cc05e0.gif)

**Comment by Talisca** [comment]
Uhh, we changed the equipment-ui and skill-ui of the raiders for a more generic approach some months ago. Ever since then, we have never tested the ai upgrade logic for skillbooks again x_X
