### ISSUE TITLE
Skillbooks duplicate the inventory count in the priority list

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#101]
![image](https://cloud.githubusercontent.com/assets/4981659/15790521/ff3e6056-29d1-11e6-8702-c550aaccf44a.png)

To reproduce:
1. Have more than 3 of any specific skillbook in your inventory.
2. Equip (drag-and-drop) one of those skills to a raider.
3. Check the priority list.

It will show the number that is left from the inventory stack. So an initial stack of 3 turns into 2, a stack of 4 turns into 3. And if you're replacing the same skill, you'll get the same number:

The effect can be cleared by clicking or rearranging the bugged skill in the skill list (not the priority list):

![image](https://i.gyazo.com/f72d3496de8febe7b58c1ccbf02a763a.gif)

**Comment by Ethismos** [comment]
Beat me by around 30 seconds :)

**Comment by askebv** [comment]
#99

**Comment by TravisGesslein** [comment]
Fixed thanks to you!
