### ISSUE TITLE
Health of raid trash doesn't reset

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#102]
![image](https://cloud.githubusercontent.com/assets/4981659/15791395/60ceebec-29d7-11e6-82b7-0dcc398508d8.png)

I damaged these, but died to them apparently. Now after I started the raid again (and the raiders are inside) they still haven't reset.

Is this intended?

**Comment by TravisGesslein** [comment]
Yup, we don't mind if players zerg down trash mobs. Besides giving more gold and XP than farm monsters of roughly the same difficulty, their primary purpose is supposed to make it harder for raid groups to finish raids in one go.
