### ISSUE TITLE
Error message is hard to see

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#103]
The almost-unnoticeable error message display should probably not be semi-disguised by the hotkey bar. It should probably have a border or something else, so you can easily read what it says:

![image](https://cloud.githubusercontent.com/assets/4981659/15791757/8e8ab0fa-29d9-11e6-8e61-454d78ef5b3c.png)

**Comment by TravisGesslein** [comment]
Oh yeah, we changed this a bit with Patch 5. Please let us know if it's enough for now. We will rework the error notifications at some point in the beta.

**Comment by askebv** [comment]
It's better I suppose. But yeah, it's not that urgent anyway. I just repeat the error message a few times so I can make sure to read it properly.
