### ISSUE TITLE
Suggestion: Indicate which menus are open

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#106]
I don't know if it's just me, but I keep forgetting which of the 3 UI buttons opens what. E.g. I keep thinking the Raider Upgrades button is the inventory. That's probably because I taught myself that the bottom one was the inventory in the beginning. And then I haven't reprogrammed my intuition well enough since the other button became available.

An easy way to remedy this would be to show some indication on the icon, that clearly showed that this UI was open right now.

Another thing you could also do, is to grey out (and hide the tooltip from) the raider upgrades button when you start the game. This way, we know that a button will eventually be there, but we just don't know what it is yet.

Yet another possibility is to have hotkeys to open/close these menus. Like 'I' for inventory, 'E' for Equipment and Statistics, and 'U' for Raider Upgrades and Ancient Wisdom.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
