### ISSUE TITLE
Royalty Ring equippable by all classes

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#107]
Is it supposed to be equippable by all classes?

![image](https://cloud.githubusercontent.com/assets/4981659/15798604/febbe63c-2a3d-11e6-82b3-24907b847c13.png)

It would make sense, since it has a stat that is universally applicable, but since it's the first one I've seen, I just wanted to make sure.

**Comment by TravisGesslein** [comment]
Yep, for that particular one it's intentional.
