### ISSUE TITLE
Thoughts on gold and items

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#108]
I just wanted to briefly talk about this. I've spent some time on private servers of World and Warcraft. And a common suffix term about the economy there was "-sink". Gold sink. Item sink. etc.

The idea behind them was that with the constant stream of items you gather (and effectively conjure into the world), there needs to be ways for most of them to disappear - or else you'll end up being flooded with stuff.

In this, we have no use of excess items (except consumables). You can't sell them, you can't turn them into something else, you can't give them to npcs for other rewards, and there's no gain in simply deleting items. And in contrary to WoW, it would be terrible if we had a limited inventory - because we have no system of picking which drops we want.

As for gold, we're getting exponential amounts over time. As of now, this game tackled this by making lots of expensive stuff to get (and allowing no refunds on anything). But most of these things are something you'll only need to buy a limited amount of times.

Thus far, I think the only items that you'll want to keep buying are consumables, the soft reset, possibly mercenaries and the Time Warped Cave. And consumables are heavily limited by the RNG and conjure-rate of the market.

This means your gold needs will decline over time - but your gold gains will exponentially increase. So in the end, we'll still go from very poor to an exponentially growing abundance of gold. Fortunately the exponential curve seems to have been drastically decreased with the ancient wisdom, but it's still exponential (because farming will always get a steady gold income and increasing the gold rate accelerates this income every time).

Hopefully you have plans for item and gold sinks in mind. I remember there used to be talks of a crafting system. And perhaps that's also what you're thinking about for the enchanting stuff that we're seeing.

Anyway, just wanted to mention it. I'll reference the other suggestion/discussion topics: #53 #84

**Comment by TravisGesslein** [comment]
Closing this, as it's older feedback now. We have several types of sinks in the game now, for both gold and ancient artifacts, like the crafting system, gold cost for unlocking ancient artifacts, etc. :) We'll add more over time, too. Balancing this is an ongoing problem of course.
