### ISSUE TITLE
Enemy stuck inside a tree.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#11]
Enemy stuck inside a tree, no one could hit him for about 2 minutes. Fixed by changing farm maps, but it could ruin idle farming.

Screenshot: http://imgur.com/nD1kSi8 

The archer is stuck at one side of the forest. A warrior and a priest are stuck next to the tree, no one could hit. There was also an enemy UNDER the priest and warrior at the sceenshot, it could be the issue.

**Comment by TravisGesslein** [comment]
Enabling monster<->tile collision next patch. From preliminary tests it seems like the performance impact is minimal. Can optimize later in case there are problems.
