### ISSUE TITLE
Dawn Fortress replaced by new raid

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#110]
I had 5 raids available when I used my rare consumable map to Dawn Fortress. The Dawn Fortress then appeared on the 6th slot.

Now I cleared the 5th raid (yay, thanks to challenging cry - still no arcane bombardment) and the Frozen Coast raid replaced the slot of the Dawn Fortress raid.

I seriously doubt this is intended.

Also - I'm guessing it's intended that we lose access to the Dawn Fortress raid once we soft reset, right? I haven't had that happen, because I just assumed so, so I didn't soft reset.

**Comment by askebv** [comment]
Fortunately I just learned that the auto-raid functionality can take my raiders there regardless! :grinning: 

Here's a link (to avoid spoilers) to proof: http://imgur.com/WGMw7f5

**Comment by Ethismos** [comment]
What is this raid? Do you unlock it with an item?

**Comment by askebv** [comment]
Yes. A rare consumable. I got it over night on auto-raid farming on farm level 5. So it's either a global drop or a drop in raid 1-4, which were the only ones auto-raid could complete at the time.

**Comment by thorbrian** [comment]
I got the same problem but not the same repro conditions - had Dawn Fortress, now I don't, but auto-raid still takes me to Dawn Fortress. However, for me I didn't lose Dawn Fortress by unlocking a raid. I had unlocked to gardens of eternity, and also had Dawn Fortress (and could access them all) but now I just have through gardens of eternity

**Comment by askebv** [comment]
I tried unlocking all raids first, and then using the map. This made it show up initially, but the raid vanished again later - like thorbrian says. Perhaps when the global cooldown was finished? But yeah - like thorbrian, I can also still access it through auto-raid.
