### ISSUE TITLE
Farm level 57 - Empty

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#111]
Title

**Comment by askebv** [comment]
So level 49 is fixed now? #89

**Comment by Ethismos** [comment]
Can't really check because my savegames died again and i can't play !

**Comment by Muskar** [comment]
You should probably open up a new issue on that then, and reference the only 94 one - since that's obviously a pretty big problem :stuck_out_tongue:

**Comment by askebv** [comment]
I still can't get past level 49, so I don't know how you got to level 57. Did you cheat to get there?

**Comment by Ethismos** [comment]
Nope, was auto farming.
