### ISSUE TITLE
Suggestion: AI Upgrade to target enemy with low hp

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#113]
I've been using the command skillbook for a little while now, and often I've found that my mages unload all the mana into one or two bosses, but then the command skill is released, and now everyone starts hitting the boss that has only been hit by the warriors.

First of all, I don't understand why the command skill is always used at such a delay. It's the first skill on the respective warrior's priority list - and he usually gets the rage pretty quickly.

Second of all, I would like it if we could get an AI upgrade for raiders to target enemies with low hp.

The devil is in the details of course, since there's a lot of corner case scenarios and implications that this would have. The command skill could also become quite pointless - but perhaps that's a good thing - because that means it could effectively be an evolution of that skill.

**Comment by askebv** [comment]
Since the command skills has changed to become pretty rapid now, this probably isn't necessary. We're having a heat wave right now, so I'm not really able to think deeply about possible use cases right now.

**Comment by TravisGesslein** [comment]
I thought about it for a while and I agree this probably isn't necessary, especially combined with #156 to make sure command skill cooldown is always available when needed.
