### ISSUE TITLE
Spawn rates of farm level 47 are really low

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#115]
I can understand reasons to have super low spawn rates, but level 47 is substantially slower than other maps.

And once you've cleared the map, perhaps there should be a limited time threshold before at least one monster is forced to spawn.

Otherwise the best action for the player would just be to change map back and forth to fill the map again.
Doable? Yes.
Rewards active gameplay? Yes.
Fun game mechanic? I'm not sure. I think there's better options though.

**Comment by Talisca** [comment]
This is not supposed to happen. One of the monsters got a large respawn time, which leads to this peculiar behavior
