### ISSUE TITLE
Raider got stuck in building formation

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#12]
![image](https://cloud.githubusercontent.com/assets/4981659/15724106/e6cfc178-2845-11e6-9109-df12593443eb.png)
http://imgur.com/dd2OQci

I think he got teleported there after dying to a raid boss. I couldn't figure out any way to free him 
besides refreshing the page.

**Comment by TravisGesslein** [comment]
Oh yeah, we need to check for those cases. We already have a way in the code to determine places that are unreachable from the entrance, and should prevent raiders from spawning in those tiles. Should be fixed next patch. Thanks for discovering this.

BTW as a short work around (in case the raider is still stuck), building something else in that spot and then reloading should do the trick.
