### ISSUE TITLE
Looting more than one of the same unique item

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#120]
This is the first time that I've ever had more than one unique item, so I generously assume that you can't loot a unique set item that you already have.

But this time I looted 2 of them from one boss kill:

![image](https://cloud.githubusercontent.com/assets/4981659/15800437/c95455ec-2a79-11e6-81d1-d7ef7640de37.png)

![image](https://cloud.githubusercontent.com/assets/4981659/15800438/cdbc10ca-2a79-11e6-9040-df5baf6107f2.png)

Maybe related to #62

**Comment by askebv** [comment]
@Talisca I just looted 2 unique items in Beta Patch 3:

![image](https://cloud.githubusercontent.com/assets/4981659/15807093/091d4348-2b54-11e6-87ce-7d42912ea4ee.png)

**Comment by Talisca** [comment]
Well, it was just a problem with the item itself
