### ISSUE TITLE
Buff counter on Enrage behaves very strangely

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#121]
I haven't managed to capture it very well, but I noticed it rarely counts linearly from 10 to 1. It sometimes skips numbers, and sometimes jumps up as well. I've seen it jump from 9 to 5 and 4 to 9 etc.

I would assume it's multiple threads (from refreshed buff triggers) updating the number or something like this.

Here's a (bad) capture of some of the odd behavior:

![image](https://i.gyazo.com/4c6389adf809a3dd5bfd960f3e0bd5e0.gif)

The only odd thing about this clip is that it jumps from 4 to 9. I'll try to capture a better clip if I can. I'm trying to bug out the enrage size like Ethismos anyway.

**Comment by askebv** [comment]
I gave this some more testing time and found that it doesn't seem to do any big skips anymore. At most I've seen it jump down 2 seconds at once, but it just seems because it requests an update at near-1-second delays and just gets an update that it went from e.g. 9.01 seconds left to 7.98 seconds left, or 8.51 to 7.48, depending on the rounding method.

And much like the animated image above, it only seems to go up when the buff refreshes, which is most probably expected behavior. So I don't think this an issue any longer. I'm gonna leave it open until the devs have seen it, just so they are aware that this could be an issue in the future.

**Comment by TravisGesslein** [comment]
Yeah, jumping up again is expected behavior. Buffs have a bunch of different ones depending on the type of buff... some can stack, some will just create a new separate one from the old one if they are allowed to co-exist, some will only refresh the time of the original one... 

I can improve the display a little bit by updating the counter immediately to whatever the time left on the buff is, which should prevent random jumps to random second amounts.

**Comment by askebv** [comment]
I'm not sure if I want it to update faster. If the numbers start updating out of sync, it could be distracting.

**Comment by TravisGesslein** [comment]
They will still be in sync after that, the only distraction could come from a buff being refreshed. I'll implement it, if it's too *distracting we can take it out again no problem :hankey:

**Comment by askebv** [comment]
:hankey:
