### ISSUE TITLE
Enrage messes sizes up

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#122]
I can't tell if all the other raiders have become too big, or if the raiders with the buff just become too small after the buff fades away. But either way, something fishy is going on :tropical_fish: 

![image](https://i.gyazo.com/0636bd58b201c7d2bdec948da7d6ad2d.gif)

Notice the small warrior with the axe and shield on the right. He has enrage equipped but doesn't have it triggered before later in the clip. The warrior that only wields an axe, using mighty blow, has enraged triggered throughout the clip - and is thus the same size as all the other raiders.

The effect seems to vary depending on what the default raider size is on the map you're currently on.

Perhaps related to #63

**Comment by askebv** [comment]
Ran the game over night and my two enrage warriors got like this:

![image](https://cloud.githubusercontent.com/assets/4981659/15804131/c6f4ca72-2afe-11e6-995e-0479cc65e846.png)

My view was set on the base. I suspect I can increase their size if I'm raid view mode (I think it happens when they enrage in another place than what you're viewing) - so I'll let it run there for a few hours.

If I refresh the page, their size is reset to normal - but I "mysteriously lose" some buildings, so I don't want to do that just yet.

**Comment by thorbrian** [comment]
Might have to do with dying? I do a lot of that:
![image](https://cloud.githubusercontent.com/assets/11687574/15804378/f0e7a0f0-2aba-11e6-934e-534123b5daad.png)

**Comment by askebv** [comment]
Yeah I don't think it's related to the place you're viewing. My raiders have become even smaller in the last 3 hours. And now my hypothesis is that it relates to where your raiders die. When my raiders got huge, they died in Burning Cave in auto-raid mode. Now they die on Ravaged Abode.

But I'm still not able to establish a reproducable pattern yet, sadly.

**EDIT:**
I reached a point where one of my raiders actually got stuck in wide open grass in the base, for being so small that I couldn't see him. Now I refreshed and think I noticed once that the enrage soundeffect was played once where raiders were actually in the base, waiting to go to a raid (in auto-raid mode). I don't know if that helps with anything. But yeah, now they've decided to go big again:

![image](https://cloud.githubusercontent.com/assets/4981659/15806308/c0c926ce-2b40-11e6-81e1-c481c20c05c2.png)

The size changes slowly over time, so it's most probably a corner case scenario that makes the size increase/decrease function run once too many ever so often.

**Comment by thorbrian** [comment]
I just reloaded the game so he was back to normal, then left it overnight, on auto farm, looking at the same location I was farming, farming mobs that would never have killed me, and when I got up in the morning, my enrage warrior was like a single pixel.

Maybe it's something that happens when enrage triggers when enraged?

**Comment by askebv** [comment]
I've noticed my guy with mighty blow always grows or shrinks faster than the one without it. Still feel like I'm shooting in the dark here though :dizzy:

**Comment by TravisGesslein** [comment]
After some testing, it seems that down/up scaling are applied in unequal amounts under some circumstances that I have yet to determine (when a buff triggers it scales the raider up, when it runs out it scales it down... it shouldn't get triggered multiple times if it just resets the duration). This results in the scale being permanently off.

**Comment by TravisGesslein** [comment]
Closing in on a fix!

**Comment by askebv** [comment]
My raiders are excited about the news! They very much look forward to the day where they can reach above the crumbs on the floor!

![image](https://i.gyazo.com/a2d576c8e1df913fd4158059fbb23aab.gif)

I would refresh the page - but now that I can't cheat money back in, it's quite expensive to lose the training facility every time!
