### ISSUE TITLE
Well buff doesn't match well description

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#123]
The Well description says it's a 3% energy regeneration buff for all raiders

However, the well buff says it's a +2% additive rage generation for warriors

**Comment by askebv** [comment]
[#90](https://github.com/Heishe/idleraiders-second-run/issues/90#issuecomment-223620535)

**Comment by askebv** [comment]
@thorbrian can you close this issue. This is a duplicate of the solved issue that I referred to.
