### ISSUE TITLE
Wandering merchant ran out of items within the first day, now seems useless, can't tell if there is more to build

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#124]
The day I started playing, I bought building unlocks from the merchant up through gravel road, and built at least one of everything - now the merchant doesn't seem to every sell anything more, can't tell if there's anything more to build

![image](https://cloud.githubusercontent.com/assets/11687574/15801845/7c09cccc-2a56-11e6-91bc-363be6b6e02d.png)

**Comment by TravisGesslein** [comment]
See #47 

The wandering merchant will sell more stuff in the future. For now he just doesn't have anything more to offer :hankey:
