### ISSUE TITLE
I can't figure out how to use a raider snapshot

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#128]
I saved a raider snapshot for an archer, and now want to activate it, but I can't figure out how

I tried clicking it, can't see an option to use it. I tried double clicking it, nothing happened.

I have the needed items:
![image](https://cloud.githubusercontent.com/assets/11687574/15802296/1ee7c8a8-2a62-11e6-8106-a78f4777e662.png)

**Comment by askebv** [comment]
Yeah it's probably a bug. But like consumables, you can single right click them #119
