### ISSUE TITLE
Boss health display can get messed up to be positioned off screen

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#130]
I never saw this until I started fighting multi-monster bosses, but now it's very common for the boss health to get offset off the top screen somehow, so I can't see the first boss health (so when there's just one boss, I can't see that)

![image](https://cloud.githubusercontent.com/assets/11687574/15804404/cdc75970-2abb-11e6-8a5d-55bde8f987e8.png)

**Comment by askebv** [comment]
#61
