### ISSUE TITLE
I've never seen any mercenaries be available, no idea if that's expected

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#131]
I've got raids unlocked up to the frozen coast (beat the chamber of the sealer) and have bought and built everything the wandering merchant had to offer, but never seen a mercenary:

![image](https://cloud.githubusercontent.com/assets/11687574/15804445/f0b6026e-2abc-11e6-88c3-ddf24c9f7f08.png)

**Comment by TravisGesslein** [comment]
No, we forgot to add the default mercenary :hankey:. Other mercenary types can be unlocked in various ways.

**Comment by askebv** [comment]
This should probably be closed, since this is fixed in Beta Patch 3:

![image](https://cloud.githubusercontent.com/assets/4981659/15807396/c8bced4e-2b5d-11e6-81c9-1342c22b7fea.png)

**Comment by thorbrian** [comment]
true
