### ISSUE TITLE
Temple of the ancients showed up as buildable, without any indication or notice

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#132]
After playing for days with nothing new to build at all, I suddenly noticed temple of the ancients was available to build, no notice or indication that it had been unlocked (I wouldn't have even opened the build menu except that I wanted to read the tooltip on the mercenary building to see if it told me why I haven't gotten any mercenaries to show)

**Comment by TravisGesslein** [comment]
Yes, we will have notifications of some form for all kinds of unlocks. I'm keeping this open as a kind of reminder.

**Comment by TravisGesslein** [comment]
Closing this, as this was implemented some time before the Kong beta start. Forgot to close the issue!
