### ISSUE TITLE
Raiders/monsters/bosses/entities are not layered as expected

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#134]
Actually, since I just took a screenshot on the enrage bug, I noticed I had also captured something I had found earlier in boss encounters of some of the big bosses (particularly last boss in Burning Cave):

![image](https://cloud.githubusercontent.com/assets/4981659/15806308/c0c926ce-2b40-11e6-81e1-c481c20c05c2.png)

As you can see, the medium-sized warrior with both axe and shield is rendered in front of the huge warrior that only wields an axe.

To my understanding, it's because you seem to layer sprites based on the bottom of the original image, rather than the rescaled version.

And also, you seem to scale monsters in all directions, rather than upwards and outwards. This results in large scaled monsters looking to be out of bounds of where they can be.

**Comment by TravisGesslein** [comment]
Should now be sorted by the bottom of the character.
