### ISSUE TITLE
Thoughts on sorting options

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#136]
Being able to sort after "[category] first" has not been very convenient for me. It means that I only have control over 1 category of items. Instead I'd probably prefer if we could make a priority/order list for the categories.

But basically, isn't the sorting - as is - mostly useful for _finding_ items, rather than keeping them organized? And in that case, a _filter_ system would be much more convenient (e.g. ability to grey out all but one category of items).

Another point is the same as mentioned in #84 - that many times I'm looking for items for a specific class. So being able to sort/filter after items **suitable** for a specific class would be nice. The reason I say suitable, is because when I'm looking for items for a specific class, I also want to see the items that all classes can wear :wink: 

And lastly, auto-sorting by rarity within the categories would be very convenient as well.

**Comment by thorbrian** [comment]
I would _love_ to sort by what class can use. It's the only think I want to sort by.

**Comment by TravisGesslein** [comment]
@Talisca did something beautifully simple here, I really like it.

**Comment by askebv** [comment]
@Heishe Looking forward to it!

**Comment by askebv** [comment]
@Heishe @Talisca I think it's pretty good, but it's still a bit tough to tell the items apart with a quick glance. I'd prefer it if the numbers and background became darker as well.
