### ISSUE TITLE
Suggestion: Warning that you'll lose the efreet on auto-increase-farm-mode

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#139]
When you have auto-increase-farm-mode enabled and an efreet has spawned, it still just skips forward when you have killed enough to do it - effectively losing the possible gains from the efreet.

I actually think it's very fair that you have a relatively high risk to lose an efreet on AFK-friendly modes. And also, efreets can be a very big challenge if your farm level is very near the border of what your raiders can manage.

But I think it would be a nice touch if there at least was a visual warning/notice that you'd effectively lose the efreet if you don't switch to farming mode. That way, you can choose to stay there, if you're actively watching at that point.

**Comment by thorbrian** [comment]
I can't tell what the benefit of the efreet is - I see he is buffing mobs, but what's the benefit?

**Comment by askebv** [comment]
I just noticed he gives a lot of gold when you kill him, and I guess that's it.

**Comment by TravisGesslein** [comment]
The efreet buffs monsters (random buffs actually, he selects one every time he spawns), you can try to charm him and make him buff your raiders instead. The warning is a good idea.

**Comment by TravisGesslein** [comment]
Also automatically switching from auto farm mode to farm mode if you click on the event notification
