### ISSUE TITLE
Witch wood glitch

### ISSUE THREAD

**Issue by Drakenfeld** [Heishe/idleraiders-second-run#14]
While i was doing the raid _Witch Woods_ the witch constantly spammed Dwarf de-buff never attacking, how i think this came by was when i finished the second boss in witch woods half my raiders were wiped out so i set them to rest then before they must of gone to town the witch casts the de-buff and it glitched it to constantly spam. 

http://imgur.com/e3Z4rd3

**Comment by TravisGesslein** [comment]
Whoops, we accidentally left the cooldown at 2 seconds from a debugging session. Will fix.
