### ISSUE TITLE
Does "Love is in the air" ever happen?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#140]
I noticed Ethismos talked about the "Love is in the air" event in the very first patch. I've not seen this yet - but I don't pay attention to the game all the time. Do the notifications quickly disappear or something? I know they used to stay until the event was over.

**Comment by Talisca** [comment]
Yes, it will happen. But the notification disappeared after ~30 seconds

See https://github.com/Heishe/idleraiders-second-run/issues/200#issuecomment-224545143 

> You likely received the notification but missed it because it disappeared [...] they will now stay until you click on them instead of disappearing automatically after 30 minutes.
