### ISSUE TITLE
Attacking nearest enemy in farm level 59

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#141]
I don't know if it's intentional, but since our raiders seem to judge "nearest enemy" by direct distance, they choose to attack an enemy that would require a much longer path to reach, thus ignoring a ton of enemies on the way:

![image](https://cloud.githubusercontent.com/assets/4981659/15807327/7c27e044-2b5b-11e6-937b-98d2db300e8e.png)

It killed my raiders several times, and I felt like the best approach was to reset the map so I didn't have to deal with the right side of it. And I think that's an unfortunate mechanic to encourage.

**Comment by TravisGesslein** [comment]
Unfortunately path finding is really expensive... can't fix it that way. Instead I'll modify the map so that case becomes much less problematic.
