### ISSUE TITLE
[Minor] Farm monsters can be pushed outside of the map

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#142]
![image](https://i.gyazo.com/035535291c9fba5205daebd645a56cf1.gif)

As you can see, one of the lizards are pushed out of the screen by the other lizard.

I don't know if this is intentional, but it doesn't really hurt anything, in my view. Because it seizes to exist, and thus a new one can just respawn. Additionally, this would probably only happen when the farm monsters are spawn-camping you near the entrance, which is when you're not doing well - and thus spawning rates are absolutely no concern! :grin:

**Comment by askebv** [comment]
I later noticed it doesn't despawn - it is just relocated. I was killing a crab on level 64, and when it was pushed out, a second passed, and then it reappeared with the same health left, at about 10-15 ingame meters away, where other monsters have spawned before.

**Comment by TravisGesslein** [comment]
This should be fixed with some physics system adjustments + the fact that they now walk back to their spawn.
