### ISSUE TITLE
"Hail of Arrows" only 3-4 hits nearby enemies

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#145]
There's a raider upgrade called "Hail of Arrows" which seems to only hit the nearest 3 or 4 targets. However the description and animation seems to suggest that all enemies in the entire map are hit:

![image](https://cloud.githubusercontent.com/assets/4981659/15807879/da66f75a-2b68-11e6-9c0c-2d9432caa6c9.png)

**Comment by askebv** [comment]
Weird. On Farming level 10, it seems to hit (almost) all enemies. It didn't on several other farm maps though - and neither in the raids I checked. So maybe it's related to how close they are together or something?

**Comment by thorbrian** [comment]
I've seen it damage the skeleton boss when using it on the first skeletons, which seemed pretty far on range - but then I've seen it used on the fire demons in burning caves, yet it didn't hit the 4 dogs immediately after, which seemed like the same distance to me

**Comment by askebv** [comment]
So maybe it depends on which map it is? Maybe it has an incorrect perception of what size the map is or something?

**Comment by TravisGesslein** [comment]
I think the behavior stated in the description is unintended anyways, I don't want you to be able to damage boss encounters further back in the map by triggering the skill near a boss encounter in the front. I think I'll modify it to hit everything on farm maps, but restrict the range in raid maps.
