### ISSUE TITLE
The Sturdy Cloak mistaken 35x attack speed thing was super awesome

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#146]
Just FYI, the super attack speed mage cloak was great - it felt like since the mage was mana bound anyways, it didn't make things fundamentally unbalanced, but was super satisfying none the less. Was one of my favorite things in the game to charge him, then fight an old boss with fireballs on (I run magic missile with the no cooldown thing as well, btw, and still chose the book over the cloak for my magic missle mage)

Seems like it would be good to have something like that still in the game - maybe more rare or a worse item in general

**Comment by TravisGesslein** [comment]
Good idea for a random unique item.

**Comment by TravisGesslein** [comment]
For mages in particular it's interesting because it's not a flat "total damage output" increase, because they don't have an auto-attack that would benefit from it. The increased casting speed comes with a direct increase in mana cost.
