### ISSUE TITLE
Confusion of ancient wisdom description: Increased energy

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#148]
In the description it says _increases the energy points [...] of all raiders by 10%_:
![image](https://cloud.githubusercontent.com/assets/4981659/15807743/e7e907a4-2b65-11e6-8b89-553ba6bd94ff.png)

It should probably say:
_increases the **base** energy points [...] of all raiders by 10%_

or better:
 _increases the energy points [...] of all raiders by **10**_

In other words. 450 mana becomes 460, because the base energy points is 100 - as it is for all classes.

**Comment by TravisGesslein** [comment]
I'll modify the upgrade to give +10/20 energy points
