### ISSUE TITLE
Some way to monitor current cooldowns

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#149]
Even if you don't want to have this implemented in the long run, it could be nice to be able to see which skills are on cooldown and how long they have left.

One way to show it, if you wanted to really implement it in the game, was to do the same effect that you have on used consumables, and put them on skillbooks in the equipment and statistics window.

If that's not something you want, then perhaps you could just put a line at the bottom of the tooltip of each skillbook.

Or at least tell me how I can test it through the developer console :stuck_out_tongue: 

Because I'm suspecting that Challenging Cry is never getting used now that I have the Raider Upgrade enabled for it. But since the animation doesn't always appear, and I forgot what it sounds like, it's hard for me to test. Any ideas?

**Comment by TravisGesslein** [comment]
It's something I've wanted to include for a while, but no time to get around to it so far. Adding them to the equipment screen would be pretty easy. But I'm afraid of compelling players to constantly have the equipment screen opened just for this reason...  I think thats kind of a "adding more stuff to the soup doesn't necessarily make it better" deal. Similar to always having the map opened in the background in Diablo-likes.

I'd rather find a more convenient way to show this somewhere else in the UI. Some way that doesn't take up too much space. Also stuff like this tends to add heavily to the amount of draw calls which melts lower end PCs so there are some performance concerns (although I would make that an optional setting in the options anyways).

**Comment by askebv** [comment]
I agree. Ideally I would also want better ways to see it for sure. But for now, I mostly just want it for debugging purposes. At the time, we are your beta-testers after all :P

**Comment by TravisGesslein** [comment]
I guess it wouldn't be harmful if I make it a disabled-by-default option until we get around to implementing it properly.

**Comment by TravisGesslein** [comment]
I'll check it out for beta patch 4.

**Comment by TravisGesslein** [comment]
Yup 
![cooldowns](https://cloud.githubusercontent.com/assets/2046189/15821058/e0eada76-2bed-11e6-84e1-5c9a8bb10ec0.png)
