### ISSUE TITLE
Second tab on inventory

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#151]
![image](https://cloud.githubusercontent.com/assets/4981659/15812786/4a042fa6-2bb9-11e6-991b-c52ac9f376b8.png)

As you can see, I have a second tab without having a full inventory. I can't figure out how to move items between the inventories either. And when I sorted my stuff, both tabs showed the same items. Then when I applied a snapshot, the second tab disappeared.

**Comment by Talisca** [comment]
Hm, will look into it. 

You're actually able to move the items between tabs by drag'n'drop. The tabs are switched if you hover over them with a pressed mouse button.

**Comment by askebv** [comment]
I figured as much - but didn't manage to test it because the second tab disappeared.
