### ISSUE TITLE
Game crashes if the same mercenary is hired again

### ISSUE THREAD

**Issue by Talisca** [Heishe/idleraiders-second-run#152]

**Comment by thorbrian** [comment]
I may have just experienced this. I bought mad dog for a second time, then tried to do a raid, and I got this:
![image](https://cloud.githubusercontent.com/assets/11687574/15813303/c3fc3872-2b72-11e6-8770-e106ec6fb06e.png)

and then tried to cancel the raid by doing resting (for obvious reasons) and then I got this:
![image](https://cloud.githubusercontent.com/assets/11687574/15813329/eb9bc6d6-2b72-11e6-992c-afd3fb7c2d73.png)

I get constant javascript errors of this:
game.min.js:4265 Uncaught TypeError: Cannot read property 'setPosition' of null
