### ISSUE TITLE
I still "mysteriously lose" my training facility

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#153]
https://github.com/Heishe/idleraiders-second-run/issues/76#issuecomment-223825173

**Comment by askebv** [comment]
@Heishe I just refreshed and the training facility (and everything else) stuck around this time. So it might be fixed! It's still weird for me that it didn't work the first few times I tried it though.

**Comment by askebv** [comment]
Scratch that. The training facility is gone again now xD

**Comment by TravisGesslein** [comment]
Yeah, I rewrote how all of the buildings are saved and loaded, should be fixed once and for all now! hopefully
