### ISSUE TITLE
Suggestion: Only use command/taunt/challenging cry if it has an effect

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#156]
Often Skillbook: Command is used when all my raiders are already attacking that enemy. It doesn't really make sense, clutters the visual and sound effects, and puts it unnecessarily on cooldown.

And taunt is also used, even though the warrior's target is already attacking him.

I'm not 100% sure about challenging cry, but I think it does it too. As of now, the long cooldown means it's rarely used incorrectly though. Especially with the Challenging Cry raider upgrade.

If you want to add it as an upgraded version of ancient upgrades you can buy, then that's fine by me. As long as I get there eventually! :rocket:

**Comment by TravisGesslein** [comment]
Good idea for a raider upgrade. Fits the concept of silly raiders who get a bit smarter over time.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!

Also, I'm just coming back to working on the game after @Talisca and @hamburml took over while I was gone, and I'm not sure but I think we actually implemented this suggestion at some point.
