### ISSUE TITLE
Skillbook command cooldown

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#157]
The description of the skill says it has a 30 second cooldown:

![image](https://cloud.githubusercontent.com/assets/4981659/15820050/0c348f44-2be7-11e6-817f-d231267c2c71.png)

But in reality, it's more like 3 seconds:

![image](https://i.gyazo.com/2e7c35796d0f92c9d3642adcec71335d.gif)

I'd like to think that the description is the wrong thing, since it wouldn't be a very useful skill if it could only trigger every 30 seconds :stuck_out_tongue_closed_eyes: 

Also - as you can see, it often only draws exclamation marks above the priests, instead of all raiders. But that seems to be mostly in boss fights where they're all targeting that boss already anyway. And it only seems logical that the priests stopped targeting the boss after they started healing.

**Comment by TravisGesslein** [comment]
Will be 10 sec in next patch.
