### ISSUE TITLE
Arctic Honor.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#158]
I think this should be a warrior only item. The 10 min rage/mana/focus is practically useless for any other class.

**Comment by askebv** [comment]
I'm using it for my priest (combined with flash heal). With 100+ percentage rage generation (from fire set and elsewhere), I'm basically full most of the time.

**Comment by TravisGesslein** [comment]
Correct, this should be a Warrior item. Sorry for your priest lol

**Comment by askebv** [comment]
:sob:
