### ISSUE TITLE
Soul of the frozen coast set - Bug and free loot abuse.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#159]
1) The blizzard can be summoned at your base, wasting the cooldown.
2) You can "bug" some raider by blocking him with buildings, then have the rest of your raiders go to a hard raid and afk at the entrance while you make sure your precious raider at base is blocked from leaving. Your raiders will summon blizzard over and over again until bosses die.

**Comment by TravisGesslein** [comment]
You are a genius with this kind of stuff.

**Comment by TravisGesslein** [comment]
I'll fix it by teleporting raiders and NPCs to the entrance in when the game detects that you are about to lock them in.
