### ISSUE TITLE
Snow hunting spear

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#160]
2.5 damage warrior item from last boss of the game?

**Comment by askebv** [comment]
It's a common item :grin: 

Probably meant for something else than equipping, I hope :P Perhaps just cosmetics? We'll see.

**Comment by thorbrian** [comment]
Yeah, this confuses me too

**Comment by Talisca** [comment]
The items which are dropped by the centaur are not balanced for now :smile:
