### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#161]
Quite a few bugs, clicking snapshots and getting only half the items, clicking snapshots and having items unequiped but not new ones equipped etc. I can't be to specific atm but i just get bugs every time i use the feature.

**Comment by askebv** [comment]
They've worked fine for me.

**Comment by Ethismos** [comment]
#162

**Comment by TravisGesslein** [comment]
Yes, we can reproduce this with a Beta Patch 2 version of the game, but not with the latest. I assume this was a browser caching issue so I'm closing this for now. Sorry that this happened btw, we're thinking about some solution to force browsers to update when a new version is out without preventing caching entirely to solve this issue.
