### ISSUE TITLE
Whole item set dissapears with snapshots

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#162]
I tried using a snapshot, all my items were unequiped, first inventory tab was full, no second tab appeared, lost propably 10 items in the process, 6 of them were the whole 6 item set we get from the first raids...

**Comment by askebv** [comment]
Okay, I didn't try using the snapshots without having anything equipped. I'll try save and test it in a bit - just to check if it's a systematic issue.

**Comment by Ethismos** [comment]
Try using it when you have enough equipped items that when unequipped they should move to the second inventory tab. Both times i tried that i lost items because no second inventory tab opened and the extra items got deleted. I 'm mentioning the first set incase it helps with bug fixing because i lost all the items from it (and it was pretty easy to notice compared to other items i may have lost)...

**Comment by askebv** [comment]
I'm not entirely sure what you mean, but I understand that the bug is related to the threshold between 1 and 2 inventory tabs, and I have 5 empty slots with everything equipped, so I think I can test it. Just gotta finish the last few raids :grin:

**Comment by TravisGesslein** [comment]
@Ethismos Do the items reappear if you reload the game?

**Comment by Ethismos** [comment]
@Heishe No, and i can get the same unique items that i lost as drops again now and equip them fine... so i guess the old ones are just gone. I will try to reproduce it at some point to help you more.

**Comment by askebv** [comment]
I can't reproduce it I think. I've tried unequipping everything, and putting all the unique items in the second tab. But using the snapshot works fine. Both if I'm applying it when viewing the first and second tab of inventory 

Can you clarify what else I could try?

**Comment by Heishe** [comment]
I think he's saying to have like 79 items in the first tab (no second tab opened), then use a snapshot that would unequip

**Comment by TravisGesslein** [comment]
Whoops

**Comment by askebv** [comment]
Like this?

![image](https://i.gyazo.com/024d093f06dd94acd3c1e0c1b1533112.gif)

No items are lost for me when I do it this way.

**Comment by Talisca** [comment]
@Ethismos I am not able to reproduce this by any means. Could you provide the savegame prior to this encounter if its still available?

**Comment by TravisGesslein** [comment]
There's another possibility: We released Patch 3 on Sunday which fixed some snapshot related stuff, and @Ethismos browser might not have updated to the latest version (instead using the local cached version). We'll check if we can reproduce the bug in the Beta Patch 2 version.

**Comment by TravisGesslein** [comment]
Yes, we can reproduce this with a Beta Patch 2 version of the game, but not with the latest. I assume this was a browser caching issue so I'm closing this for now. Sorry that this happened btw, we're thinking about some solution to force browsers to update when a new version is out without preventing caching entirely to solve this issue.
