### ISSUE TITLE
Buildings charge ~10% more than they cost

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#164]
I had this suspicion for a while now, and this time I got it on camera. I have around 10570 gold. I buy an armor shop that costs 10500, and I end up somewhere near -1000 gold:

![image](https://cloud.githubusercontent.com/assets/4981659/15825922/e2eaa3f2-2c05-11e6-885a-035f98fcdb06.png)

![image](https://cloud.githubusercontent.com/assets/4981659/15825935/eb8e89ec-2c05-11e6-9e3c-be537ffda324.png)

**Comment by askebv** [comment]
Just bought a training facility for 500. Turns out I was charged exactly 550 for it. So it seems everything costs 10% more than it should.

**Comment by Ethismos** [comment]
It seems to me like the more you delete buildings and buy new ones the more the cost is increased. I deleted 10 armor smith buildings to test something (#179) and when i tried to make a new one the cost was 800 but i went at negative gold from 10k +.

So to test it i repeated the process (delete all, buy new ones), and right now my armor smith says 14400 cost and actually costs 300k+.

**Comment by askebv** [comment]
Nice work. How are you testing this though - is there a new way to cheat in money, because the gamesystem object doesn't seem to exist anymore?

**Comment by Ethismos** [comment]
Eh, works fine for me, maybe i m at an older patch?

**Comment by askebv** [comment]
Hmm works fine for me too now. I guess it was just a temporary thing then. Two days ago it kept giving me the error that the gamesystem object didn't exist, so I just assumed it was a code change in the new patch.

**Comment by TravisGesslein** [comment]
Not 100% sure but it should be fixed with Beta Patch 4. Please reopen this if anything goes wrong after Patch 4 is released.
