### ISSUE TITLE
Have I been banned from beta?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#165]
I just refreshed the page and got this:

![image](https://cloud.githubusercontent.com/assets/4981659/15826179/db9e5b2e-2c06-11e6-8f5b-342fa30ad34f.png)

I also tried reentering my key and it says it's invalid:

![image](https://cloud.githubusercontent.com/assets/4981659/15826230/0c34fb08-2c07-11e6-843b-b641b3273f30.png)

Oh well - time for a break from debugging then :P

**Comment by TravisGesslein** [comment]
No, but I think I heard some mutterings about a website bug like that going on between our web dev @Omegahorus  and @Talisca. Will look into it asap

**Comment by TravisGesslein** [comment]
Any errors in the console when you try to log in?

**Comment by askebv** [comment]
No errors. But if I log out and log in again, then all is working again. I just didn't notice there was a log out button in that page :blush:

**Comment by Talisca** [comment]
@Muskar Have you been on kongregate-idleraiders before refreshing the beta? If so, you've been logged in with your kongregate-account I think

**Comment by askebv** [comment]
@Talisca Yes I have. I'll keep that in mind.
