### ISSUE TITLE
Still losing buildings

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#166]
Every time i load the game i lose at least:

Training facility, town hall, mercenary guild.

Doesn't matter where i build them.

In some occasions i have lost 1 to 4 red churces and 1 to 4 inns, never all of them...

**Comment by askebv** [comment]
#153

**Comment by TravisGesslein** [comment]
Sorry about this one, will be fixed later today when we upload Patch 4.
