### ISSUE TITLE
Item is missing icon

### ISSUE THREAD

**Issue by Noxos** [Heishe/idleraiders-second-run#17]
![idleraiders2](https://cloud.githubusercontent.com/assets/19698037/15733432/7a953a5a-284b-11e6-85f3-3ba6b84cb8f0.png)

**Comment by Ethismos** [comment]
Similar issue with enchantment: Greater healing (http://imgur.com/NECiBzn).

**Comment by TravisGesslein** [comment]
Is it still missing after reloading the game?

**Comment by Ethismos** [comment]
Enc:Greater healing got fixed after reloading ^^

**Comment by TravisGesslein** [comment]
We'll keep this opened: We have dealt with this kind of bug several times internally over the past few weeks. We strongly suspect there are some error cases left in the code yet. So this issue is helpful in case someone else encounters it again.

**Comment by TravisGesslein** [comment]
By now, most of these bugs should be squashed... closing until it happens again.
