### ISSUE TITLE
Suggestion: Auto-focus and Auto-scroll

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#171]
When You switch to active Raid Map let game auto-focus on You first raider sin list and when he move screen auto-scroll with him.

**Comment by askebv** [comment]
In line with the suggestions in #75

As you can read there as well, for now you can at least use the F-hotkey to center your camera on the raiders. You can also use the equipment menu to track on the raiders, and then close it again, assuming you have disabled the "Reset camera to last position and map..." option, in options :)

**Comment by TravisGesslein** [comment]
I'll use this issue for "auto focus on raiders when raid opens" and use #75 for a toggle to follow raiders constantly.
