### ISSUE TITLE
Raid 4: Archer terrorist

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#172]
One of My archers constantly ignore first group of three enemy and run to the dogs. Shot them few times and then glad run back with group of dogs at tail. So My time wiped very fast.

**Comment by thorbrian** [comment]
Do you have charm equipped? 

I've noticed that archers with charm will leave the boss to go find a target suitable for charm when it is off cooldown. I've actually taken advantage of this by equipping lots of charm skills, and then my archers will go bring all dogs over to slaughter the boss >:)

**Comment by DaemoniaV** [comment]
Yes it is Charm. Remove it and he stop run out.

**Comment by TravisGesslein** [comment]
Ah, it seems the Charming Shot does not have a range at the moment, so it can target all monsters on the entire map. I will add a range restriction to the skill which should fix it.
