### ISSUE TITLE
Raid 2: Group attack of Bosses

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#173]
Often second boss come to first boss at time of battle with first boss. My raider does not provoke him. One time the third boss come to place where My group fight with first boss.

**Comment by askebv** [comment]
You mean the beam-bird and the shrinking-witch came to fight you while you were fighting the tree boss?

I've never had that happen before. Do you think it's due to some item or skill you're using?

**Comment by thorbrian** [comment]
I've gotten this a few time, when using charm. I noticed the tree helpers spawned by the tree can be charmed - maybe they are somehow triggering aggro on the bird and witch?

**Comment by TravisGesslein** [comment]
What @thorbrian says would make sense, @DaemoniaV can you confirm that you used Skillbook: Charm too?

**Comment by DaemoniaV** [comment]
Yes. It is clearly charm. A catch one time. Charmed tree helper provoke second boss.

**Comment by TravisGesslein** [comment]
Thanks, I think it should be a safe fix to just make the map a little bigger and place the bosses a bit further apart.
