### ISSUE TITLE
A weird effect started showing up, can't tell what it's for

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#175]
It appears to show up when I damage things, but can't tell why - location seems to be near enemies, but weirdly offset, and it doesn't seem to place a buff on the target
![image](https://cloud.githubusercontent.com/assets/11687574/15845871/1a11c5a6-2c2c-11e6-9720-37aaeac8efb7.png)

Here's what I have equipped:
![image](https://cloud.githubusercontent.com/assets/11687574/15845885/39db97f4-2c2c-11e6-87fd-d6a11a3cc1fd.png)

**Comment by askebv** [comment]
To me it seems to happen when my warriors attack. I thought it was from the fire imbued hatchet - but since you don't have that on, it seems it's not. Could be from the Waraxe of the Sealer?

By the way, what's that legendary sword you have on the priest?

**Comment by thorbrian** [comment]
Burned out seal, from the sealer boss thing. Not sure if it is simple loot drop or result of some process (I had been equipping the essence of rage thing for fun)

**Comment by thorbrian** [comment]
You are correct sir - it is indeed waraxe of the sealer. Guess it's just an effect for fun?

**Comment by askebv** [comment]
Yeah, I'd guess so.

**Comment by TravisGesslein** [comment]
This is related to #147 and should be fixed with Patch 4.
