### ISSUE TITLE
Sometimes a raider won't go to the raid - causing the other raiders to just wait there

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#176]
A few times I've gotten situations where all raiders but one go to the raid, causing the rest to wait forever
![image](https://cloud.githubusercontent.com/assets/11687574/15845926/b12f61a0-2c2c-11e6-879a-77a6801391d8.png)

In this case, it was my super-shrunken enrage warrior, ernhat, who doesn't seem to have any reason to be stuck here:
![image](https://cloud.githubusercontent.com/assets/11687574/15845934/cd640038-2c2c-11e6-8f94-0f07894af40e.png)

I've seen it occur with not shrunk guys too, they were always in base tho

switching to sleep mode gets everybody to come back, so not too bad of a problem

**Comment by askebv** [comment]
Yeah I've had it happen several times too. But it'll probably be fixed when #122 is

**Comment by TravisGesslein** [comment]
The next time this happens, could you open the console (F12 on most browsers) and see if it throws any errors? This behavior is very strange, I don't think it will be fixed by the scaling fix if you have seen it happen for non-shrunk raiders as well.

**Comment by TravisGesslein** [comment]
Also keep in mind that in the Auto Raid mode, raiders will rest in the base until they are at full HP every time a new raid is started.

**Comment by askebv** [comment]
I've only ever seen it happen for super shrunk raiders, but I'll make sure to include the error. It happened to me a few hours ago, and haven't closed the window since. There's no noticable errors in there though (just the https insecure script errors and a bunch of warnings).

**Comment by askebv** [comment]
I just had it happen again, and there's no errors:

![image](https://cloud.githubusercontent.com/assets/4981659/15857517/21af9a0a-2cbc-11e6-9c24-4e7b336d9217.png)

![image](https://cloud.githubusercontent.com/assets/4981659/15857542/3ddba250-2cbc-11e6-8113-a489d8617479.png)

**Comment by TravisGesslein** [comment]
Mhm still with shrunken raiders only. I guess I'll close this issue in anticipation of Patch 4, we'll see if new issues pop up and can reference this one then.
