### ISSUE TITLE
Hail of Arrows can fire with one archer back in base

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#178]
Not sure if this is intended - but the description of the Hail of Arrows says it "Requires the coordination of two archers", which implied to me I needed to archers with the skill in battle - but with one of the archers back in base, it still fires. If it's intended, it's kind of funny and cool, just wanted to let you know.

**Comment by askebv** [comment]
Yeah I noticed that too. I'm neither sure that it's intentional, but I think the main reason of saying it requires "coordination", is probably to make it take a skillbook slot on both archers - which I think is a fair price for such a powerful skill.

**Comment by TravisGesslein** [comment]
Indeed, this is not really intended but at the same time I don't have anything against it. As @Muskar says, the primary trade-off is supposed to be the fact that you need one skill slot on both Archers for the skill.

**Comment by TravisGesslein** [comment]
Actually thinking about it I wouldn't want the skill to become useless in raids or farm maps once one archer dies and is back in the base. I think I'll leave it working as it is right now for that reason, but I'll update the description to reflect this behavior
