### ISSUE TITLE
Damage immune warrior - Armor smith buff

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#179]
It seems like the armor smith buff applies as a flat % after everything else is calculated and not as a multiplier. This makes it possible to have damage reduction values above 100% when using bulwark with any other damage reduction items.

This is pretty abusable in late game with some warrior builds, for example taking full atk speed items and full buff duration bonus can make your main tank invinsible for almost 100% of fights. (And is actually the method i plan to use to test arena).

How to test:

Get armor smith buff to 10.
Get bulwark and activate it in a fight.
![](http://i.imgur.com/EVtJdxk.jpg)
Get any other damage reduction item, like frozen shield, frozen chestplate, set bonuses etc.
![](http://i.imgur.com/Zac9iu3.jpg)

**Comment by TravisGesslein** [comment]
We'll convert the buff to the usual exponential fall off. Starting from 100% damage taken, it has nearly the same effect (you will receive 90.4% damage instead of 90.0% with the flat values) but it'll solve the problem you mentioned.

**Comment by TravisGesslein** [comment]
Although I do suspect Bulwark and the increased Buff duration combination might just be a bit too strong. With the increased buff duration buff a 90% reduced damage uptime is probably almost a free kill for bosses that don't do AOE damage isn't it? Mhm...

**Comment by Ethismos** [comment]
Well, with the available gear you can get 36 atk speed from items making bulwark cd 88 seconds. With 4 bulwarks and 120% duration bonus making each bulwark last 22 seconds (and some rage generation management) you can practically be invincible. Even without this bug with the set bonuses etc you can have a 92-93% reduction at all times. Assuming we can enchant buff duration by 50% like we could at alpha this is pretty possible without artifact or gold hacks.

I do think it needs a balance change. I would combine a lower damage reduction with lower CD (like 75% - 80 sec cd) so you can cap your main tank at ~80% damage reduction and/or make it unique per warrior so it is kind of impossible to have 100% uptime on it unless you gather a few million artifacts, which would make other things like rejuvenation imbalanced anyway.

**Comment by TravisGesslein** [comment]
Yeah, I like the "lower damage reduction vs lower cooldown" change.
