### ISSUE TITLE
Raid 4: Dont work Taunt

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#181]
Every My Warrior have one Taunt book. But the monsters from first group ignor eand hit the other raiders. Only one fight with My warriors often.

**Comment by thorbrian** [comment]
I believe the warriors only taunt their own target, and taunt has a 10 second cooldown - are the warriors attacking a target that's not attacking them, for longer than 10 seconds?

**Comment by askebv** [comment]
You'll need Challenging Cry (from scholar's tower) to taunt other targets than the ones that the warriors target by themself. Or Saving Throw but that skill seems pretty broken/useless when I've tested it.

**Comment by TravisGesslein** [comment]
Actually, for the very first boss in Burning Cave this is intended. The two side-mobs to the boss devil pick a new random target every 10 seconds or so.

**Comment by TravisGesslein** [comment]
It's true that the default taunt is not intended for this, at least until you get the group taunt upgrade. Instead this encounter was suposed to be a perfect use case for Saving Throw.  I think I should link this with the Saving Throw issue #104
