### ISSUE TITLE
Gold 10%???

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#185]
Did gold upgrade add invisible part to collected 1-9 gold?
Or it was reasonable only if you farm monsters with 10 gold drops?

**Comment by TravisGesslein** [comment]
It's just an invisible part. If a monster drops 1 gold, you get "1.10" gold, but we don't show it in the interface. After you kill 10 of those monsters you will have 11 gold.

**Comment by TravisGesslein** [comment]
I will update the description of the upgrade to reflect this fact.

**Comment by askebv** [comment]
There was a bug where you could get negative gold, and in the negative numbers, it actually shows the decimal points, so it was easy to see there.
