### ISSUE TITLE
Multidrop from bosses...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#186]
Are the multidrop legal?)
Try to beat Raid 3. Easy clean first group of enemy and green goblin. Then wiped out by Dragon. Do second run - again wipe. Change strategy and kill the Dragon - receive 3 Dragonling Armor. It is normal?

**Comment by TravisGesslein** [comment]
Yep, currently you receive +2 extra items the first time you kill a boss in each soft-reset. But while playing we find that this kind of swamps players with items too quickly when they play the game for the first time, so we will reduce this to +1 in the future and introduce a permanent upgrade which increases this value.
