### ISSUE TITLE
Suggestion on future - Auto-filled Bestiary.

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#187]
Let it was Bestiary page in game where You can see Monster drops. But let item showed there only after once dropped.

**Comment by TravisGesslein** [comment]
Yeah this has been on internal to do lists as well. But it's a huge amount of work. This won't be tackled before the re-release but I agree it would be an awesome feature. 

BTW I'm going to start closing long term suggestion issues (or issues that are very general). Just to keep the issue list a bit more cleaned up so we can focus on actual issues or imminent changes. They are still available in the closed tab by filtering all issues with the suggestion label (you can do that right? Not sure if only we admins have the permissions).
