### ISSUE TITLE
One priest has 1 higher base regen than the others

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#189]
For some reason, one of my priests have higher base mana regen than the others:

![image](https://cloud.githubusercontent.com/assets/4981659/15869108/38ee7298-2ceb-11e6-83f1-c1e9b2796787.png)

![image](https://cloud.githubusercontent.com/assets/4981659/15869123/4a56be3c-2ceb-11e6-8c30-575ce69acade.png)

As you might be able to tell, they're all in sleep mode, hanging out in the base, so there's no buffs to account for.

The only difference I know of, is that the super-regen priest used to have Arctic Honor equipped (but it got instantly unequipped with an error message when I launched the new patch). I already tried refreshing the page and nothing really happened.

And I can confirm that the regen is true to its word:

![image](https://i.gyazo.com/acc1265055427dbe6048ca08e072fc01.gif)

I've exported a savefile to send over email, if it isn't reproducible for other people. Just give me the word :)

I figure that even if I'm alone in this, it's still pretty weird that the regen should be affected, since Arctic Honor didn't provide any regen.

**Comment by Ethismos** [comment]
Since it is 1 mana regen difference exactly i guess it has to do with frozen heart set bonus not applying. I might be wrong, but try to unequip it and reequip it (the whole set).

**Comment by askebv** [comment]
Unequipped the whole set and then the values are 1.30 and 0.30 for the others, respectively. Equipped it again, and the values go to 2.30 and 1.30 again.

So you don't share these values, I presume? This is with 5 wells and 2 tents, by the way.

And just to make sure - you're running beta patch 4, right?

**Comment by TravisGesslein** [comment]
Can you send me that savegame?

**Comment by TravisGesslein** [comment]
Just checking if it's the same for you:  

Oina: 1 base regen + 0.4 Icetouched band + 0.2 from tents + 0.1 from wells = 1.7
Daelm: 1 base regen + 0.4 icetouched band + 1 frozen heart + 0.2 tents + 0.1 wells = 2.7
Urnkel: 1 base regen + 0.2 tens + 0.1 wells + ??? = 2.3

I haven't debugged yet but it seems the set bonus only applies to Urnkel, but not to the others. Which is why that priest has 1 mystery regen.

**Comment by askebv** [comment]
Yeah the values are the same for me as you posted. Except I have Ancient Emberwood Staff on Urnkel (+0.5) which gives her 2.80.

**Comment by TravisGesslein** [comment]
Yup, it was a bug with the set bonuses. You can fix it as a workaround by unequipping the entire set, reloading the game, and then equipping the set again.
