### ISSUE TITLE
Suggestion: Cancel building

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#19]
There should be an easy way to cancel your current building selection to avoid building when you try to click the "demolish" or "main menu" buttons. Happened to me twice in a day...

**Comment by TravisGesslein** [comment]
"ESC" on the keyboard already works, but I'd like a simple way to tell players about that somewhere. We'll add little tutorial popups that appear when you do stuff for the first time, this seems like a good candidate for it.

**Comment by TravisGesslein** [comment]
I added this to internal trello board as tutorial stuff todo
