### ISSUE TITLE
Melee enemies on level 5-6 / 69-70 have pretty high range

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#190]
I don't know if they're supposed to use throwing knives or something, but their attack range doesn't look melee at all:

![image](https://i.gyazo.com/c5cdd62cec9096a6170333973a3e7142.gif)

**Comment by TravisGesslein** [comment]
No they are just supposed to be flailing around their sabers. Fixed in Beta Patch 5.
