### ISSUE TITLE
Efreet might be summoned on wrong map

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#191]
I was here writing my past issue when it happened, but when I returned to the game there was an efreet notification on a map where my raiders are struggling to survive (level 69). I doubt they would have managed to kill it that fast, so maybe it spawned wrong?

Anyway, I can't confirm that's what happened yet. Just throwing this out there as a reminder of something to pay attention to.

**Comment by Talisca** [comment]
Ok, this is related to the fix of #85 

Because of some modified checks he might not spawn at all. The event triggers nevertheless. I am sorry :(
