### ISSUE TITLE
Can't unequip item if inventory is full

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#192]
I can't drag and drop my equipped item into my inventory if my inventory is full. I can only replace it with another item. Once I have a second tab open, I can just drag it into an empty spot there though.

In a previous patch, this was possible since you could drag and drop the item unto non-equip items to unequip.

But honestly I think even if you drag an equipped item unto a replaceable item, it should only unequip. It should only swap if you drag from the inventory to the equipped items.

**Comment by TravisGesslein** [comment]
I agree, dragging something down is probably intended to be an unequip most of the time.

**Comment by TravisGesslein** [comment]
Also we should show a second tab as soon as one tab is full, not just when another item needs to be placed into the inventory.
