### ISSUE TITLE
Monsters with bugged health bars

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#193]
I've only seen it once so far, but I remembered to screenshot it:

![image](https://cloud.githubusercontent.com/assets/4981659/15870879/3df2786e-2cf2-11e6-8608-89131c17c147.png)

As you should be able to tell, the leftmost red scorpion has an oversized rectangle representing its health. These all took damage from Hail of Arrows by the way.

**Comment by askebv** [comment]
Nevermind saw it again on the next map. On another type of scorpion no less:

![image](https://cloud.githubusercontent.com/assets/4981659/15870958/90d0cc3e-2cf2-11e6-8350-d6307e201e19.png)

**Comment by Ethismos** [comment]
Also saw it at least 3 times in levels 65-70.

**Comment by askebv** [comment]
Also encountered a different variation on farm level 40:

![image](https://cloud.githubusercontent.com/assets/4981659/15873097/3faa26ce-2cfd-11e6-8434-a15fed65e480.png)
