### ISSUE TITLE
Changing areas - Inventory items stay on air.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#195]
So, i was trying to focus on the new feature of watching my spell cooldowns while my raiders where auto farming. At some point i pressed the "X" button and the camera moved to the farm area where i started auto farming (and not to the current one, which would be more useful) and noticed a candy standing in the area and last critical i did. Could reproduce it a few times with arrows or fireballs staying on air.

![](http://i.imgur.com/FCSTuJF.jpg)
![](http://i.imgur.com/gonoliY.jpg)
![](http://i.imgur.com/z2nF7f8.jpg)

 No idea if picked up this candy or not...

For example, my raiders could be at level 80 and the screenshot was taken from level 70 where i started auto farming after i stopped tracking the statistics and equipment.

**Comment by TravisGesslein** [comment]
If you actually change back to these maps and return to farm there, are those sprites still there?

**Comment by Ethismos** [comment]
No.

**Comment by TravisGesslein** [comment]
Good :hankey: You're not actually supposed to be able to view these maps unless your raiders are on it... having them all hanging around (just invisible) can reduce performance by a bit. Will fix
