### ISSUE TITLE
Bug - Activate Deactivate

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#199]
I have unlock 4 upgrades but one moment can activate only 3. I start R4 with some configuration after wiped deactivate Overheal and activate Avoid of AoE, wiped again... Try to deactivate Saving Throw button has switched between Activate/Deactivate but color of icon and count do not change. After some random pressing have this picture(
![bug1](https://cloud.githubusercontent.com/assets/19784493/15876294/4657f4de-2d15-11e6-9877-9ff83976ff43.jpg)
All 4 are highlighted but count show 2/3. Reloading of page do not help.
There is Muskar write about similar https://github.com/Heishe/idleraiders-second-run/issues/100

**Comment by Talisca** [comment]
Yep, this is a duplicate to #100 

For the other part: The unlocking of an upgrade doesn't influence the max. active upgrade limitation
