### ISSUE TITLE
Editing base tools

### ISSUE THREAD

**Issue by Drakenfeld** [Heishe/idleraiders-second-run#2]
Hey Pitforest, been messing around with the new ( Edit base ) game mechanics, not sure if it's a bug but when you destroy the pre-placed dirt road you can't place dirt road back down it them spots. it's all just highlighted as red.

Heres a screenshot showing what i mean. 
http://imgur.com/IIOd2II

**Comment by TravisGesslein** [comment]
Oh yes that's a bug. That pre-placed part of the map isn't supposed to be editable at all, it's kind of a safe buffer zone to make sure the raiders always have somewhere to go on the map even if you fill all buildable tiles with (non-road) buildings. So deleting those tiles shouldn't be possible either. 

Maybe I should look into allowing the player to build on those tiles but restrict the building types to roads only in those positions?

**Comment by Drakenfeld** [comment]
I feel it'll just be better to set them all as untouchable, one of the tiles is currently untouchable and thats the one left over in the screenshot, i have noticed after i refresh the game them tiles i deleted get restored back to their default state.

Another thing that i found was while editing the Archer tent deleting it and replacing one else where loses the stack effect but when i refresh the stack damage effect for archers tent get's restored.  

Plus a little suggestion, maybe add a warning for when you click on an tent since it can be painful on your gold savings when the tents just get deleted.

**Comment by Drakenfeld** [comment]
List of bugs i have found so far will keep on editing this as i go along.

● While entering _The Crypt_ skeletons started attacking me before my whole team entered the raid.
● T̶h̶e̶ ̶b̶a̶s̶i̶c̶ ̶s̶w̶o̶r̶d̶ ̶f̶r̶o̶m̶ ̶_̶T̶h̶e̶ ̶C̶r̶y̶p̶t̶_̶ ̶d̶i̶s̶a̶p̶p̶e̶a̶r̶e̶d̶ ̶o̶n̶c̶e̶ ̶i̶ ̶u̶n̶e̶q̶u̶i̶p̶p̶e̶d̶ ̶i̶t̶,̶ ̶r̶e̶f̶r̶e̶s̶h̶e̶d̶ ̶s̶t̶i̶l̶l̶ ̶d̶i̶d̶ ̶n̶o̶t̶ ̶r̶e̶t̶u̶r̶n̶ ̶n̶e̶i̶t̶h̶e̶r̶ ̶i̶s̶ ̶i̶t̶ ̶i̶n̶ ̶a̶n̶y̶ ̶r̶a̶i̶d̶e̶r̶s̶ ̶e̶q̶u̶i̶p̶m̶e̶n̶t̶ ̶s̶l̶o̶t̶s̶.̶
● tbc

**Comment by TravisGesslein** [comment]
Could you tell me which browser you're playing with?

**Comment by Drakenfeld** [comment]
Chrome latest version on windows 10.

**Comment by TravisGesslein** [comment]
Oh wow, that is exceedingly weird! We primarily develop using Chrome and item bugs like that haven't happened almost since the original alpha release. Please let me know if the item bug happens again.

**Comment by TravisGesslein** [comment]
Oh, I just realized we fixed some transmogrification bugs today that haven't been uploaded to the servers yet. Is there any chance you equipped the item into the slots on the right (next to the transparent part of the window that is placed around the raider)? Those are transmogrification slots, they're only supposed to change the look of the character in case you prefer the look of one type of item but want to use the stats and stuff of another.

**Comment by Drakenfeld** [comment]
Yes! _Runs away and hides in corner_ lol

**Comment by TravisGesslein** [comment]
Phew, don't worry that's good for us. We will upload a fix asap (already at it), the item should show up in that slot again when you reload the game after the uploading has finished. I'll write something in here once that's done.

**Comment by TravisGesslein** [comment]
Okay, patch should be uploaded. I'll close this issue and create a couple of separate issues for the topics discussed in here.
