### ISSUE TITLE
My priests have different mana regen

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#201]
Not sure if this is intended, but I actually find it pretty cool - makes me wish every raider had their own unique stats, so that what was optimal on each one changed

So Charynoth has 2.3 mana regen
![image](https://cloud.githubusercontent.com/assets/11687574/15883298/c7400420-2cfb-11e6-81f2-683cf743a005.png)

While Luki has 1.3 mana regen
![image](https://cloud.githubusercontent.com/assets/11687574/15883307/e1757aa0-2cfb-11e6-8d2d-440f204cc39c.png)

It's a pretty significant mana regen difference

**Comment by askebv** [comment]
It's an item set bug for Soul of the Frozen Coast. This is how you fix it:

https://github.com/Heishe/idleraiders-second-run/issues/189#issuecomment-224389778

> You can fix it as a workaround by unequipping the entire [Soul of the Frozen Coast] set, reloading the game, and then equipping the set again.
