### ISSUE TITLE
Can't unlock Crypt after reset

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#203]
I just "gained wisdom", progressed to level 10, and now the raid isn't showing up. But I can open the raid menu.

![image](https://cloud.githubusercontent.com/assets/4981659/15884009/91cac4d6-2d4d-11e6-8272-2ac2d6e72636.png)

Related to the fix of #110?

**Comment by Talisca** [comment]
Yep, its rleated 

As a workaround you have to reload the game.
