### ISSUE TITLE
Suggestion: Let Us ability to select monsters on farm map and show all monster names)

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#204]
Let Me know what name of the f... fantastic brown monsters from Map 29)

**Comment by AlexanderOtte** [comment]
![image](https://cloud.githubusercontent.com/assets/19685289/15895431/8dd769c2-2d8b-11e6-8b65-4a8367623edb.png)

**Comment by DaemoniaV** [comment]
Like I see them 
![256833910_dc5e794df2_b](https://cloud.githubusercontent.com/assets/19784493/15897309/adf7407c-2d9c-11e6-88ff-13f0fbcde7cf.jpg)

**Comment by TravisGesslein** [comment]
I think I can say yes to selecting farm monsters, but no to seeing all the names (for now), similar to #187 

Also this is related to #126
