### ISSUE TITLE
Hotkey bar appearing and reappearing under strange conditions

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#206]
I'm not exactly sure when the hotkey bar is supposed to be revealed or hidden. But with the option on, it's surely not always there.

I noticed that it always reappears when I turn sound effects on and off. It vanishes as soon as I change my view though. I tested it a bit, and it seems like it happens with non-audio options too.

If hiding the hotkey bar is for us to not use it incidentally, then I don't understand why it doesn't appear in raids, or at least when I'm dragging a usable item.

So I'm guessing this is a bug:

![image](https://cloud.githubusercontent.com/assets/4981659/15904165/3775d51c-2db0-11e6-83b9-25db7cd6858f.png)

**Comment by Talisca** [comment]
Seems to be related to #74
