### ISSUE TITLE
Charm lets you advance farm maps forever

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#207]
So, I'm in farm map 92 now - and my raiders are level 58 with a pretty decent setup (not optimized though). I realized I can't really do significant damage to the enemies now. Even if it's stunned and all my guys are going nuts on one guy, it's getting doubtful that I can advance much further - because their regen is getting near as powerful as my best burst damage.

But a charming shot makes at least two of them fight and one is bound to die, leaving the eventuality that I'll advance to the next level, and so on.

This seems a little overpowered.

But without tinkering too much with the skill, I think it would probably be best if the monsters had some kind of resistance against each other. Because right now, they almost always 3-hit each other. And as long as they can't fully kill each other for the full duration, it shouldn't disturb the balance too much.

**Comment by TravisGesslein** [comment]
Yeah that's a good idea.
