### ISSUE TITLE
Can't start raid due to missing raider

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#21]
The last raider doesn't show up after I started a raid:

![image](https://cloud.githubusercontent.com/assets/4981659/15736482/4bc09620-28a0-11e6-91fa-e0408ffd262f.png)

In this case it's my wizard, and the tracker tells me he's located inside a building. It doesn't show an arrow when I hover him though, so I don't know if he's really there, or if it just shows this place because he's nowhere:

![image](https://cloud.githubusercontent.com/assets/4981659/15736563/e150cfa2-28a0-11e6-97a9-ddea1e41005c.png)

I was running and viewing the second raid, then I viewed the base. And from there I launched the third raid right away.

After that, I put my raiders in sleep mode and then all raiders were present in the base. Then I tried to launch the 3rd raid again, and now the wizard got there fine, but both an archer and priest are stuck in the same spot.

It seems very frequent on the third raid, but I also had it happen on the first raid.

This is my base layout by the way:

![image](https://cloud.githubusercontent.com/assets/4981659/15736685/aa5723c4-28a1-11e6-9ee9-0901f4fa1e5a.png)

And after reloading the page:
![image](https://cloud.githubusercontent.com/assets/4981659/15736729/08805de4-28a2-11e6-9a0e-af2f964b803d.png)

**Comment by TravisGesslein** [comment]
Thanks for the detailled description, I think is related to #12 .
