### ISSUE TITLE
Repeat Bug - Overpriced Building 

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#211]
Just buy second Inn and got minus money.
![bug2](https://cloud.githubusercontent.com/assets/19784493/15914320/ab90c8fc-2de8-11e6-94d2-d5c0197803a9.jpg)

**Comment by askebv** [comment]
#164

**Comment by TravisGesslein** [comment]
Ah I now realize this happens probably because of the gold bonus upgrade. Can you confirm that you have it activated @DaemoniaV ? Or maybe @Muskar when you experienced the issue?

**Comment by TravisGesslein** [comment]
Yeah pretty sure, can reproduce with upgrade activated and fixed it now

**Comment by DaemoniaV** [comment]
Late for a few moment. Test with Church - price 480 with +20 Gold upgrade.

**Comment by askebv** [comment]
@Heishe I haven't really built anything since I got all available buffs built and too much money. And since I have 60k+ money now, I wouldn't be able to notice small differences in price very well. I just referenced the issue because I like having issues organized and linked well :P
