### ISSUE TITLE
Bug? - 0 drop

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#212]
Second group of monsters in Frozen Coast has 0 drop. They do not drop anything in first kill and after 5 try there is still zero.

**Comment by TravisGesslein** [comment]
Very strange, let me investigate :hankey:.

**Comment by TravisGesslein** [comment]
Ok we added the loot table reference for the one of the bosses last patch, but he only has optional drops. We forgot to add the loot table for the main dropper guy. will be fixed in Beta Patch 5
