### ISSUE TITLE
Bug: Enrage buff got enraged

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#213]
![image](https://cloud.githubusercontent.com/assets/4981659/15922721/89e3ffbc-2e29-11e6-84de-cdff7241d1fe.png)

I've only seen it happen once. My camera was away from the raiders at the time of the enrage buff appearing, and as you can see, it only happened to one of them.

**Comment by TravisGesslein** [comment]
Yup we identified a bug in the code that caused several effects such as this (the health bar bug was related). Should be fixed in Patch 5. It's possible that other similar bugs remain in the code, but I will close this until they happen again.
