### ISSUE TITLE
Again! Bug - 0 drop game bug 

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#214]
Last team of Monsters in Frozen Coast did not drop any items too(

**Comment by TravisGesslein** [comment]
Oh, the bug fixes won't show up until we actually upload the patch (Patch 5 should be uploaded in a couple of hours). When we close an issue here, it gets a milestone (on the top right), which means that it will appear to you players as soon as that patch referenced in the milestone is uploaded.

**Comment by DaemoniaV** [comment]
I thought that You talk only about second group of monsters. But third group too eas empty.

**Comment by TravisGesslein** [comment]
Oh yeah lol. That seems to be an issue with our internal editor, some previous edits have been undone. Should be fixed again when the patch is uploaded.
