### ISSUE TITLE
Red Priest bug?

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#217]
I have Upgrade for mana restoring. Seems they apply restoring mana only when cast health restoring. At the moment when health of rider is full mana again restore very slow.

**Comment by askebv** [comment]
My red priestesses heal my raiders even though they're at full hp, just to restore their mana.

**Comment by TravisGesslein** [comment]
No, this is just a visual issue, it uses the same animation and effect for energy regeneration, I'll change it :D
