### ISSUE TITLE
Burned out seal - Burning seal

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#218]
Any idea how to upgrade the item? I have the burned out seal and 10 essences but i see now way to use it.

**Comment by TravisGesslein** [comment]
Let me check if it's actually still working :hankey:

**Comment by TravisGesslein** [comment]
Nope, it's bugged, sorry about that. Will be fixed next patch.

**Comment by TravisGesslein** [comment]
Just btw, from that point onward the upgrade works just like in the alpha, but you only need 3 essences.

**Comment by thorbrian** [comment]
![image](https://cloud.githubusercontent.com/assets/11687574/15983854/aa39286e-2f69-11e6-9e6d-83f6251c1266.png)

FWIW, I have been doing this for a while, hoping it would work
