### ISSUE TITLE
Continued: Dragging an equipped item while having an equippable item selected

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#219]
#194 There's some minor issues still:

![image](https://i.gyazo.com/f5cc8570f8828dd41e54258bdedc0dab.gif)

Select equippable item, drag and drop the item from one slot to a slot of an adjacent raider of the same class, and you'll replace the item.

It's not 100% consistent, but pretty close.

**Comment by Talisca** [comment]
Okay, I probably didn't test this case. But thats good, I've got an idea to solve this more elegantly.
