### ISSUE TITLE
Sound effect of boss keeps playing forever

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#22]
The sound effect of the first boss in Gardens of Eternity keeps playing forever:

![image](https://cloud.githubusercontent.com/assets/4981659/15736819/ac3d7322-28a2-11e6-863b-730ad9e240c4.png)

At least in the case where you die to him, and he stops casting. The soundloop doesn't go away when I go to the base or to the farm map.

**Comment by Talisca** [comment]
Confirmed. Also the loop seems to be somewhat broken
