### ISSUE TITLE
Suggestion: Have a background for the level display

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#223]
The level display can be quite hard to see against some backgrounds, especially the snow ones:

![image](https://cloud.githubusercontent.com/assets/4981659/15940483/9827027e-2e7c-11e6-9962-c984533c4a6d.png)

![image](https://cloud.githubusercontent.com/assets/4981659/15940918/614ea98a-2e7e-11e6-8474-e5f9a5b1d9a3.png)

![image](https://cloud.githubusercontent.com/assets/4981659/15940700/88580cf2-2e7d-11e6-8384-9b080916fbee.png)

So why not make it permanently like it is against a black background:

![image](https://cloud.githubusercontent.com/assets/4981659/15940520/b1670efa-2e7c-11e6-8c99-873eecdea111.png)

Or another dark color, if you prefer:

![image](https://cloud.githubusercontent.com/assets/4981659/15940945/7f0b6a12-2e7e-11e6-8acc-328c6ec6a6c8.png)

![image](https://cloud.githubusercontent.com/assets/4981659/15940981/9ea5cc32-2e7e-11e6-9fd1-bffb448120f9.png)

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
