### ISSUE TITLE
Brown bears buffed as if an efreet is always present

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#224]
I've noticed the brown bears keep getting the buff visual on them, as if an efreet is there:

![image](https://cloud.githubusercontent.com/assets/4981659/15941338/f728b1d4-2e7f-11e6-8788-1d47e253f019.png)

![image](https://i.gyazo.com/e2f0f54b9bb97bdf30c7de7059ba8f34.gif)

I've only seen it with these brown bears, so I'm guessing it could be intended.

**Comment by Talisca** [comment]
Ah lol, we abused the brown bear to test the efreet-buffs during development. We just forgot to remove the ability :smile:
