### ISSUE TITLE
Level up sound is played way too frequently

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#225]
I don't remember if it also did this before level 50, but the level up sound effect triggers every 600 exp or so in level 52. So it's almost like it follows the scale that would be there without the soft limit increase in exp required.

**Comment by TravisGesslein** [comment]
Woot? That's very strange. Will investigate. Also can you send me your current savegame again? Would be helpful for this and the issue with the green buildings.

**Comment by askebv** [comment]
Hmm never mind - it's not the level up sound. I'm confusing the sound effects. The level up sound is the weirdly looped synth string in C major. The one I'm hearing all the time is Calming Shot I think (high patches bells with a delay effect). And that's because I disabled the "Remove Buffs" raider upgrade.

I've sent the save file for the green tint effect on buildings anyway.
