### ISSUE TITLE
Sugestion for other testers...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#226]
Let place there screen shots of inventory) Interesting to know there are any Level 2 Skill Books and look at other cool stuff)
![inv2](https://cloud.githubusercontent.com/assets/19784493/15942622/cc0510fc-2e8d-11e6-83d5-354a5611035b.jpg)

**Comment by askebv** [comment]
I haven't seen "level 2" skills other than frost shard. And I got 10 of them :P

This is my inventory:

![image](https://cloud.githubusercontent.com/assets/4981659/15942430/9bc31758-2e84-11e6-8220-e94233b61a50.png)

**Comment by askebv** [comment]
I might start over soon. Just to test if there's any early game bugs or imbalances that I haven't caught. I'm close to having tested everything I can think of in the endgame. There's just a few more ancient wisdom upgrades I can test left.

I'll probably keep this endgame savefile exported and saved in the cloud, just to check other stuff out, if I ever think of something.

**Comment by DaemoniaV** [comment]
Did You loot first sword from first slot of You first warrior in Chamber of Sealer?

**Comment by askebv** [comment]
I would guess so, because of its name (Burned Out Seal) but I don't know. I got it while AFK on auto-raid.
