### ISSUE TITLE
Aggro drawn from Hail of Arrows vs Icy Wind of Frozen Coast

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#227]
I think it's fair that Hail of Arrows aggros all enemies on the screen. But shouldn't the blizzard do that too? I suppose it's hard for it to decide which raider to go for. Perhaps you can just let it pick randomly between raiders alive on the map?

And also, future raids beyond Ravaged Abode should probably be immune to the icy winds damage - or at least have the effect somehow be more insignificant (perhaps just by making their HP much higher?). Because in longer raids like the Burning Cave, I've had it trigger twice on the last boss, before I've even engaged, and then the boss is significantly weakened.

**Comment by TravisGesslein** [comment]
Oh yes, regarding the first thing, we can do that but I'm not sure we need to. It's not really clearly a bad thing to have all monsters aggro, but also not clearly a good thing. If you're trying to get as high as possible you probably don't want to aggro the entire map onto your raiders, but if you're farming for gold on semi-hard maps having them all aggro and run towards your raiders so you can kill them faster is probably something you really want. In short it's kinda situational. What do you think about it?

Regarding the second thing, we should probably just change the behavior to behave similar to Hail of Arrows (only damage currently fought boss encounter).

**Comment by askebv** [comment]
After thinking it over a bit, I actually think it's fine that it doesn't aggro monsters. Especially because it will discourage people to have the full set on, if they don't want the aggro - and I'm not sure I like that - since the items don't have other powerful alternatives at this point.

The damage isn't significant on later farm maps anyway. And when you've defeated the raids enough that you have 7 pieces of the set, then you'll already be able to get so far in the farm level maps, that the unengaged enemies can regen the effect of icy winds fairly quickly.
