### ISSUE TITLE
Suggestion: Raiders team up before entering an area.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#23]
I am trying to get in high farm areas to get more ancients artifacts for my first reset and i noticed that in most cases my raiders go in one by one (because they are further away from the entrance, trapped in building or running around) and get killed before they team up. It would be nice if they either tp at the entrance together or team up at my base exit and only enter if more than 5 or 6 are ready.

(Raid 3 down, yay)

**Comment by askebv** [comment]
When I hover the description of the "ancient artifacts" it says I should get them when I defeat bosses for the first time and every 10th farming map I clear. But I have cleared 2 raids (and have unlocked farm level up to level 6) and have no artifacts. Is this a bug or have I misunderstood how it works?

EDIT: Ah nevermind, it says "70 earned after reset" in the bottom of the description.

**Comment by Ethismos** [comment]
My reset unlocked after beating 3rd raid and also managed farm area 24 by that time (at some areas i hae to kill 2-3 enemies and reset like they are bosses). I think i waster 500g on temple of the ancients though, it doesn't seem to do anything more than what the menu option for reset does... now i need 1000 gold to test the reset.

**Comment by askebv** [comment]
A bit off-topic (but the reddit seems barren):
I envy your abundance of ancient swords. I mostly got worn leather armor instead:

![image](https://cloud.githubusercontent.com/assets/4981659/15738037/9e2c74ac-28a9-11e6-9333-303417fcced3.png)

I haven't progressed with farm maps because it seems bad for gold gain, which is what I lack the most. But I'll make sure to try and progress farm levels before resetting. By the way, how does enchanting work? I've gotten a lot of them but I see no way to use them.

**Comment by Ethismos** [comment]
You can farm ancient swords at farm area 8 (camels and crocodiles). 45% chance drop from each enemy.

Edit: Haven't managed to do any enchanting yet.

**Comment by TravisGesslein** [comment]
We'll actually add this as a raider upgrade. When your raiders group up and heal before going back into farm maps for example, it's a giant improvement of their performance on farm maps. I estimate it'll bump the maximum farm level you can reach with idle farming by quite a bit (using the auto-increase-farm-map activity), and it should yield an increase in gold and xp per minute on 'difficult' farm maps as well. Should be a perfect subject for an 'AI upgrade'.

@Ethismos 
Whoops, that is definitely a bug. I think it applies to some other monster types as well.

**Comment by Ethismos** [comment]
If you mean the sword drop chance you can ctrl-f your code for probability: 0.45.

There are many monsters like: bear, white bear, black bear, green/blue/red snapping turtle, green/blue/red slime, green/red/brown lizard,red horror 1/2, weasel, crocodile, eagle, worm, crab etc... got 60+ hits total.

**Comment by askebv** [comment]
How would it increase gold per minute? Isn't it 1 gold for all enemies? So gold per minute is by far the best to farm where you get the highest kills per minute, which is rarely (if ever) the highest available map.

**Comment by TravisGesslein** [comment]
@Ethismos Yeah they are just a left-over we forgot about. Will be fixed next patch.
@Muskar Indeed! I meant the case where you want to farm a map (for XP or other reasons) that is hard enough that your raiders only kill monsters slowly and your raiders keep dying. Grouping up in that case should increase both xp and gold farm rate.

**Comment by askebv** [comment]
@Ethismos As a temporary solution, I've found that starting a raid and then cancelling when it's just about to start, is the best way to do this.

**Comment by TravisGesslein** [comment]
I implemented it, let's see how people like it. There are various options to handle it. Right now they will gather until every raider on the farm map is ready to go in again (as opposed to, say, waiting until ALL raiders regenerate in base, which would mean waiting until raiders in the farm map die and come back).
