### ISSUE TITLE
I can't seem to login - no way I can see to reset or remember my password

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#231]
After logging in the first time at https://beta.pitforest.de/idleRaiders it didn't ask me for login again, until yesterday. Now when I try to login, what I thought was my password doesn't work, and I can't see any way to reset it at all

my username is thorbrian (same as in github) and my email is the same as my username at gmail.com

**Comment by TravisGesslein** [comment]
Are you sure you created an account using name + password? Maybe you just used the google login at the bottom? Either way we can send you a new key if you want, your local savegames should still be there... as for cloud saves, we'll have to see if we can pull them out of the database somehow.

**Comment by thorbrian** [comment]
google login worked, got the cloud save - thanks!
