### ISSUE TITLE
Thoughts on "Increased movement speed"

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#234]
It works as intended, as far as I can tell. But as far as I understand, the primary reason to use the upgrade right now, is to improve the auto-raid times. And if your raiders are very fast, then the red priestesses have a hard time to keep up, so the advantage might even out. So maybe this upgrade also needs to affect red priestesses? Or have another upgrade for them? You could e.g. get an upgrade that increased their range instead. Because I kinda like them, aesthetically, as slow priestesses in big heavy robes.

Another use of movement speed, might also be for farm maps - getting just a little bit faster to your enemies. But in farm maps red priestesses usually hug the base entrance anyway, so then it doesn't matter I suppose.

**Comment by TravisGesslein** [comment]
Range improvement to priestesses sounds good

**Comment by TravisGesslein** [comment]
eh, on a second thought probably not gonna make it for patch 6.

**Comment by askebv** [comment]
I just realized that I can just trap my raiders, and then there's never a range problem :P

![image](https://cloud.githubusercontent.com/assets/4981659/15991089/9ea31416-30a8-11e6-8dc5-d3d7417e406b.png)

**Comment by TravisGesslein** [comment]
Getting back to this older suggestions, red priestesses now have a greatly increased range for their casts in general. Raiders and NPCs walking around in the base is just for cosmetics, it's not supposed to interfere with gameplay too much.
