### ISSUE TITLE
timeapi calls are blocked, due https security restrictions

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#235]
Currently when I open the game in chrome, there is a redirect to https, but then the http call to the timeapi is blocked, with the following error:

game.min.js:5175 Mixed Content: The page at 'https://beta.pitforest.de/idleRaiders/' was loaded over HTTPS, but requested an insecure script 'http://www.timeapi.org/utc/now.json?callback=AsynchronousTimeUpdate'. This request has been blocked; the content must be served over HTTPS.updateRemoteUtcDate @ game.min.js:5175

**Comment by Talisca** [comment]
Yeah, this happens because the timeapi is called over http rather than https (because their certificate is self-signed), so the user agent returns this network error and will not load the resource.

The error-handling for these calls is part of our todo-list.
