### ISSUE TITLE
Minor suggestion: Inventory class-filtering in a new game

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#239]
![image](https://cloud.githubusercontent.com/assets/4981659/15984350/d766d508-2fc7-11e6-8ec3-de1eb4f492f8.png)

As you can see, you can already see the 4 classes before you even have one of each. I would suggest hiding the options entirely when you only have a warrior. And when you have the first priest, then only show the warrior and priest and so on.

Small details like these help with pacing the game, and not cluttering the interface too fast. Much like the fact that you don't show UI buttons for building, raids, practice mode, ancient wisdom etc. in the beginning.

**Comment by TravisGesslein** [comment]
Good idea
