### ISSUE TITLE
Raid finish time

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#24]
I think you can abuse raid finish time by going out before the last boss and reentering. Its impossible that first raid takes me 1:20 and second 1:40 (its probably 3 times as much because i go back to heal every time), i think it only counts your last encounter. So you can go in, clear all trash/bosses except the last one and have the time restart.

There should probably be seperate timers for each dungeon that start the first time you enter them after a global reset and end when the last boss dies. It would be more accurate.

**Comment by TravisGesslein** [comment]
Excellent idea!
