### ISSUE TITLE
Gameplay gap after defeating The Crypt for the first time

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#241]
I thought I'd revisit the experience of starting out, now that I already know the possibilities of the game. So I've started a new game.

And I must say that the game has a pretty good pace up until defeating the Crypt for the first time.

At first you watch your raiders unlock, once you figure out how to put the warrior into farm mode. Then you unlock build mode and can prioritize which tents you buy first.
The merchant also shows up, but everything he sells is extremely expensive. If you make the mistake of thinking that there's plans that are a better early investment than the tents (like I did the first time), you're in for a setback. But if you don't, you'll shortly have all the tents.

Then you push forward on the farm maps, and starts struggling around farm level 5. And if you regularly check, you'll notice you have now unlocked raid mode. You're about level 10, and decide to check it out. At first you go without resting, but manage to kill the trash without dying. You have almost no mana left on your priests and less than 40 mana on both your mages, but your raiders continue on towards the boss. You die after having put up a decent fight.

This leaves you with the notion that you need to be a little stronger. Perhaps you figure out by accident, that you won't have to fight the trash again, if you relaunch the raid. Perhaps you think resting to get full mana might help you out. Perhaps you hastily conclude that you'll need more exp or gold in order to defeat this boss.

Either way, you're likely to shortly figure out that you can defeat The Crypt with relative ease, once you understand how the game works. You may find that you've looted an item from the boss, and figure out how to equip it.

And then the grind begins. You've unlocked the second raid, but you're absolutely destroyed by the first boss in it.
You can push the farm map levels, but you're still struggling at level 5 or 6, even though you've just looted a reward from the crypt. You neither really know what the rewards are for pushing forward any further, since exp and gold rewards don't seem better - and you're not noticing any special item drops.
The mysterious travelling merchant sells plans at 100 gold a pop, and at best you make a wooping 20-30 gold per minute. These plans unlock buildings that you don't know what does, since the plans don't say. Once you buy a few, you realize that you can't afford them by a long stretch - except for the decorative ones - which don't really help you progress. And if you start decorating, you'll quickly learn that you have to destroy buildings without any refund if you place them. This probably leaves you feeling that you need to be more careful with your use of money on decorations.

You may notice that the plans unlock pretty random functionality, and conclude that luck is a big factor into which plans he sells. Then you might keep buying plans, in the hopes that you just need to get lucky to get the right building. Or perhaps you just buy all the plans because you figure you'll probably need them eventually anyway.
After a while you probably conclude that the primary thing you need to do for a long time is grind exp, gold and wait for the crypt to reset.

Then the active gameplay opportunities pretty much disappear. And if I remember right, they only slowly return when you're able to defeat bosses in the second raid. And they don't fully return before you're able to defeat the third raid.
### Suggestions
1.  I think the game should start out by showing you how to start farm mode for the first time. This could be done by a notification. Or better, by a simple pulsing glow around the mode-button. You could also do it by the questing system that you've talked about.
2. Build mode shouldn't just appear. It should request some attention. This could also just simply be by notification or a simple pulsing glow around the button. It could also be by questing too.
3. The merchant arrives far too early, compared to how late his items are truly useful. I know he's just a dump for stuff you haven't decided on yet, but I really hope you find a better solution for this eventually. He's a confusing entry, and mostly seems to kill pacing optimism early on. At least at the current gold income and pricing balance.
4. As the game is now, tents should be emphasized as the best way to spend your money, for getting stronger in the early game.
5. Like in 1. and 2., raid mode should also reveal itself properly.
6. When you die in a raid for the first time, you should get a tip that you won't have to fight defeated bosses or trash again, if you relaunch the raid.
7. If you've launched the first raid twice, without having full hp or mana when you began, and died both times - then you should get a tip about resting before raiding. Getting tips that you don't need can be seen as demeaning, so this is why I tried to suggest these preconditions.
8. As I mentioned elsewhere (#53), it isn't immediately obvious that building plans go into the inventory, and needs to be activated before being able to build the building. At first glance, it might appear as if you've hit a bug and just wasted your money.

And the big suggestion is to increase gameplay options between clearing The Crypt for the first time, and clearing Gardens of Eternity. Requiring grinding and luck is fine - and I know you love that stuff. But options are important. And the best way to even out a grind, is to put optional goals inbetween. 

This could be many things. For starters, it could be:
- a bestiary (#187), to encourage exploring the different enemies (which could continue on later as well).
- optional quests where we're required to collect some things, or do some other tasks that require at least a minor level active engagement. These quests could reward a few items. As the game stands now, potions would be a great reward. They're good, but not game-breaking - and they're very scarce - especially in the early game.
- crafting/enchanting options. I haven't seen how it works in the alpha - but if there's ingredients that require active engagement to gather, and that make you stronger in a faster pace, then that's also a positive contribution.

If this gap isn't filled in eventually, then I think you'll miss out on a lot of potential players. As you in no doubt are aware, first impressions are pretty important.

**Comment by TravisGesslein** [comment]
If I remember correctly, this suggestion was from the beta. We have since implemented a short series of tutorials in the game at the start (really bare bones though) which covers some of these suggestions. But a lot of the other suggestions aren't covered yet so I'll reference this issue in the internal document. 

(copy pasted:) I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
