### ISSUE TITLE
AoE Yoda keeps using his magic if you call your raiders to sleep mode

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#244]
The Green Goblin of Gardens of Eternity keeps using his skills if you put your raiders to sleep mode during the battle:

![image](https://cloud.githubusercontent.com/assets/4981659/15987007/d20fd47c-3019-11e6-86bc-c65a996b24e9.png)

He stops after minute or two, but I still figure it's unintended.

**Comment by TravisGesslein** [comment]
Yoda is a girl!

**Comment by askebv** [comment]
sorry I'll be gender neutral next time :grin:

using their magic*
