### ISSUE TITLE
Some suggestion...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#245]
Hello, again in My brain born some thing.
1) Show the % of thing thaе I have. For example in game is 100 unique items I have in inventory 80 of them. So I have 80% all items.
2) Give some ancient for levelup 50+, 100 for 1 level will be good) . There is no reason to level up 50+ it is slow and increase of stats small. Today more profit level up 50, some raiding, reach farm level cap, reset, repeat.
3) Add Super Building when You build all other available on base to cap. Let it have switchable bonus for every class. For example 1) Warriors - Rage grow +100%, Rage fade slowed in a half, each warrior have 5% chance reborn when hp0 to full health (one time in one raid attemp) 2) Mage have 5% chance for each projectile do 5X damage. 3) Priest - select one ither raider - his become Saint - had 0 damage but twice effect of heal.
4) If was wonderfull to know some much more about future pathes. What are in next update& When it is come?
5) Let capped buildings in build menu show by red.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
