### ISSUE TITLE
Why are health bars behind everything else?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#246]
I'm sure you have reasons as to why health bars are behind everything else:

![image](https://cloud.githubusercontent.com/assets/4981659/15987365/e243bf1e-3025-11e6-8a48-b7f9856cbeb2.png)

Did you not want to cover up the raiders? Did you have prior complaints about this?

I'm asking because it's sometimes a bit inconvenient to not be able to see the health of a monster. Maybe it's just because I'm the kind of person who likes to track progress. And in high end farm maps, when monsters cluster around me, I want to see what progress I'm making. Of course I can just time it, or wait until my raiders die to see how they did - but that's not the same kind of fun. I like to be able to see and compare the damage that each raider's abilities' do.

But at the same time, I'm not entirely sure I just want health bars to always cover my raiders instead. Ideally I'd prefer a solution where I can tell where my raiders are, which is which, and what actions they're currently doing - and seeing the same for the monsters - while also being able to see their health when I want.

Perhaps a mouseover on the enemy could move the healthbar up a few layers, so it's behind UI but in front raiders? I don't really know how convenient or intuitive that is though.

Either way, I'd like to know your thoughts on the matter.

**Comment by TravisGesslein** [comment]
Lesser of two evils... putting them in front clutters everything so hard that you can't see your raiders fighting anymore. We DID spend a ton of time implementing a skeletal animation system and drawing lots of equipment parts so your raiders look prettier! :hankey: Regarding your suggestion with mouse overing: Well, you can already click them and have the health bars show up, not sure there's much of a difference, but I suppose it can't hurt.

What about putting a toggle in the options that decides whether or not to put them in front or behind creatures? I suppose this is a "I want this to be pretty" vs "I want all information available to me" thing which depends on what the player prefers. Of course there's probably a way to fulfill both of those things at the same time, but I can't think of anything specific (so if you can, pls do tell).

**Comment by askebv** [comment]
I think your idea of an "options" way is pretty good. I think you're right about it being a "I want this to be pretty" vs "I want all information available to me" thing.

For alternatives, my best bet is to think of World of Warcraft. There you have a hotkey (V is default) to show the healthbars of all enemies. When you don't have it on, you can still see the health if you have them as targets. But of course, here you often have many targets, so it's nice that this game always shows them all. Perhaps you can put a hotkey for it, and mention it in the option description e.g. "(hotkey: V)".

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
