### ISSUE TITLE
Building Plan improvements

### ISSUE THREAD

**Issue by TravisGesslein** [Heishe/idleraiders-second-run#248]
- They should be automatically used and the buildings unlocked when the plans are bought
- Add building description to the building plan description (including gold cost).
- 'new item' label similar to #247 should be shown on the base building button when a new building was unlocked

**Comment by askebv** [comment]
Equip slot bags should probably also be automatically used when bought. Same with buildings plans. Since there's no utility in not using them.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
