### ISSUE TITLE
Building buffs are not displayed correctly after demolishing

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#25]
As you can see, I have 6 warrior tents, and the maximum of 3 buffs here:

![image](https://cloud.githubusercontent.com/assets/4981659/15737493/9057be5c-28a6-11e6-82cb-d06f48b7c1f7.png)

When I demolish one more more of them, the buff disappears:

![image](https://cloud.githubusercontent.com/assets/4981659/15737513/a9ce7ca4-28a6-11e6-86bd-78f4f82252d7.png)

When I refresh the page, the initial warrior tent keeps showing up again (but the buff returns):

![image](https://cloud.githubusercontent.com/assets/4981659/15737597/2d9e7dd6-28a7-11e6-96ce-83946ac7c979.png)

Note, the reason I had to demolish some buildings was because my raiders kept getting stuck in the spot beside the leftmost well (where the bonfire originally is). They got teleported there a lot of the times. So now I demolished an archer tent instead, and fortunately that remains gone after refresh.
If I get the money to replace buildings, I'd definitely place them against the edges instead, to avoid issues like this. It seems like the center of the map makes it the biggest obstacle possible for the raiders.

**Comment by TravisGesslein** [comment]
Thanks for the description. Should be related to #12 and #6
