### ISSUE TITLE
First bosses in Burning Cave don't spawn in place after relaunch

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#252]
I launched the Burning Cave raid and died to them. Then I launched it again and one of them was suddenly separated from the others. I didn't manage to screen capture it, but it died right between where my healed warrior and front archer is:

![image](https://cloud.githubusercontent.com/assets/4981659/15990329/2088025c-3090-11e6-86d8-ffcb239480f8.png)

Then I killed 2, and relaunched again, finding this scenario:

![image](https://cloud.githubusercontent.com/assets/4981659/15990332/37e725e0-3090-11e6-8d96-ef5ee7b4cccd.png)

**Comment by DaemoniaV** [comment]
Confirm this situation sometimes in Frozen Coast with last gropu of enemy.

**Comment by TravisGesslein** [comment]
Should be fixed in Patch 6.
