### ISSUE TITLE
Consumables aren't used correctly when viewing another place

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#254]
So I just had a scenario where I had no scrolls of healing, but I wanted to use one in the raid fight. So I went to the base to buy one from the market, and use it right away. It turned out that it didn't actually apply to my raiders.

I recorded this in a second setting to show this:

![image](https://i.gyazo.com/5b9115e87e786a1d2315ac79b75fb794.gif)

I also tested that it neither works with Scroll of Brotherhood, and I'm guessing you know which others would be affected too.

**Comment by Muskar** [comment]
On an unrelated note, it really seems like the bug squashing is closing in fast. It's getting pretty hard to find new bugs now, which is pretty exciting stuff. Because that means you guys can get to work more on features soon :smiley:

**Comment by TravisGesslein** [comment]
Coming in a bit late, but should be fixed next patch!
