### ISSUE TITLE
Moving towards Beta Patch 6 or 7

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#255]
I just wanted to make a small discussion topic, because it really seems like the bug squashing is closing in fast. It's getting pretty hard for me to find new bugs now, which is pretty exciting stuff. Because that means you guys can get to work more on features soon :smiley: 

Good work, gentlemen! :tada:

**Comment by TravisGesslein** [comment]
We just uploaded Patch 6!

**Comment by DaemoniaV** [comment]
You can share with us by nearest game features.

**Comment by TravisGesslein** [comment]
Nearest? Well, the reintroduction of the crafting system and the book of prophecies will probably happen at the same time, there's almost no code work left for them (book of prohpecies has to be slightly altered from the old quest system), just creating prophecies, and stuff to craft. Together with that we will probably release another raid. 

After that the only thing that is left is to release. But alongside all of this stuff we'll also do stuff like optimize the performance of the game, of course bug fixing and other content creation (more upgrades, mercenary types, etc.). Dunno in terms of timeline though.

**Comment by DaemoniaV** [comment]
Did You plan to remove "50 level wall"? As My opinion in Alpha the items has little value and You level is very important. When new raid release sometimes You clearly understand that no items can help You need serious level up. In beta 50 level achieved in couple of hours. There is no so feel when You some days try beat Raid and see slow progress by boss hp left after wipe of You team. Three days ago left 8000hp, two days ago 6000, yesterday 2500, today 1000 only. Great feeling that You beat the raid tomorrow. Let the scheme kill first group of bosses get loot, equip it and defeat second group still there but for killing first group of bosses You need some high level - 5-7 days non stop farming alongside the best items.
Today My game count 6 days, at 4 day i beat last Raid. It is very fast. It good for beta that we can fast achieve last raid and all content for test but for release it not good. IMHO. Let for every Raid beat you need 2-3 days level up minimum.

**Comment by askebv** [comment]
I've grown to like the soft wall at level 50. I didn't like that you needed exponential levels in the alpha, to get any meaningful stats. Like you said, it diminished items to very low value.

I agree with your worries though. For now, the gameplay is finished way too fast. At least if you consider raid bosses a way to measure how strong you are. And I like seeing it like that.

But just dragging out the requirements won't make it better (like lowering item drops, or returning the exponential leveling system). I think it's better that they even out the curve with more content, like whatever the prophecy and crafting system does, and so on. So more things to do, in between the raids.

**Comment by DaemoniaV** [comment]
Agree with some Muskar thoughts. Core of My message "Game is to easy". Want that every new raid - "Punch into face", like a drunk bear and You do not know how to restrict him.
Four days of non stop farming for every new raid good time. There are some different ways to fill this days by interesting game process.
1) Do the buildings on base more capped but much more powerfull and expensive. Let Weapon Smith have for start cap 2, +10 bonus for each and price 10k and 20k. When You beat R1 cap increased by 2 by price 30 and 50k. R2 do nothing. R3 add two more cap.
It requires minimum 1 day of gold farming at first farm map.
2) Leveling is hard question for me. I am do not like 50 level wall. But may be other like Muskar do not like exponential level. May be there is moving cap let level 50 at start and +5 levels after each raid. You need 1 day of farming on last aviable for You team map for reach this. Let this levels do much more stats increase.
3) Enchantments - on some farm maps add new enchantment drop. You need 1 day to farm it necessary for beat next raid.
4) Reduce % of drop. Remove bonus items on first kill after soft reset. Replace it by simple more drop chance. + 100% drop chance for fist kill after soft reset. And let upgrade increase it to 200% and 300% for huge price - 200k and 500k. May be just really first (not after reset) kill just give one new item with 100%.
5) May be some quest need to be done simple to access to new raid and it requires 1 day of active gaming. Something like I wrote about Old Slime Hunter)
What do You think?

**Comment by askebv** [comment]
Getting to level 60+ isn't so hard after a few resets. All it takes is ancient wisdom investments into "More XP" to help you out. Eventually it'll become pretty easy - so you still have the exponential levels - they're just not as dominant, as before. Which is what I like.

As for quests that will give you items to be able to do raids faster, I love that idea. As the developers stated elsewhere, I think it should be possible to slowly complete the game with very little activity - but I also think there should be fun ways to accelerate your progress, when you have the time to do so.
But if the quest is just about getting some lucky drops, then I think there's less potential. Some could get really lucky, others could make a big effort and still not gain an advantage over being idle - and that can feel like a punishment.

In general though, I do like the idea of requiring something done, in order to access some higher level raids. But it needs to be intuitive. Perhaps some optional raids can show up, greyed out, and require quests completed. Perhaps raiders would have to go on non-killing missions, like gathering herbs, mining veins, converting items into materials and recrafting them etc. etc. This is pretty typical in RPGs of course, but I think it could be cool.

**Comment by askebv** [comment]
I just drew a small illustration of what I think the optimal overall progress should feel like:

![image](http://i.imgur.com/5RYTfSU.png)

This is what I learned from Adventure Capitalist. Progress should feel easy and fast in the beginning, and then it should slowly transition into slower progress speeds, as you approach the end. The more time and effort you put into it, the more rewarding progress will feel like, once you've already grown to like the game and its mechanics.

As seen in the illustration above, idling still gives (diminishing) progress, and when you return, you have the opportunity to utilize some of your idle rewards for a quick progress boost, which essentially gives you the possibility of getting back on the same pace, but just at a delay of the most active players.

This is how I feel like Idle Raiders Beta feels like at the moment:

![image](http://i.imgur.com/GUVLxqA.png)

So on that front, there's some ways to go. The alpha might have been closer to the first illustration, but I like the Beta more for other reasons.

And pacing isn't everything. As I see it, the main game mechanic challenge of Idle Raiders right now, is fun things to do, on the way to the end. The infinite scalability of harder raids and better items over time is already there. So here's another illustration for what I see as optimal:

![image](http://i.imgur.com/sUaCUH7.png)

Starting out small, as you learn the game, introducing new opportunities at a steady pace, and then slowing down pace of new things, keeping it on a level where there's not an overwhelming amount of stuff to do, but still enough to keep you engaged and occupied, if you want to.

This is how I see it in Idle Raiders at the moment:

![image](http://i.imgur.com/vfJHeTI.png)

The first drop-off is after the 1st crypt. The small bumps are when new items and raids are obtainable, and then the ending bump is the introduction of ancient wisdom, which then slows off because the game becomes super easy towards the end, where you can basically idle through the last raids, as long as you log in to equip the new items obtained. Although, it really depends on your mage skill luck, as their relative damage output matter greatly to your success with raid bosses.
