### ISSUE TITLE
Bug? Burning Seal and Essence of Rage.

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#256]
When I create My Burning Seal it spend all My essence of Rage - about 10 items. Is it correct?

**Comment by askebv** [comment]
How do you use the essences with the sword?

**Comment by DaemoniaV** [comment]
Just double click on grey color sword in time of raid in Chamber of Sealer.

**Comment by thorbrian** [comment]
FWIW, it didn't take all my rage. I got left with 3. I don't know how many I had before, but it was more than 10.

**Comment by askebv** [comment]
Btw, I hope the questing system will hint how this weapon is obtained in the future. If you keep it a secret, it'll just be voted up as a top comment on Kongregate and take a slot there. And if you advance to Steam, people will probably need to go to forums and otherwise to realize it.

**Comment by thorbrian** [comment]
FWIW, I guessed that the sword could be recharged with essence of rage from the description (where it mentioned burned out of rage) but the part I would really never have guessed was that the burned out seal could be activated, like an item.

I assumed I had to make this work through equipment choices, so had been farming like this:
![image](https://cloud.githubusercontent.com/assets/11687574/15994118/0abb7894-30b0-11e6-8d20-c0820d42f7a6.png)

**Comment by askebv** [comment]
Yeah same for me. I hypothesized things like getting 100 rage with 3 essences and the sword equipped or defeating certain bosses with it. I also tried double clicking the item to use it, but I never thought of using it in the specific raid.

**Comment by TravisGesslein** [comment]
Yup, there will be prophecies for stuff like this which the player can find. Some of them along a set unlock schedule, so to speak (i.e. new prophecy is unlocked when certain conditions are met), some just random world drops, in the form of Scrolls. Burning Seal will probably be a random world drop. You can do all of this stuff without the prophecy, that is just a feature for people who don't like reading Wikis and instead like discovering stuff for themselves.

**Comment by TravisGesslein** [comment]
So here's what should happen btw: When you create the Burning Seal, all rage essences should be removed from your inventory (and they should also stop dropping in the world). @thorbrian has essences left after creating the Burning Seal? Woot

**Comment by DaemoniaV** [comment]
They do not stop drop. After creating Burning Seal I got already four essences.

**Comment by thorbrian** [comment]
I may have kept 3 essences of rage because I had 3 equipped on my raider?

**Comment by TravisGesslein** [comment]
Oh yeah, they are only deleted in the inventory. It's not actually an issue so I won't fix it (at worst, in the crafting system later you will get some additional mats out of them). 

But they should definitely stop dropping, will look into it.
