### ISSUE TITLE
Saving Throw is used on mercenaries

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#257]
![image](https://cloud.githubusercontent.com/assets/4981659/15992397/2977b26e-30cb-11e6-84fb-e62d74e21136.png)

**Comment by askebv** [comment]
I think some of my abilities are also making the mercenary attack my raiders. I'm guessing some of my warrior skills, but I haven't caught it yet. Here's the skills I'm currently using:

![image](https://cloud.githubusercontent.com/assets/4981659/15992413/a9f95b90-30cb-11e6-9bb0-e9f7be6543a0.png)

**Comment by askebv** [comment]
My priests neither heal the mercenary, so maybe he's seen as a semi-enemy?

**Comment by Talisca** [comment]
Its true that the mercenary is sometimes not regarded as an ally. But the priests should heal him regardless as long as his family is not overwritten

**Comment by askebv** [comment]
Yeah I later noticed I was wrong about the healing. I just noticed that he always died in Ravaged Abode, and that he didn't have full hp. In reality, it turned out that I had overheal on, and that all my other raiders also died on Ravaged Abode, so the world makes sense again! xD

**Comment by thorbrian** [comment]
FWIW, I get this all the time, but don't have command or challenging cry equipped

It's pretty hilarious watching the mercenary go stab a boss enemy, then go stab one of my raiders, only to get stunned by a no look saving throw, and have him just repeat that over and over again

bad mad dog
