### ISSUE TITLE
Suggestion: Make filtered items less visible

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#258]
I can't seem to find where I said this elsewhere, but I was just searching for a priest item and for everything else than uncommon items it's still pretty hard to tell which items I can use:

![image](https://cloud.githubusercontent.com/assets/4981659/15992455/3d2e00c2-30cd-11e6-9ffd-832c9ebdc239.png)

The white color from the numbers stand out far too much, so I'd suggest darkening those. I might even prefer if you made the rarity background slightly darker as well.

**Comment by thorbrian** [comment]
Yeah, the filtering doesn't really work for me either. Ideally, I'd just not see the other stuff at all.

**Comment by Talisca** [comment]
Your wish is my command.

**Comment by Talisca** [comment]
![class-filtering](https://cloud.githubusercontent.com/assets/9008844/16005438/93d50566-3167-11e6-8d03-2d81d676d3da.gif)

That would be the upcoming behavior. All non-matching items won't be shown at all.

**Comment by askebv** [comment]
Is [the ultimate question](https://www.youtube.com/watch?v=aboZctrHfK8) how many Worn Leather Armors you have?
