### ISSUE TITLE
Mercenaries aren't initially sorted right when hired

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#259]
When you buy the mercenary and have the sorting set on "by class", the mercenary is put in between the mages:

![image](https://cloud.githubusercontent.com/assets/4981659/15992566/7fea8d20-30cf-11e6-9aab-8b2a81d82710.png)

But when you sort again afterwards, it's sorted between all mages and all warriors:

![image](https://cloud.githubusercontent.com/assets/4981659/15992577/c184f324-30cf-11e6-96f2-8c55fa2776a3.png)

Every time to try to sort by class, it will interchange between these two. But if you then sort by "none", and the sort by class again, it goes to the top:

![image](https://cloud.githubusercontent.com/assets/4981659/15992589/f5c03ee6-30cf-11e6-8841-d9189020be0f.png)

Regardless of what's intended, I would probably prefer if they were put at the bottom both when you sort by none and by class. This is because the bottom seems to correlate with something "extra", and also to keep the standard raiders in a consistent spot, in the sorting modes where that is expected. Sorting by HP and damage is obviously expected to change. And sorting by name obviously has ordering exceptions when raiders have identical names.

**Comment by Talisca** [comment]
This is indeed a bug. Currently its still sorted by the classes Warrior, Archer and Priest. All others will be put anywhere.

> Regardless of what's intended, I would probably prefer if they were put at the bottom both when you sort by none and by class.

I agree with you.
