### ISSUE TITLE
Cosmetics slots on mercenaries

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#260]
Unless you want us to be able to decorate our mercenaries in the future (and preferably keep the items when they die), then I'd suggest removing the cosmetic slots from them:

![image](https://cloud.githubusercontent.com/assets/4981659/15992631/db9c9d88-30d0-11e6-9bbd-4889442367c3.png)

And in case you didn't even intend for players to be able to view this window for mercenaries, then I achieved it by hitting the arrows, by the name.

**Comment by thorbrian** [comment]
I love this feature. 

Mad Dog never looked so good:
![image](https://cloud.githubusercontent.com/assets/11687574/15993977/3adf1076-30ab-11e6-9aef-b48cb08f81aa.png)

I don't even mind that it costs me an item per.

**Comment by askebv** [comment]
Oh, I tried several items on him with no success. Then I agree, keep it. Regarding items, then it obviously doesn't matter now when we have an abundance of items - but depending on what excess items are used for in the future, I'd at least keep this use in mind. And if we get a use of excess items, and mercenaries still make you lose the items you decorate them with, then there should probably be a way to warn the player in the future.

**Comment by TravisGesslein** [comment]
Sorry, but we must remove this :D Introduces a ton of code complications and works against the concept of the mercenaries - zero customizations, characters with their own predefined identity (in terms of looks, lore and abilities etc.) and usefulness.

We know people might want to make them prettier, but that's one of their trade-offs. You get an "11th raider", but weakened in several regards compared to the other raiders.
