### ISSUE TITLE
Mercenaries and taunt/command skill

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#261]
It seems that there's an issue with mercenaries and at least one of the taunting-type skills. There's a permanent red exclamation mark floating far away from him (check upper part of the image), but it follows the mercenary's movement and orientation:

![image](https://i.gyazo.com/bdec08f31ca4a4e2538b730c8559871a.gif)

After recording that, I also realized that the stun the mercenary received from Saving Throw has moved up to around the center now - which might be related.

**Comment by Talisca** [comment]
How... Its funny, because the red exclamation mark is never attached to the creatures. :(

**Comment by askebv** [comment]
I don't know how it happened honestly. I was just in normal farm mode with my mercenary, to test stuff out, and after about 10 minutes I noticed this.

**Comment by TravisGesslein** [comment]
This should have been fixed as part of some other issue fixes. When object pooling was added to reduce garbage collector overhead, we sometimes reused objects without cleaning up their hierarchies first (all children, etc., remained), which is probably what caused this issue. Looking over the current code it seems like this shouldn't happen anymore, so I will close this older issue.
