### ISSUE TITLE
Mercenary guild's advertised stats

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#262]
The Mercenary guild says the mercenary for hire has 100 Max HP and does 4 damage:

![image](https://cloud.githubusercontent.com/assets/4981659/15993037/2ad9f30a-30db-11e6-910b-ddf78642fd42.png)

But he actually has 1900 hp, and does 19 damage:

![image](https://cloud.githubusercontent.com/assets/4981659/15993040/47b32302-30db-11e6-8fc7-44268fcce21f.png)

I'm level 61, if that matters.

**Comment by Talisca** [comment]
Yeah, the stats shown above are the initial values for Mad Dog at level 1. After he is hired, he will level up to your current raider level.

**Comment by TravisGesslein** [comment]
We should show the scaled stats :hankey:

**Comment by Muskar** [comment]
@Heishe Is it intended that mercenaries don't get their stats increased when you level up, while they're hired?
