### ISSUE TITLE
Boss still attack...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#264]
If You give commnand raid at a the same raid where You fight the bosses go to attack You team.
![bug3](https://cloud.githubusercontent.com/assets/19784493/15999927/9ef76198-3151-11e6-87d8-91b1b8d678d2.jpg)

**Comment by askebv** [comment]
I'm not sure what you mean. When I change from auto-raid to raid mode, or raid mode to auto-raid mode, nothing changes, as long as it would try to do the same raid. This is a new feature in Beta Patch 6.

Is this not what happens to you?

**Comment by DaemoniaV** [comment]
Seems that when Tou fast relaunch raid current fighting boss do not reset target. When My party wait all member at entrace boss run to them throught all map.

**Comment by askebv** [comment]
Ah, now I get it. I also see that the boss is way down the map, far away from where he's supposed to be. So how do you do it? Do you put it in sleep mode and then quickly back in raid mode?

**Comment by DaemoniaV** [comment]
No.Just double click on active raiding icon (shield with sword) it open/close list of modes and open raid menu. Then click same raid and press "Strat Raid".

**Comment by askebv** [comment]
Nothing happens when I click "Start Raid", when I'm already in the raid:

![image](https://i.gyazo.com/c2fdaec66f321f20961a4269d7e517d8.gif)

**Comment by DaemoniaV** [comment]
Strange same to me. Trying to repeat it.

**Comment by DaemoniaV** [comment]
It like You said previous. Fast Sleep mode and then Raid again provoke bosses to run to You team.

**Comment by TravisGesslein** [comment]
Yup, can happen in rare circumstances. Will be fixed in Patch 9.

**Comment by TravisGesslein** [comment]
It seems that it was possible to abuse boss fights by letting a raider start a ranged attack, then quit and restart the raid before the raider can spawn the projectile. This would lead to the projectile spawning when the raider stands at the entrance of the map, flying all the way over to the boss and only aggroing that one boss even if its a boss group. In patch 9, the entire boss group will aggro if you do that.
