### ISSUE TITLE
Some question about drop rate...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#267]
My team spend 2 days in non stop Auto-Raiding mode. They able to kill all monsters except last in last Raid. I have all elements of sets except - Warfists of Frothen Coast and Blizzard Walkers. Drop chance 300%. Does all normal with drop table? I am simple unlucky?

**Comment by askebv** [comment]
I got the full Soul of the Frozen Coast set without any item drop chance upgrades - so I'd say you're either unlucky or a victim of a bug. It depends on how those set items work. I.e. if there's supposed to be a guaranteed drop every X runs.

**Comment by thorbrian** [comment]
FWIW, even at level 50 with basically every item and both sets fully equipped, when I am on auto-raid, I notice my raiders don't consistently finish burning cave and frozen coast on a single raid attempt, and if they fail at all, they don't retry or continue until the next global reset.

If you want to check if this is the case for you, check in on them when auto-raiding and see which raids are finished (i.e. have the red text in their hover) and which aren't. I was finding that they usually had not finished frozen coast.

I actually finished both the fire set and ice set of equipment through manually beating each of those raids - i.e. checking in on them, noticing that not every raid was finished, selecting the unfinished raid, and then getting the needed items on that manual run.

**Comment by DaemoniaV** [comment]
My team Auto-Raid all raids except last one. All raids except last have red text that they cleared. No doubt. There is another 12 hours Auto-Raiding with 400% drop = 0 new items.

**Comment by askebv** [comment]
As thorbrian says, idle raiders are often not consistent. I've found my raiders sometimes lose on Frozen Coast one time, and then the next time they even clear Ravaged Abode. So you can't be sure that they clear the raids every time on idle mode.

**Comment by DaemoniaV** [comment]
Since three days ago I rebuild skills My team come to last three bosses of Frozen full ready. Priest with almost full mana and they regen faster than spent. I look for them 8 attemps in a row. They easy clear Frozen raid. So another 24 of raiding with 500 drop no result. Sure this is some bug with drop system((((((

**Comment by thorbrian** [comment]
I looked up the item drop chances - turns out they are both from the Ravaged Abode, so that is probably why you haven't gotten them. Looks like if you manually grind through Ravaged Abode, you should get them quickly

Blizzard Walkers are a 10% drop from the Centaur boss pair
Warfists are a 10% drop from the Yeti boss pair

I'm guessing the Yeti boss pair are killing your raiders on auto with the AOE ice spell.

**Comment by DaemoniaV** [comment]
In 50% they do it in 50 raiders kill them first. Keep trying manually. Thx.

**Comment by TravisGesslein** [comment]
Yeah, two of the set items drop in Ravaged Abode. We kept it this way because the raids are thematically similar, and geographically very close, makes sense to drop the frozen set in both.
