### ISSUE TITLE
Priest priority list glitches

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#268]
I'm not sure I understand exactly how the priority list works. Take the following scenario for example:

![image](https://cloud.githubusercontent.com/assets/4981659/16010138/2c4d09f2-3180-11e6-9f3b-0122e4806655.png)

There's two raiders in need of healing, but all my priests seem to do are rejuvenation. They don't even cast basic heal. Take in mind that Overheal is off at this point.

So is there some internal cooldown or something that prevents the priests from casting something else? I thought that the priority list looked at each item and saw whether it could afford it, and whether it was on cooldown, and then executed the first one upholding all criteria.

**Comment by askebv** [comment]
Okay, after refreshing the page, it looked like this:

![image](https://cloud.githubusercontent.com/assets/4981659/16010554/021b58da-3182-11e6-9da2-2e58fec5e50b.png)

And now my raiders are healing normally again. However, if I unequip all my flash heals, and then re-equip them, I get this:

![image](https://i.gyazo.com/3dfec4e72c0dfc5f0c1a689ba47ceee5.gif)

Note the first one replaced the duplicated rejuvenation slot with flash heal. The only thing I did different for that one was move the duplicated rejuvenation back and forth first.

So then I tried moving the skills around on the second raider as well, and then everything but flash heal vanished. Even Basic Heal!

![image](https://cloud.githubusercontent.com/assets/4981659/16010707/b4c9fcfc-3182-11e6-995d-92d8d2cd31a1.png)

Then I refreshed it again, and everything works like normal again.

I'll investigate and see if I can reproduce it.

**Comment by TravisGesslein** [comment]
Does the list in the first screenshot (with the duplicated rejuvenations) look like that every time you reload that? If you could send me that savegame in that state it would probably make it easy to debug the error.

**Comment by askebv** [comment]
@Heishe A few minutes later, it happened again, but with rejuvenation, healstreak and basic heal still working. I refreshed and now have two basic heals. I exported my game and sent it to you. Hopefully it's still glitched when you receive it. Otherwise I'll make sure to export one where I notice it glitch before I refresh the page.

**Comment by TravisGesslein** [comment]
Yup, glitched for me too. I'll investigate it

**Comment by TravisGesslein** [comment]
Alright, the glitch is fixed (dont worry it didn't take me two days, I was busy with optimization)... now to automatically fix broken savegames...
