### ISSUE TITLE
Burning cave gold/exp farm.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#27]
There is a similar issue with the old raid 5 at the new burning cave. You can start fight 1, kill1-2 enemies, go out, go back in, both enemies are up. I am not 100% sure if it is better than farming a normal area, but depending on the gear it could be abusable.

**Comment by askebv** [comment]
Well, it's a lot more difficult to do than having it on auto-farm. And if this game solely relies on WoW mechanics, then I believe trash mobs are always possible to farm - except that they also have (shorter) respawn timers. Or do you mean bosses when you say "1-2 enemies"?

**Comment by Ethismos** [comment]
Judging from the fact that i can see their health, they are bosses. They have 2.3k to 4k hp and drop 30+ gold and exp. Right now with my gear its not worth it, but it will soon be i think. Its the first camp of old raid 6, the one with 3 demons, one holding some kind of whip.

**Comment by TravisGesslein** [comment]
Ah, you mean boss encounters with multiple boss monsters in them. True, that is very much unintended. We should delay the XP and gold rewards until the entire encounter is defeated, just like we do with item drops.
