### ISSUE TITLE
Fixed cost for soft resets combined with "More gold" upgrade

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#270]
I'm not sure I think those are a great idea. Thus far, we don't really need more money than 1x can buy, so all the "More gold" upgrade really does is accelerate the rate of possible soft resets which, in turn, further diminishes all the absolute costs that this game have.

I don't know your longterm plans, but the first thought I had was to tie the cost of soft resets to lifetime earned ancient wisdom, combined with the ancient wisdom to be rewarded. That way, there'll be a natural limitation as to how many soft resets you can do, where the "More gold" (along with future ways to make more gold) will be a way to increase that rate.

Or you could leave out the "More Gold" upgrade entirely for now. And do something more fun and clever later on.

Anyway, just spraying thoughts as usual :wink:

**Comment by TravisGesslein** [comment]
Scaling it with the rewarded Ancient Wisdom is a very good idea.

**Comment by askebv** [comment]
@Heishe Oh wow, I didn't expect that to be implemented so soon. I'm excited to check out the implications of this. I'm guessing the factor will probably require some tweaking.
What is the formula you have implemented now?

**Comment by TravisGesslein** [comment]
earned points \* 10 :hankey:

**Comment by askebv** [comment]
@Heishe And what is "earned points"? Is it:
1. Claimable points (the number in the bottom of the tooltip)?
2. Prior earned points (let's say I have Overheal unlocked and 30 unused points - that's 530 total)
3. The two above combined

From the price, it sounds like the first option.

**Comment by TravisGesslein** [comment]
It's #1. I like the word claimable

**Comment by askebv** [comment]
@Heishe Yeah - I actually had a little bit of difficulty finding a good word for it. Turns out it is a word, just mostly for scrabble games and pretentious Internet comments :wink:
