### ISSUE TITLE
Using a snapshot does nothing

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#271]
Weird. I've used snapshots a few times in prior patches, and the stuff worked fine. But now nothing seems to happen. Even after a refresh, my snapshots don't seem to do anything except put everything on cooldown.

**Comment by Talisca** [comment]
Maybe you are missing some of the items in the snapshot. Hm..

Could be easier to see if the information in the mouseover-info would be somewhat formatted. I think its time to overhaul the shown infromation

**Comment by askebv** [comment]
I tried saving a snapshot of what I had on, and then changing one item, and then using the snapshot. Nothing happened - not even an error message.
Maybe it's because I still have 2 Arctic Honors and 2 Frozen Chestplates or something like that? I sent my snapshot to the email anyway.

**Comment by Talisca** [comment]
Your snapshot "Normal" is not usable, because you are missing the Hail of Arrows Skillbook.

**Comment by askebv** [comment]
Hmm, that's weird. I thought I disabled that upgrade after I tested this the first time. But if I enable it, it seems to work fine. So either you're right, and there's no problem (except that it doesn't show an error) - or I just can't reproduce it right now.

**Comment by Talisca** [comment]
In the coming patch you will be notified by an error with the amount of missing items. :D 
I don't want to list all of them, that would be too much.

**Comment by askebv** [comment]
Yeah, I'll just open another issue in a later patch if the issue turns out to be what I originally thought it was. Thanks.
