### ISSUE TITLE
Raider in lava stuck)

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#273]
![bug3](https://cloud.githubusercontent.com/assets/19784493/16052300/4a6403d6-326c-11e6-9887-9b9a0d3d1777.jpg)
While all team wait on raiding it lazy archer he cool in lava)

**Comment by Talisca** [comment]
There seems to be something awfully broken. You are on a farm map, but your activity states that you are in the Crypt raid?

Is there any chance you had the developer console open at the time?

**Comment by DaemoniaV** [comment]
I was on Auto-Raid. When timer is count to zero my team left farm map and after rest try begin Crypt raid. But one raider stuck in the lava and team stay at entrance of crypt. If this is cath again then try console.

**Comment by TravisGesslein** [comment]
The collision layers of some of these tile maps had some holes. I assume the raider opped through. Fixed in Patch 7
