### ISSUE TITLE
"Old Cane" duplicates itself when used

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#274]
I found an "Old Cane" piece of equipment when grinding farm level - it's equippable by all classes, but appears to do nothing when equipped.

However, when I use it (double click) it seems to just give me more canes, without any limit

![image](https://cloud.githubusercontent.com/assets/11687574/16073218/c12ba24e-3299-11e6-9900-9df4de7586aa.png)

Is it supposed to do anything at all?

Checked javascript console, and am getting this error:
game.min.js:4588 Uncaught TypeError: Cannot read property 'cooldown' of undefined

**Comment by Talisca** [comment]
By using the Old Cane, you will trigger something special. But we removed this special thingy for the beta without checking the Old Cane :D

**Comment by DaemoniaV** [comment]
Does Old Cane remove from drop at this moment?

**Comment by TravisGesslein** [comment]
Nope, should still drop as usual. It does have an extremely low chance to drop though, and the raid associated with it shouldn't  yet be unlocked (in any case, it's not balanced).

**Comment by DaemoniaV** [comment]
Does it specific area drop? Or it can drop everywhere?

**Comment by TravisGesslein** [comment]
(It's a global random drop). My email inbox said you asked about it, but now the message is gone :hankey:

**Comment by DaemoniaV** [comment]
Yep. I delete the message. Cause - re-reading You message and think that cause the Raid is not unlocked it does not drop. I am still 24h idle every day but do not get it)
