### ISSUE TITLE
Hovering over bowstring slot in cosmetic equipment window triggers javascript error

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#275]
Everytime I hover an item over the "bowstring" slot of the cosmetic equipment window, I get this error:
game.min.js:4468 Uncaught TypeError: Cannot read property 'indexOf' of undefined

... and come to think of it, isn't there only one bowstring piece of equipment?

**Comment by askebv** [comment]
Yes, there's only one bowstring, unless you got more when the glitch of multiple drops was still in the game.

**Comment by Talisca** [comment]
Happens because of an additional check. Bowstrings are somewhat special and not all items will modify the raiders. Will be fixed soon.
