### ISSUE TITLE
Hey, you! The travelling merchant just arrived with nothing available!

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#277]
I don't know your future plans with the travelling merchant - but I think it would be nice if the merchant (at least the notification) didn't show up if he didn't have anything to offer. I don't mind him showing up from time to time, even if he has no utility - if that's something you like. But I think the notification is completely unnecessary. In fact, I think it indirectly devalues the importance of checking the notifications because you get the sense that "oh it's probably just the merchant, so it's probably not worth checking out" when you see one notification by itself.

"The Boy Who Cried Wolf" comes to mind.

**Comment by TravisGesslein** [comment]
Closing this, merchant always offers something now, some items are repeatedly sold (crafting resources, for example).
