### ISSUE TITLE
Pathfinding ignoring other raiders

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#28]
I'm assuming their pathfinding is supposed to be stupid when you start out. And that you can improve them greatly later. It makes the warriors push the others into fights, which is probably an intended feature of their initial stupidity.

However it makes some weird glitching behavior sometimes. Especially when they're roaming or if they're farming, going at opposite targets. They rub hard against each other and sometimes starts jumping around, sometimes even teleporting a bit.

I think it would probably be better if they at least realized that they were stuck, after a few seconds of standing still (or not improving their distance to their next waypoint). And then they could have a few seconds of actively pathfind around nearby raiders (or movable obstacles in general).

Perhaps it should also communicate to other raiders about which way they're going, so that the other raider, which might also be stuck, won't pathfind exactly the same way, at the same time.

Anyway, just a thought. Haven't got eternally stuck due to pathfinding yet, so it's just visually weird behavior I guess - nothing critical.

EDIT: I tried capturing it for a while, but I didn't get much of the weirdest behavior on camera. This was the best I got:

![image](https://i.gyazo.com/17c028e1c604021acbff50518fa03c80.gif)

**Comment by TravisGesslein** [comment]
Yeah, there's collision avoidance code in the game but it's buggy for various reasons. At some point soon-ish I will do another pass on the whole path finding and collision avoidance behavior because it's still pretty rough around the edges (for examples raiders still drunkenly bump into things on their way to the target).
