### ISSUE TITLE
After Fuulscreen muse cursor do not show actual position...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#281]
Try to explain. In full screen the actual click happen some pixels upper than show cursor. When You come back to window mode that more worse. Example on screen - cursor show empty place but game show about Boss HP Reduce. Cursor dont snapshotes so I draw position manual. Cursor draw red arrow. In circle where game think the cursor.
![bug5](https://cloud.githubusercontent.com/assets/19784493/16095849/1fca9d9a-334f-11e6-933c-0902495e9e78.jpg)

**Comment by askebv** [comment]
As a sidenote, putting the browser in full-screen-mode (F11) looks better than the Alt-Enter mode, since the game mode also stretches things.
