### ISSUE TITLE
Size of the new notification icon

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#285]
I feel like it's super small. So small that it's sometimes hard to see what it is. Is there a reason for this?

If it's because the text is so big in comparison, then I wouldn't mind if you removed the text again. Of course that would work better if everything had a unique icon first, but maybe @AlexanderOtte isn't up for this? Too busy drawing awesome new bosses, eh?

**Comment by AlexanderOtte** [comment]
This will be the first thing I will check in the morning.

**Comment by askebv** [comment]
This is an example:

![image](https://cloud.githubusercontent.com/assets/4981659/16116075/27fe215e-33cb-11e6-8a39-95c99625240d.png)

And this is with a pretty high resolution. I can't imagine how small it would be to lower resolutions.

**Comment by Talisca** [comment]
Every event got its own icon now. Increased the scaling slightly. With that they are more distinctive, so we removed the text :smiley:
