### ISSUE TITLE
Dislocated enemy health bar in Gardens of Eternity 

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#286]
I only noticed it once so far, but the female Yoda in Gardens of Eternity had their character portrait (when clicked) down below my hotkey bar in the bottom left corner. I don't yet know if it's reproducible, but the dragon's health bar and several other bosses I checked later on were fine.

**Comment by askebv** [comment]
Saw it again:

![image](https://cloud.githubusercontent.com/assets/4981659/16119490/04934346-33dc-11e6-96d7-14f43bae8a08.png)

It seems it's not even the real health bar either - so maybe it's a leftover? Because that boss didn't have 0 HP, at the time - and I neither even managed to beat it at the time of this screenshot.

**Comment by TravisGesslein** [comment]
Ah, so those might be left overs from older entities... interesting

**Comment by askebv** [comment]
Since then, I saw it on farm level 10 as well. I think it was also 0/3500

**Comment by askebv** [comment]
@Heishe Happened in Beta Patch 8 as well. This time I accidentally clicked it, and it took me to the last farm map I was at:

![image](https://cloud.githubusercontent.com/assets/4981659/16169547/3778dcc8-3533-11e6-86b6-2a4b39174edb.png)

**Comment by askebv** [comment]
@Heishe Could it be related to the Reduced Boss HP ancient wisdom?
