### ISSUE TITLE
"New patch available"

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#287]
#233 #127 #58

The "New patch available" showed up last night. Then I refreshed the page to update to beta patch 7, and this morning I found that it still said "new patch available":

![image](https://cloud.githubusercontent.com/assets/4981659/16108358/ef169a6a-33a2-11e6-8cb5-e8917a612742.png)

I only think it appears once, after updating. That's what happened between beta patch 5 and 6 anyway.

Is this intentional?

**Comment by DaemoniaV** [comment]
Me too.

**Comment by TravisGesslein** [comment]
Did you immediately refresh once it showed up, i.e. less than 30 seconds later? I.e. is it possible the game didn't save before that? Otherwise it would be very weird!

**Comment by askebv** [comment]
I refreshed shortly after seeing DaemoniaV had posted issues in a new patch (#280 #281 #282).

I probably hadn't had the game in focus since the patch was released, so it might have been in low-power mode. So maybe the notification hadn't shown up before I actually made the tab active. Could this be it?

**Comment by TravisGesslein** [comment]
Nah, the game's cold heart cares not for your machine's energy consumption! It should trigger the event immediately.

**Comment by TravisGesslein** [comment]
Does it still happen? Like, when you refresh now?

**Comment by askebv** [comment]
No, it only happens once after refreshing. I think it happened in the last patch too.

I can check again in Beta Patch 8. I'm probably going to be offline when you upload that, so just to make sure - should it show up if I load the game when a new patch has been installed? Or should it only show up on running instances of an old version?

**Comment by TravisGesslein** [comment]
It shouldn't show up if you start the game after the patch has already been uploaded. But now that you asked that we figured out what the problem might be.
