### ISSUE TITLE
Suggestion: Craft skillbooks

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#289]
In continuation of #84, I've just gotten an idea to make skillbooks something you create, instead of just buy.
E.g., beating The Crypt could drop an item that, perhaps combined with a bit of gold (balance tweaking), allowed creation of one tier of books. These books could then be crafted by combining a few simple world drop ingredients (e.g. parchment and herbs for AoE heal, parchment and rusty blade for hitstreak etc.). Later and better skills could require drops in bosses, to make them more scarce - and to make us pick between good books when we use our gathered ingredients, but have the option of creating more lower tier books, because we have more basic ingredients. etc.

This will obviously require a fair amount of work, but I think it could be really fun to do it that way. I also think it's a much more fun alternative than to just have "level 2" books drop from later raids.

**Comment by askebv** [comment]
To make it more appealing, I've spent a bit of time making up an (incomplete) example list of drops and recipes for the current version of the game:

**World drops** (W):
Parchment, Herbs, Rusty Blade, Rusty Arrowhead, Dry Blood

**Raid 1** (R1):
Permafrost, Obsidian Shard, Decayed Relic

**Raid 2** (R2):
Old Elixir, Chamomile Flower (and perhaps potions too, since they're so scarce?)

**Secret Raid 2a** (R2a):
Probably nothing. Optional/rare content should probably only give temporary boosts and cosmetic additions.

**Raid 3** (R3):
Bottled Arcane, Dragonscale

**Raid 4** (R4):

**Raid 5** (R5):

**Raid 6** (R6):

**Raid 7** (R7):

### Crafting recipes

**W**
- Hit Streak: Parchment, 2x Rusty Blade
- Mark Enemy: Parchment, Dry Blood
- Quick Shot: Parchment, 2x Rusty Arrowhead
- Rallying Cry: Parchment, Rusty Blade, Herbs
- Rejuvenation: Parchment, 2x Herbs

**W+R1**
- AoE Heal: Parchment, Herbs, Decayed Relic
- Fireball: Parchment, 2x Obsidian Shard
- Frost Shard: Parchment, 2x Permafrost
- Magic Missiles: Parchment, 2x Decayed Relic
- Multiple Shots: Parchment, Rusty Arrowhead, Obsidian Shard
- Taunt: Parchment, Ancient Sword, Dry Blood

**W+R2**
- Focused Shot: Parchment, Amulet of Concentration
- Healstreak: Parchment, Herbs, Chamomile Flower
- War Cry: Parchment, Rusty Blade, Old Elixir

**W+R1+R2**
- Arcane Frenzy: Parchment, Decayed Relic, Old Elixir
- Chill: Parchment, Permafrost, Old Elixir
- Ignite: Parchment, Obsidian Shard, Old Elixir
- Shield Block: Parchment, Worn Leather Armor, Old Elixir

**W+R3**
- Cleave: Enchanted Parchment, 3x Rusty Blade, Dragonscale
- Enchanted Parchment: 2x Parchment, Dragonscale
- Heal Propagation: Enchanted Parchment, Herbs, Bottled Arcane
- Arcane Barrage: Enchanted Parchment, 2x Bottled Arcane

**W+R1+R3**, Dragonscale
- Inner Combustion: Enchanted Parchment, 2x Obsidian Shard
- Cold Focus: Enchanted Parchment, 2x Permafrost

**W+R3+R4**
- Challenging Cry: Enchanted Parchment, 3x Dry Blood
- 

**W+R1+R3+R4**
- Calming Shot: Enchanted Parchment, Permafrost, Fury Stone

**W+R5**

**W+R3+R6**
- Frost Shard Level 2: Enchanted Parchment, Frost Shard Level 1, Frozen Spike

**W+R7**

---

I won't complete the list, since I realized that it'd take a bit too long to finish, without knowing the drop tables. Also, it might change dynamics of other aspects of the game (like Raiders upgrades), which makes it a bit harder to lay out in a decent way. I think I'll just leave this as a possible inspiration for the future.

**Comment by TravisGesslein** [comment]
Yep, some skillbooks will be craftable and the 'recipes' for them can be unlocked in various ways. Regarding the resources required, however, we're probably going to stay away from requiring many different types of them for different skillbooks. Just takes too much time creating many different resource times and balancing them (we don't have the manpower for it). We'll probably stick to a few crafting resources of different rarities, and special types of resources that have a reason to be there for specific rare or powerful skillbooks (i.e. something like the Essence of Rage for Burning Seal).

**Comment by TravisGesslein** [comment]
Leaving this open as reminder

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
