### ISSUE TITLE
Question: Soft level cap

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#29]
Is there a soft cap at 50? Seems like 50 to 51 takes more than the last 10 levels combined :)

**Comment by askebv** [comment]
When you hover the exp bar, what does it say? I'm at 44 and it says 616/930 exp

**Comment by Ethismos** [comment]
5218/50000. I m pretty sure pre 50 it was less than 1500 each level, so there is a cap. I was afk while farming 45-50 so i wasn't sure.

**Comment by TravisGesslein** [comment]
Yup, but it's extremely soft. You should reach level 51 after a few hours, depending on what you're prioritizing (higher level farm maps give more xp, but the gold you get stays static so you might prefer gold farming on lower level maps). We want leveling to stay a part of the game, but we wanted to put raider items and their skillbooks into the spotlight so to speak, so we slow the curve down significantly once you reach level 50. Raids before Gardens of Eternity are intended as a bit of a tutorial section for the game, you're supposed to reach level 50 roughly when you can beat Gardens of Eternity.

We'll add various tutorial and early game stuff for those levels 1-50 until the actual rerelease. Then from level 50 onwards 'the real game begins' for the most part. 

Those later raids are also balanced with higher raider levels in mind. I think the raid you unlock after Gardens was balanced with level 51 in mind, the highest available raid in the beta with level 54. I should add that soft-resetting resets your raider level to 1 of course. This means players have to make kind of a trade off between 'oh man I'm level 52 already so do I keep trying the current raid a bit more or reset and get more Ancient Wisdom or Raider Upgrades?". We thought it would create a neat dynamic where raider levels become really valuable without becoming boring like they were in the old version of the game.

**Comment by TravisGesslein** [comment]
Uhhh, what do I do with question issues? I guess I'll leave them open for a while and then close them arbitrarily :hankey:

**Comment by askebv** [comment]
I'm not sure I follow the logic. Does level 51+ give a lot of stats? If not, then the level seems to be a tiny factor, considering how many different kinds of upgrades you can get with gold and managing your items. But of course, if you have optimized everything to the limit, have every item and AI upgrade that you want, then those levels could perhaps be relevant again. I'll see when I get there, I guess.

**Comment by TravisGesslein** [comment]
The stats you get for a level up don't change, but being level 55 for example in concrete terms would be like giving one or two of your raiders a free fifth equipment slot. It's a small but noticeable effect on your raider performance. Depending on how many % based bonuses you have (from item set bonuses or something else) the effect may be even bigger because those only scale off of the base stats (they don't use whatever you get from items that only increase a stat a flat added value).
