### ISSUE TITLE
"New item"-icon while filtering items

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#290]
Some odd behavior happens when you loot new items while in filter mode:

![image](https://cloud.githubusercontent.com/assets/4981659/16118137/f884c6e8-33d5-11e6-9a2a-451dc2992ca6.png)

![image](https://cloud.githubusercontent.com/assets/4981659/16118437/5eb9c9bc-33d7-11e6-8a6d-365fcfe92129.png)

**Comment by Talisca** [comment]
My bad. The check is at the wrong place :<
