### ISSUE TITLE
Detecting full inventory while filtering

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#292]
It seems it didn't detect that I had a full inventory while I had filter mode enabled:

![image](https://i.gyazo.com/23cef4546d98ed329dd8e177edfe2e43.gif)

Also it behaved strangely when I dragged an archer item into a warrior filtered inventory. It should probably attempt to filter the item when you drag it into the inventory.

**Comment by Muskar** [comment]
Haha, it seems I overlooked an inventory spot in that screenshot (2nd row, 3rd spot). Maybe this is nothing then :grin:

**Comment by Talisca** [comment]
Somewhat similar to #290
