### ISSUE TITLE
Cannot read property 'getContentSize' of null

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#295]
This shows up a lot of times in the console:

game.min.js:4294 Uncaught TypeError: Cannot read property 'getContentSize' of null

**Comment by TravisGesslein** [comment]
can you expand the list by clicking the little red arrow that should be there and make a screenshot of what it shows?

**Comment by askebv** [comment]
I already checked the top one, which didn't show anything. But then I tried on the bottom one:

![image](https://cloud.githubusercontent.com/assets/4981659/16121825/115b144c-33e5-11e6-97b6-56e6139dc582.png)

**Comment by TravisGesslein** [comment]
Ah, I see. Thanks
