### ISSUE TITLE
[Minor] Suggestion: Shorten the animation of Hail of Arrows

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#297]
Right now, the attack is instant, and is thereafter followed by a 3-4 second long animation.
The sound-effect is less than a second though, which seems more fitting to the instant effect.

I'd suggest cutting down the falling arrow animation down to 1-2 seconds.

Especially because it's a bit misleading to have non-damaging arrows raining, when new monsters have already spawned.

**Comment by TravisGesslein** [comment]
Good idea.
