### ISSUE TITLE
Fix bug where pre-placed roads at the bottom of the map can be deleted.

### ISSUE THREAD

**Issue by TravisGesslein** [Heishe/idleraiders-second-run#3]
Split from #2

**Comment by askebv** [comment]
Perhaps related, you can delete the initial bonfire, but once you deleted it, it's still there visually. You can build on top of it once deleted too.

![image](https://cloud.githubusercontent.com/assets/4981659/15724697/91c91eb0-2848-11e6-8d89-6f8a3ff7c5a3.png)

**Comment by TravisGesslein** [comment]
Thanks! I'll look into it.
