### ISSUE TITLE
[Minor] Changelog errors

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#301]
> Warped Cave description now feet in window.

Is feet in the window a good thing? :grin: 

There's also one in Beta Patch 6 I didn't mention, because I thought it didn't matter, but I guess I'll include it here, since I'm on the topic:

> Switching between auto raiding and basic raiding modes will now no longer cancel and restart raids if they would be the same in both modes. Instead the raiders will just continue in the raid./li>

I.e. the broken list tag in the end.

**Comment by TravisGesslein** [comment]
The first one is an easter egg!

Will fix the second one though, thanks.
