### ISSUE TITLE
Mercenary's mana animation

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#303]
I like that you included the purple/pink healing particles to indicate that he was providing aid, and not attacking. But in the first few minutes, it did indeed appear like he was attacking my own raiders:

![image](https://i.gyazo.com/bbde3b825285084b3420a08b472a47b1.gif)

I would suggest making an animation that didn't swing his sword identically to an attack, if it isn't already on your TODO-list ![image](http://4.bp.blogspot.com/-ZgtYQpXq0Yo/UZEDl_PJLhI/AAAAAAAADnk/2pgkDG-nlGs/s1600/facebook-smiley-face-for-comments.png)

**Comment by TravisGesslein** [comment]
Actually, he's not supposed to have that ability :hankey:. Will be fixed. Mad Dog is just the basic mercenary guy, can't do much but tank some damage and increase your groups DPS a little. The other ones will have special abilities like that once they become available.

**Comment by askebv** [comment]
Haha, I guess I'll leave him unhired then. He's not very useful for the money if he can only attack, because that brings bigger strain on the healers, and all the damage raiders are much more powerful anyway.

**Comment by TravisGesslein** [comment]
Do you think he's a net negative in general or just because of the gold you have to invest in him? We could make him cheaper and buff his basic stats... he's not supposed to be more than a "ah I'm broke now, lets take him so at least the raiders have SOME mercenaries with them" option but we definitely want him to be something players want to have if they have nothing else.

**Comment by askebv** [comment]
It's hard to say. I have three saves at the moment, one of which where I'm far too poor to afford him (and the guild). And one where I'm so powerful that he doesn't make a noticeable difference. He did speed things up ~20% with the mana ability though.

The last save I have is one where I haven't done my first soft reset, but I might have enough money to try him out. I'll do that and get back to you on that.

EDIT: Actually, nevermind. Even when cheating in gold to do the soft reset, it seems that I don't have the possibility of buying the mercenaries guild yet. So it'd take a pretty long time before I could test it, unless there's an easy way to cheat in some raid progress or whatever it takes to unlock the guild.

My intuition is that if you want to keep him with the same basic functionality he has now, then he needs to be cheaper. Otherwise I don't see a use. After all, you need to tread far more carefully if you intend to keep him for very long - and if you use it as a way to push progress, then consumables are generally much better at that. Either way, priests probably won't be powerful enough to keep him alive for long enough to be relevant, unless they can already keep the other raiders alive easily - which means you're not pushing progress, just pushing the speed of clearing.
I guess he can help up to a few percent with farming gold, but his return of investment time is probably many hours, which doesn't seem very appealing.

**Comment by TravisGesslein** [comment]
Fixed in Patch 9. Also yeah we'll just make him much cheaper.
