### ISSUE TITLE
Buff stacks are darker

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#307]
Is it intentional that stacked buffs appear darker than they used to?

![image](https://cloud.githubusercontent.com/assets/4981659/16170730/405debce-355d-11e6-9712-82f000ac224c.png)

![image](https://cloud.githubusercontent.com/assets/4981659/16170742/a604957c-355d-11e6-896d-9537e0125402.png)

At least they seem darker to me. The numbers certainly are.

**Comment by TravisGesslein** [comment]
Will be brighter and also bigger in Patch 9 (no real reason to keep them that tiny),
