### ISSUE TITLE
Boss idle spazzing 

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#308]
The low FPS in this recording doesn't show it well, but every other time, bosses are having a spaz attack:

![image](https://i.gyazo.com/1aee17dc43bfe4010b9d969246dfa4ee.gif)

One of my raiders got stuck in the base, so I got a chance to watch them for a while, and it seemed to happen at least once per minute.

Probably related to #222

**Comment by TravisGesslein** [comment]
Should be fixed in patch 9
