### ISSUE TITLE
Hail of Arrows with green transparent tint

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#309]
Now I'm suddenly seeing Hail of Arrows have the green tint:

Do you think this might be related to #208?

**Comment by TravisGesslein** [comment]
Almost certainly!

**Comment by askebv** [comment]
My github is acting crazy at the moment. This is what it looks like: http://i.imgur.com/7RWHWws.png

Anyway, I was trying to upload an image about this issue, so I guess I'll do that through imgur also:

http://i.imgur.com/mf87Bvt.png

**Comment by Muskar** [comment]
My github is acting crazy at the moment. This is what it looks like: http://i.imgur.com/7RWHWws.png

Anyway, I was trying to upload an image about this issue, so I guess I'll do that through imgur also:

http://i.imgur.com/mf87Bvt.png

**Comment by Muskar** [comment]
My github is acting crazy at the moment. This is what it looks like: http://i.imgur.com/7RWHWws.png

Anyway, I was trying to upload an image about this issue, so I guess I'll do that through imgur also:

http://i.imgur.com/mf87Bvt.png

**Comment by TravisGesslein** [comment]
Will finally be fixed in upcoming patch of Kong beta
