### ISSUE TITLE
Suggestion: Give raiders a portal ability

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#310]
I've been thinking about the flaws of designing the base, and having raiders getting stuck or drastically delayed by the building placement.
Instead, it would be awesome if raiders had the ability to teleport to the entrance of the base (e.g. on the dirt patch by the river). It could even be a channeling thing, if you prefer a delay (Hearthstone from WoW pops into mind). That way, there won't be any disadvantage to making weird designs to your base, and you can still have raiders roam around freely.

**Comment by TravisGesslein** [comment]
I still like this idea a lot (especially as an upgrade), but never got around to implementing it. Still want to add this at some point!

I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
