### ISSUE TITLE
Wipe?

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#313]
Does new pacth mean wipe?
I have lost all my local and cloud saves.

**Comment by TravisGesslein** [comment]
No, it shouldn't. The new patch isn't uploaded yet (the patch notes are, though). Might be a server bug. We'll look into it.

Although, is it possible you logged into the game after playing the alpha on Kongregate?

**Comment by DaemoniaV** [comment]
Some reloading will help. New raid is hard - AWESOME!
Small question - if I have above 50 level - 90 for example))) does stats are recalculate or I need again level above 50 to gain it.

**Comment by TravisGesslein** [comment]
Yup, the stats should update automatically. When you load the game, it starts every raider at level 1 and quickly levels them up to whatever level is stored in the savegame. This makes it easy to automatically apply changes when a new patch is uploaded (if we stored the actual HP, damage, etc. values instead, we would have to convert them somehow every time we change something in the scaling).
