### ISSUE TITLE
Bug? Cannot hire second mercenary...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#315]
May be there is some cooldown?
![bug02](https://cloud.githubusercontent.com/assets/19784493/16927468/2983b4ba-4d36-11e6-8830-ce57ffdf1ef8.jpg)

**Comment by TravisGesslein** [comment]
Oh, that's quite intended... they have to be two different types of mercenaries... the merchant who visits the base should show up with one at some point for example.
