### ISSUE TITLE
Bug: Scrool of False Courage...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#318]
In description it last 30 second in icon 40.
![bug03](https://cloud.githubusercontent.com/assets/19784493/16929440/7d770c8e-4d40-11e6-9c40-42fd33bb90c8.jpg)

**Comment by Talisca** [comment]
I think your permanent upgrade "Longer buff duration" is active

**Comment by DaemoniaV** [comment]
Yes.
