### ISSUE TITLE
First reset - Gain Wisdom

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#32]
When i click the Gain Wisdom button (through the menu or temple of the ancients) i get the message: "Not enough gold!" While i have 1.2k and it asks 1000. Are there any additional requirements? If so the error message should be different and we should get some more info about what is needed for the reset.

**Comment by TravisGesslein** [comment]
Oh I think the label is just wrong. Sorry about that. It costs 2500 Gold right now! Will be fixed
