### ISSUE TITLE
Bug? *!Spoiler Warning!* Runesmith...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#320]
I farm 19 level several hours. But have no effect. Then My raiders go to the AutoRaiding mode. They fight at some Raid. I manually switch view to farm map and saw the strange bright gnome. I scroll to him and he dissapeared and leave to me the item that open new building. There is no my raiders on farm map at this moment. Does it normal?

**Comment by TravisGesslein** [comment]
You probably right clicked on him accidentally while scrolling? We're restricting npc interactions to left click next patch.

**Comment by DaemoniaV** [comment]
Probably)
