### ISSUE TITLE
Bug - Buning Seal Prophecy 

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#321]
I am already have Burned Out Seal and Burning Seal but Prophecy do not achieved.
![bug7](https://cloud.githubusercontent.com/assets/19784493/16930999/5f3c5a24-4d47-11e6-8c92-61ef245d8489.jpg)

**Comment by Talisca** [comment]
For now the prophecy will be closed if you get another Burned Out Seal. Will be fixed in the upcoming patch.
