### ISSUE TITLE
Bug Raiders Stuck....

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#324]
![stuck](https://cloud.githubusercontent.com/assets/19784493/16932190/8b3faa94-4d4d-11e6-8e93-5d9975b95d97.jpg)

**Comment by TravisGesslein** [comment]
This is because of a bug in the physics engine of the game. Should be fixed in next update.

**Comment by DaemoniaV** [comment]
Today catch again - reason a stucked simgle idiot)
![stuck2](https://cloud.githubusercontent.com/assets/19784493/17003972/33449338-4edb-11e6-983c-9b6f54a92f65.jpg)
