### ISSUE TITLE
BUG "Saves Lost"

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#325]
Whan You connect to site and  authorisation button press there is empty all saves. After reload of page You do not need  authorisation again and saves appear.

**Comment by TravisGesslein** [comment]
Are you playing on Kongregate at the same time?

**Comment by Talisca** [comment]
Reproducible behavior in firefox. Will look into it

**Comment by DaemoniaV** [comment]
Not use Kong. Use Firefox.

**Comment by Talisca** [comment]
The savegames were just not visible due to some bugs in the used framework
