### ISSUE TITLE
Weird bug but very annoying. Heishe please help!

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#330]
Do not know the reason but from today evening one of My warriors  do the rush for second boss in Mountain. So he provoke them and I have not any chance to stop this stupid berserk.
Help!
![bugg](https://cloud.githubusercontent.com/assets/19784493/16963000/ed3d70b4-4dfc-11e6-9ae5-922bddf7080a.jpg)

**Comment by TravisGesslein** [comment]
Will look into it.

**Comment by TravisGesslein** [comment]
Just to help us reproduce it, can you send a savegame where this behavior can be reproduced? We took your savegame from the cloud (we can do that now!) but we can't reproduce the behavior with that savegame.

**Comment by DaemoniaV** [comment]
It do not reproducing. I try to load save but it is do not happened again.

**Comment by TravisGesslein** [comment]
Oh, by the way: The issues is that they ignore the first boss and go straight for the second one? Or is it something else? (Like super high movement speed from first warrior).

**Comment by DaemoniaV** [comment]
Sorry there is wrong screenshot! Evening send right. Only one warrior ignore first Boss and rush to second one. I try to remove all skills but he run to him just for basic attack.

**Comment by TravisGesslein** [comment]
Mhm... did it happen by any chance after the raid timer reset happened after you only killed the first boss?

**Comment by DaemoniaV** [comment]
After time resseting it repeated again. With second Boss provoked I can not be able to kill even one of them at that point. Reloading page will help.

**Comment by TravisGesslein** [comment]
I tried a lot and can't get this to happen :hankey:

**Comment by TravisGesslein** [comment]
I'm removing this from Patch 11 milestone since I can't reproduce it. But it's bound to happen to other people as well, hopefully we can reproduce this reliably together.

**Comment by TravisGesslein** [comment]
Closing this old issue. This was probably caused by a missing range check in the disarm ability - players in the current beta observed this effect too and it was promptly fixed!
