### ISSUE TITLE
Suggestion Raider Upgrade - Delayed Rallying Cry

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#332]
Let Rallying Cry delay until All You Priest and Mages have 10 mana depleted.

**Comment by TravisGesslein** [comment]
Would be solved neatly with the custom conditions suggested in #311

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
