### ISSUE TITLE
Suggestion: Let raider does not spread off on the Base.

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#333]
![bug10](https://cloud.githubusercontent.com/assets/19784493/16969770/0140a284-4e20-11e6-9dc2-f216a13833d6.jpg)
Selected Mage stand side and do not recover mana by Red Priestes. It is very often situation.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
