### ISSUE TITLE
Drop rate.. again)))

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#334]
For My non-stop Raiding I am loot - 70 Bulwark, 312 Calming shot, 40 Great Heal and only two Fireball! Does it normal?

**Comment by TravisGesslein** [comment]
It's probably Fireball Level 2, and that is pretty rare, so yes that would be intended. Unless you are talking about another skill.

**Comment by TravisGesslein** [comment]
Also Bulwark and Calming Shot are dropped from bosses, while Fireball Level 2 is a random global glop.

**Comment by DaemoniaV** [comment]
50xFrost Shard lvl2, 30 Disarm, 28 Crippling Shot.... besides.. and I talk about simple Fireball.
![drop](https://cloud.githubusercontent.com/assets/19784493/17001178/9a3a99c8-4ece-11e6-88c4-3008df12c49e.jpg)

**Comment by TravisGesslein** [comment]
Oh, you start with those two when you first get Mages. They start with 1x Fireball each. Other than that, the level 1 Fireballs can only be bought from Scholars Tower

**Comment by DaemoniaV** [comment]
Sorry... there is no way to achieve more?

**Comment by TravisGesslein** [comment]
Actually now that you mention it it looks like I forgot to add them to Scholars tower :hankey: Will add next patch

**Comment by TravisGesslein** [comment]
Fixed! Will probably upload patch tomorrow btw
