### ISSUE TITLE
Key to the Crypt

### ISSUE THREAD

**Issue by wagenerator** [Heishe/idleraiders-second-run#337]
Anyone else having problems finding this dang key? Am I missing something? 

I have been grinding farm level 3, like it said I should in the quest description, for 2 days now and haven't found the key yet.

**Comment by DaemoniaV** [comment]
Same.

**Comment by Talisca** [comment]
Dang it. The ref to the loottable disappeared somehow.

I am sorry for the inconvenience.

**Comment by TravisGesslein** [comment]
@wagenerator We will upload a patch later today that should fix this (we have milestones for bugs here that show the planned release date, on the right side next to the labels). This probably means you couldn't even access the first raid, sorry about that. 

A way to work around it until the patch is out is to open your browser's console (F12 on most browsers)  and paste "inventorySystem.createItem(g_items.KeyToCrypt)" and press enter to let the key spawn in your inventory. We left these simple ways to basically cheat stuff in the game for the beta, for emergency work-arounds like these, but they will be disabled on release.

**Comment by wagenerator** [comment]
Its not a problem, I was just wondering if I was doing something wrong. I understand this is beta so bugs will happen. 

I will wait for the patch to release and in the meantime let my raiders grind more, lol. Thanks for the help.
