### ISSUE TITLE
Arena

### ISSUE THREAD

**Issue by wagenerator** [Heishe/idleraiders-second-run#340]
I just beat raid 3, and all my raiders are level 50. I decided to try arena and it gave me the skeleton boss, except this time he had 105000 health and proceeded to wipe out my raiders in a matter of seconds. 

I know you all previously mentioned that the arena is buggy and is not balanced yet,  but I just wanted to let you know of this particular bug.

**Comment by DaemoniaV** [comment]
My team 93 lvl, tanks health 9k+ Skeleton on Arena just oneshot them)
#329

**Comment by TravisGesslein** [comment]
Yup, this is because it still has the balancing from the old alpha, where numbers in general are much much larger than in the beta. See the other issues (#329 for example)
