### ISSUE TITLE
Bug? Rejuvenation lvl2 sell in Market not in the Tower

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#341]
![bug11](https://cloud.githubusercontent.com/assets/19784493/17048814/819e6a2e-4ff1-11e6-98c0-303c7a7aafb5.jpg)

**Comment by TravisGesslein** [comment]
Actually, it's not a bug. The market, in addition to having regular spawns for items like the potions, also has a small chance to sell loot drops from the random global loot tables. Usually this means equipment items like armor and weapons, but in some rare cases you may get skillbooks that drop globally as well.

**Comment by DaemoniaV** [comment]
Do not sure...  For My previous farming never book spawn there. But there is 3 books for 14h - Rejuv, Mag Mis, Fireball.
