### ISSUE TITLE
Suggestion Gems

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#344]
Seesm to Me the Gem system form Diablo perfect fits there. Four of five different gems that have many upgrade level from chipped to perfect. You can assembly form 3 X grade one X+1 grade. For setup use Cosmetics slot. Every gem may be placed in head, eapon or torso slot and have differemt bonus for them. Peoples fun with any (let it be tiny) progress.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
