### ISSUE TITLE
Spawned mini-Golem range..

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#347]
Often spawned by set mini-Golem do not attack.
![bugn2](https://cloud.githubusercontent.com/assets/19784493/17213481/222c2522-54dd-11e6-8c3e-33ea86eda761.jpg)

**Comment by TravisGesslein** [comment]
I made a small change just now that should improve this behavior (but it will not completely get rid of it - we need proper minion / pet AI for that).
