### ISSUE TITLE
Are somebody there?

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#348]
Does some work do about project? There is some weeks of silence(

**Comment by TravisGesslein** [comment]
Of course! We've been busy getting all the other stuff finished for the re-release, before we return to suggestions and bugs from github!

**Comment by TravisGesslein** [comment]
(It's not tooooo long until rerelease!)

**Comment by Ethismos** [comment]
Passing by every few days to see how things are going ^^

**Comment by DaemoniaV** [comment]
It is more month gone. Does You have any news?

**Comment by TravisGesslein** [comment]
Yeah, the game has been ready for about a month but we are still going through the approval process for Kongregate release which is taking longer than expected. We're getting there, though.

**Comment by DaemoniaV** [comment]
Do You  planned another update for test before re-release?

**Comment by TravisGesslein** [comment]
Nope! But we'll probably keep the beta site up because we're going to use it to test content updates before releasing them to the public.

**Comment by wagenerator** [comment]
How much more content is the released kongregate version going to have than the Beta?
