### ISSUE TITLE
hired mercenary dies in training-facility - survivability-test

### ISSUE THREAD

**Issue by PfeiferSebastian** [Heishe/idleraiders-second-run#349]
doing a survivability-test in the training-facility cause hired mercenarys to die instead of just getting thrown out or something like that - I suggest an exclusion of mercenarys in these (lethal) tests or a not-dying since they do cost a bit of gold and it should be just a training, right?

**Comment by TravisGesslein** [comment]
Yeah this definitely shouldn't happen. Will be fixed.
