### ISSUE TITLE
Suggestion: Sort buildings.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#35]
Options like: 

A) Having decoration buildings last or a way to sort them ourselves.
B) Buildings that we have maximum effect from (like 3/3 warrior tents etc) turn grey/hidden.

would help a lot !

**Comment by TravisGesslein** [comment]
Very nice ideas. We'll tackle this after patch 1.

**Comment by TravisGesslein** [comment]
Technically I made the correct statement. 8 > 1 !
