### ISSUE TITLE
Set items need reworked for re-release version of game.

### ISSUE THREAD

**Issue by aslan132** [Heishe/idleraiders-second-run#350]
![image](https://cloud.githubusercontent.com/assets/23040499/19663541/6c5e775e-9a0a-11e6-9850-187cf23010ac.png)

In the new release of the game, Idle Raiders: Second Run, items are restricted to one class, this one being a mage item. For the set, it requires items that can not be equipped by mage (Waraxe/Bowstring), so set cannot be completed. Also, full set is 6 items, raiders can only equip a max of 4, therefore again, set cannot be completed. And lastly, there is a set bonus for Warriors, which cannot equip this item (mage only), so set cannot be used by Warrior. 

This is just the first set piece I have gotten, but I am sure they are all broken this way. Set items need a complete rework for new version of game. Thanks.

**Comment by aslan132** [comment]
Ok, after getting more pieces, apparently I was mistaken about how sets work. It seems it counts all items across all raid members, and I can only assume the set bonuses are applied to all raid members as well? Is that correct?

**Comment by TravisGesslein** [comment]
Yup, unless stated otherwise bonuses apply to all raid members. The set from the raid after Burning Cave starts with a bonus that says "Priests receive +1.00 Mana regeneration per second", for example.
