### ISSUE TITLE
Witch size debuff sometimes stays active

### ISSUE THREAD

**Issue by Syntastic** [Heishe/idleraiders-second-run#352]
While I thought it was cool to have perma tiny raiders, the perma +100% damage taken was not. Refreshing the game fixed this. Unfortunately cannot reproduce at will.

**Comment by TravisGesslein** [comment]
Several code sections have been added to deal with this kind of problem since the issue was created... hoping the issue is gone for now, if not, there will probably be issues for it newer in the issue list.
