### ISSUE TITLE
Prophecies not giving rewards

### ISSUE THREAD

**Issue by Syntastic** [Heishe/idleraiders-second-run#356]
![screenshot_8](https://cloud.githubusercontent.com/assets/6775313/19709181/42804774-9aea-11e6-9c35-3eef4fad3b7f.png)

![screenshot_9](https://cloud.githubusercontent.com/assets/6775313/19709183/46688662-9aea-11e6-8df4-25c9adcc095d.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/6775313/19709134/d04df7e6-9ae9-11e6-9e84-c9522d278f39.png)

^ did not get any of these. And no, artifacts were not awarded after soft reset.

**Comment by TravisGesslein** [comment]
First two should be fixed as of last Friday, fixing Sacred Rite reward in Patch 14
