### ISSUE TITLE
Priests get stall in between two hero groups

### ISSUE THREAD

**Issue by Ardagan** [Heishe/idleraiders-second-run#358]
When in hunting grounds, if your party splits into two groups, sometimes, priests stand in middle of two groups with no reach to heal any heroes.

Observed on lvl8. Two groups on top and bot, priests get stall on left of the lake.

**Comment by TravisGesslein** [comment]
Can't reproduce this behavior for now - if somebody else sees the same thing, please feel free to give more details!

**Comment by TravisGesslein** [comment]
I remember fixing some bugs related to ability ranges, this shouldn't happen anymore.
