### ISSUE TITLE
Reach farm map lvl 10: Artifacts not awarded upon completion.

### ISSUE THREAD

**Issue by Ardagan** [Heishe/idleraiders-second-run#359]
Once 10 monsters are killed on map 9, this quests marks as closed.

However, reward for this quest: 110 artifacts is not awarded nor as active, nor as un-available artifacts.

**Comment by ChillySkye** [comment]
I had the same when I reached the 10th map

**Comment by TravisGesslein** [comment]
There was an off-by-one error in the code that made the game reward the claimable AA one level too late. So if you progress to the 11th map, you should get those artifacts. Will be fixed in upcoming patch.
