### ISSUE TITLE
Not getting claimable artifact points upon "gain wisdom"

### ISSUE THREAD

**Issue by ChillySkye** [Heishe/idleraiders-second-run#360]
I got 460 claimable artifact points, but they are not transfered upon reset.
When I noticed they didn't register I reloaded the game, still didn't register. So I claimed them again, but didn't work the second time either.

And yes, I did have enough gold, and they were spent both times (2x 4600 gold)

**Comment by ChillySkye** [comment]
Update:
Doing the raid bosses does reward additional artifact points, so it's not because it doesn't reset at all, it does partially.

**Comment by TravisGesslein** [comment]
Thank you, I'll look into it.

**Comment by TravisGesslein** [comment]
Could you send us the savegame this is happening with? social@pitforest.de

**Comment by ChillySkye** [comment]
Hi, I've mailed you the savefile.

**Comment by TravisGesslein** [comment]
Hi, thank you for the savefile. It allowed me to identify and fix the issue quite quickly. Will be fixed in upcoming patch.
