### ISSUE TITLE
Arcane Frenzy lv 2 is the same as 1

### ISSUE THREAD

**Issue by Syntastic** [Heishe/idleraiders-second-run#361]
![screenshot_14](https://cloud.githubusercontent.com/assets/6775313/19830356/cb731db2-9dbb-11e6-9b3c-e8e6b58bddc5.png)

![screenshot_13](https://cloud.githubusercontent.com/assets/6775313/19830354/c3dc8ef8-9dbb-11e6-8a07-7a5cf68b29d5.png)

The buff tooltip when triggered shows +2% casting speed for both

**Comment by TravisGesslein** [comment]
Typo in the code! While I'm at it, I should check the rest of the higher level skillbooks, too..
