### ISSUE TITLE
Obsidian Claymore has NaN stats

### ISSUE THREAD

**Issue by isNaN6** [Heishe/idleraiders-second-run#362]
Hi,

The tier 5 orange sword Obsidian Claymore has NaN stats and + 2700% damage received.

![c74c35735b0d4bc1a7fb926c3c648e10](https://cloud.githubusercontent.com/assets/23148644/19835756/8bb8e8c6-9e8f-11e6-8f06-5c266bdf8484.png)

PS: this is a game breaking bug. Just comparing the stats of this item to what is equipped on the warriors makes the health of the warriors become NaN, witch makes them immortal.

**Comment by TravisGesslein** [comment]
Sorry this happened, and good morning. I want to note that restarting the game without the item equipped will reset the stats to normal values.  I'm going through all reports and issues now and am gathering everything I can fix until this evening so I can upload a smaller patch with fixes that can be made in that short amount of time.
