### ISSUE TITLE
Inventory not organized properly on refresh

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#367]
If i save game, update to new version then refresh, my inventory becomes a mess again and i have to reorganize it.

**Comment by TravisGesslein** [comment]
Did you sort the inventory (using the button in the bottom right of the inventory window) in any way before this happened?

**Comment by TravisGesslein** [comment]
Also, when you say it becomes a mess again, does it seem like the ordering of the items is just random, or are they by any chance sorted in a certain order? Like with the other issues, a savegame where you can get this to happen so we can reproduce it would be extremely helpful.

**Comment by dcish** [comment]
Yeah I had created space so I can identify groups of items over pages. When I come back all those spaces are removed.

**Comment by dcish** [comment]
Tried again after other people supposedly stopped having these problems at patch 14, i still have them. I have 5 open slots, if i move those items to last slots available and refresh, the first 5 slots get filled and only empty ones at the back again.

**Comment by TravisGesslein** [comment]
This should hopefully be fixed in next patch! Don't hesitate to reopen this issue if you see it again, though.
