### ISSUE TITLE
Old Holy Warrior

### ISSUE THREAD

**Issue by isNaN6** [Heishe/idleraiders-second-run#373]
Hi,
I just cleared the Temple of the Pharaons and didn't received the Mercenary Contract.

![screenshot_5](https://cloud.githubusercontent.com/assets/23148644/19913662/fc18fc20-a0a4-11e6-9efd-2c4d78908891.png)

For info, I didn't upgrade the 2 others mercenaries yet, don't know if that plays a role in it.

**Comment by TravisGesslein** [comment]
Sorry, don't know how that prophecy reward slipped in, the contract isn't supposed to be rewarded here. The Holy Warrior mercenary is a reward for an entirely different prophecy (it's secret, but if you don't know what to do, these secret prophecies can drop as random world drops, and some are also sold by the visiting merchant from time to time).
