### ISSUE TITLE
Tomb of Pharoa second boss shoots beam below the character 

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#375]
Sometimes when he does his beam attack its visually below the character on the screen. I've only noticed it when the boss is facing to the right.

**Comment by isNaN6** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/23148644/19987395/350d6666-a21b-11e6-9f05-84c16229ecd1.png)

I believe it's this you are talking about.

**Comment by TravisGesslein** [comment]
Not sure if this happens anymore, but this issue is old and I can't reproduce it at the moment, so closing it for now.
