### ISSUE TITLE
Extract materials quest reward missing

### ISSUE THREAD

**Issue by BrackCarmony** [Heishe/idleraiders-second-run#377]
After completing the Extract Materials quest, I didn't get the quest reward of the skillbook of sacred rite recipe.

**Comment by TravisGesslein** [comment]
Thank you for the bug report. This will be fixed on Kongregate when Patch 14 is uploaded (sometime tomorrow). It includes a retro-active fix for players who previously already completed the prophecy. Once Patch 14 is live, you should see Sacred Rite just appear in the runesmith's inventory. 

See #356
