### ISSUE TITLE
Farm area 24

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#38]
The caster mummies (whatever they are called) don't fight back.

**Comment by askebv** [comment]
I had the same thing happening with the priests at 19. Are those mummies priests as well, or do they just do nothing?

**Comment by Ethismos** [comment]
I can kill the other mummies around them with 5 of those casters around without an issue, so i don't think they are healers.

**Comment by TravisGesslein** [comment]
Yup, some priest monsters lacked energyPoints so the healing abiltiy couldn't execute.
