### ISSUE TITLE
Pathing issue when entering a new map

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#383]
On map 198 (and similar maps) units will attempt to go to the closest unit as measured by screen distance, not pathing. Sometimes this will lead to an issue where the units will walk around a bunch of monsters to the target farthest away from them while letting other monsters take free hits at them.

Here's a representation!
      m m
m  xx  
m  xx
t    xx   e

E is the entrance where the units enter, x is blocked terrain, m represents a non targeted monster and t is the target they acquire first. They would have to pass by 4 monsters at least to get there.

**Comment by TravisGesslein** [comment]
I made some adjustments to a lot of the maps so while the issue remains in the code, the layout of the maps should now be such that it's not an issue in practice anymore.
