### ISSUE TITLE
Can`t login to beta

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#385]
Always login with button Googlewith goole account. Now meet error messge - "error":"unauthorized_client","error_description":"Unauthorized","status":400
p.s. Try three different browsers - Mozilla, IE, Opera.

**Comment by TravisGesslein** [comment]
Thanks, I'll report this to the server guys. Keep in mind though that nothing has changed in that beta, the current one is running on Kongregate+ until release!

**Comment by TravisGesslein** [comment]
We would give you access to it, but we don't know how. As far as I can tell, we can't grant explicit invites to people.

**Comment by DaemoniaV** [comment]
http://www.kongregate.com/accounts/Daemnoia
My Kong user profile if it help)

**Comment by DaemoniaV** [comment]
How long Kong+ test long? Is there some that I can do for gain access?

**Comment by TravisGesslein** [comment]
We're not sure we're going to make it before the end of the year. There's just a lot of bug fixing and stuff left to do! The game has been content complete (for release) for a long time now, but we just want to polish more.

As far as I'm aware, any Kong+ member can enter the beta (i.e. you would have to subscribe for money), other than that I'm not aware of any way to enter, sorry :hankey:

**Comment by DaemoniaV** [comment]
Understand. Have some chance to login in old beta on https://beta.pitforest.de/idleRaiders/
Just one time to export save.

**Comment by TravisGesslein** [comment]
Sorry, I didn't even see that last comment. Exporting save will be unnecessary, there will be a reset when the game is released.
