### ISSUE TITLE
Mage critical on fireball

### ISSUE THREAD

**Issue by Plop86** [Heishe/idleraiders-second-run#394]
SO i had exactly 100% crit chance on my mage with fireball so i went to dummy target practice to try if it would constantly cast fireball. My mage doesn't always crit so my guess would be that ignite doesn't properly stacks. My mage had 84% crit chance with x2 ignite which should mean 100% yet he happen to fail to do critical and put fireball on cd.
Is there a max amount of fireball you can cast in a row ? or does ignite not stack ?
I can't test that with 1 ignite as i can't reach 100% without.

**Comment by TravisGesslein** [comment]
This was a bug in the work-around code that was added with the fix of issue #376 (also related #387). Will be fixed in upcoming update.

**Comment by TravisGesslein** [comment]
(Also thanks to Thorbrian, who made the fix of this issue pretty easy thanks to a detailed error report via email. He should be around somewhere here as well I think)
