### ISSUE TITLE
Critical hits

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#395]
With a critical hit damage bonus of 100%, my critical hits are doing exactly base damage. Where is the 'bonus' part from critical damage?

**Comment by TravisGesslein** [comment]
I can't check the code right now, but this is probably just a display error. With 100% crit bonus, you basically do double damage when your initial attack crits. It's possible we're only showing the bonus amount that comes from the critical hit when we show the little floating text.

**Comment by Profputricide** [comment]
tested it on low lvl, getting critical hit numbers of 21 (base dmg), not oneshotting the skeletons in farm map 3 with that

**Comment by TravisGesslein** [comment]
Yup, it only showed the bonus damage resulting from crits. Will be fixed in next update.
