### ISSUE TITLE
Skill book: Cold Focus Level 3

### ISSUE THREAD

**Issue by Igotz** [Heishe/idleraiders-second-run#401]
The text says a 9% increase in damage per stack but the buff that its giving says 3% when i mouse over it. The cold focus buff seems to be stacking properly though, as in I can get 7 stacks with the level 3 skillbook, but the damage is still going up at 3% a stack. I will attempt to actually calculate the if the buff is factoring in at 9 or 3% but I cant make any promises there ( math is not my strong suite ).

**Comment by Igotz** [comment]
![screen shot 2016-11-22 at 9 55 12 pm](https://cloud.githubusercontent.com/assets/23691537/20550761/9dcd1e02-b0fe-11e6-8956-833e965e3ce1.png)

**Comment by Igotz** [comment]
hopefully the screenshot helps.

**Comment by Profputricide** [comment]
If i remember correctly, the same issue has been mentioned about cold focus lvl2

**Comment by ImperialUser** [comment]
skill book descriptions that mention what they do also don't update between v1/v2/v3.  A few examples: Rejuvenation, Arcane Bombardment, Fireball.

**Comment by TravisGesslein** [comment]
Yup, a code error caused the skills to always take the level 1 value for damage specifically (the other stats, like max stacks, were unaffected, so they ended up working correctly). 

The thing with the descriptions is a left over from a time when we didn't auto-generate descriptions for all the attributes that skillbooks have in common (stuff like proc chance, the damage modifier of a skill, etc.). If you could look at the code, you'd see that it's literally just a piece of text (mostly) that says what the description now says. I changed all of those to take on the new format, where the description only generally states what the skill does, and the auto generated descriptions show the concrete values (won't affect the live version until I upload the patch of course).
