### ISSUE TITLE
suggestion: gold/AA

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#407]
There is currently no way to see exactly how much gold/AA we have with high numbers. Maybe show exact numbers on mouseover?

**Comment by Profputricide** [comment]
starting to have the same issue with crafting materials ...

**Comment by TravisGesslein** [comment]
With the next patch we will show the exact numbers in the tooltip on mouseover. Same for items of which you have more than 999 (so the UI shows a *).
