### ISSUE TITLE
Suggestion: snapshot item indicator

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#410]
Would be nice to have a way of seeing what items are used in the snapshots while extracting items. 
Finding out that you extracted items that are used in snapshots is really annoying to deal with :p

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
