### ISSUE TITLE
Suggestion for items we would like to see in game

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#415]
![](http://puu.sh/sUzCG/5f27391ed2.png)

If anyone has something to add to this, feel free to do so!

**Comment by Plop86** [comment]
Overall more diversity. And maybe items to make priest attack. Maybe items that increase skills stats or maybe even have some new skills.
But yeah warrior suffer damage quite badly compared to other class (when you want to make it pure dps of course)

**Comment by ImperialUser** [comment]
As previously mentioned, archers lack any +attack speed equips late game.  Best one is a tier 3 set item, Ice Kiss, followed by an uncommon tier 5, stonefoot boots.

Priests casting a party-wide buff of some kind would be nice. Even if it was something heally like -damage taken or +healing received.  But it also opens up other possibilities like +speed, +damage, +crits, +gold, etc.

Mages could use some kind of spell books for when you have 100% chance with fire balls.  It's 2 spell slots left open. Maybe some kind of passive skill like warriors and archers have.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
