### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#417]
Had hired 3 mercenaries, went to a high map to get them killed but 1 of them didn't die properly. Now all my raiders are stuck in base not moving and i can't do anything to get out of it. (except for reloading the game offcourse)
![error](https://cloud.githubusercontent.com/assets/23452501/21341831/db50b45a-c68e-11e6-9f3f-08bf07f7a0b9.png)

**Comment by TravisGesslein** [comment]
This should've prompted an error log export, did it?

**Comment by Profputricide** [comment]
uh ... no it didn't

**Comment by TravisGesslein** [comment]
That's weird... any chance you're still running on the old version? The browser will sometimes load a locally cached version. Easy way to check would be to go to the savegame section of the options, there should be a new button for exporting your gamelog (which, by the way, can also be used if you see any kind of weird stuff happening. Not just errors but also weird raider behavior, etc.).

**Comment by Profputricide** [comment]
Not seeing that button, only the export for savegame ... guess i should clear cache or something?

**Comment by TravisGesslein** [comment]
No, clearing the cache doesn't do anything as far as I know. But the developer console has an option to disable caching while it's open. When you open the console there are 3 dots on the top right, there you can go to settings, and in the preferences tab there's a network section where youc an tick 'disable cache'. This should force it to update.

**Comment by Profputricide** [comment]
Clearing cache fixed it, i am now seeing the new button

**Comment by Profputricide** [comment]
"Not just errors but also weird raider behavior, etc."
Does this also include dmg numbers/arrows/fireballs getting stuck on farm maps? 
like this
![](http://puu.sh/sVua3/1cf2264687.png)
It looks like whatever is on the screen at the time of changing map zones is left there forever. 
Did some testing, and got it to look like this in just a few minutes:
![](http://puu.sh/sVujR/716a1f101c.png)

ps. This stil happens after reloading the game

**Comment by Plop86** [comment]
I also happen to see loot leftover on the map aswell and i have to click them manually on the map lol. This only happens when being active on the map (seems fine when in town)

**Comment by Profputricide** [comment]
I'm having leftover loot aswell, but only while running on map progression, haven't had it happen when on basic farming (while looking at farm map)

**Comment by TravisGesslein** [comment]
These issues will be fixed with next patch!
