### ISSUE TITLE
Sanctuary of the forgotten

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#420]
This raid has dissapeared from my raid selection list after reloading my save, can still run it by using auto raiding somehow. 
![](http://puu.sh/sVVi2/7ff8e1b0aa.png)

**Comment by Profputricide** [comment]
Looks like the cane also drops again when the raid is not showing in the list.
And it also dissapeared from the selection window again after gaining wisdom. 
Can still run it on auto raid though.

Have also had loot drop only once so far, while running it at least 5 times already.

**Comment by Plop86** [comment]
The loot from this raid is an artifact salvage it and it will drop everytime it is not in inventory. cheap way to get material from artifact.

**Comment by TravisGesslein** [comment]
A bit late since this report came during the holidays, but does anyone have a save where this still happens?

**Comment by Profputricide** [comment]
This seems to be happening to everyone, so getting a save with this happening should be easy.

I myself have to find the cane again first, can send it once i found it if you like (if still needed by then)

**Comment by ImperialUser** [comment]
The raid is lost from the list any time the game is refreshed, but is still run on auto-raiding.

**Comment by TravisGesslein** [comment]
Yup, will be fixed next patch.
