### ISSUE TITLE
rage/mana/energy

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#421]
The bars that indicate how much rage/mana/energy a raider has does not update depending on the raiders available resources, but seems to be linked to the hp bar right now. 
![](http://puu.sh/sWlT9/8798a56a3b.png)
Archers/priests not having full resource while the resource bar says it is maxed.
Wizard and warrior showing resource bar at the exact same spot as hp, while the number says it's maxed.

**Comment by roflaa** [comment]
can confirm this

**Comment by TravisGesslein** [comment]
Fixed in next patch!
