### ISSUE TITLE
old holy warrior prophecy

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#422]
Failed to finish the prophecy while running with this setup almost 10 times already. 
![](http://puu.sh/sWNHw/056172bd5a.png)
Don't want to spoil too much, but am i missing something in how the prophecy works or is this bugged?

**Comment by Plop86** [comment]
I can confirm this. I pretty much did the same setup removing everything from everyone but warrior. their mighty blow were hitting for 60k yet when the boss died nothing happened. 
I also made sure to last hit everyboss there just to be sure and nothing happened aswell

**Comment by TravisGesslein** [comment]
The prophecy will be changed a bit in next patch. Will now just require a certain amount of kills while that particular mercenary is active.

edit: Actually, I misread which of the two this one was referring to. I'll what's wrong with this one.

**Comment by TravisGesslein** [comment]
Looks like an item ID changed a while back, but the prophecy code didn't get updated to reflect that. Fixed next patch.
