### ISSUE TITLE
Find schematic for strange device prophecy

### ISSUE THREAD

**Issue by Plop86** [Heishe/idleraiders-second-run#424]
It asks to kill the werewolf in 10 seconds  for the castle of undying. I'm not sure how this is possible, even with full movement speed and one shotting all the bosses the time to reach werewolf alone takes more than that.

**Comment by Profputricide** [comment]
Been wondering this too, thought it would mean just the bosskill, but that doesn't credit it.

But theres more prophecies currently that we don't seem to be able to complete, so not sure what's going on.

**Comment by TravisGesslein** [comment]
Will be adjusted to 60 seconds. When we initially created this prophecy, there were still (stacking) speed scrolls in the game, and we forgot about adjusting it when we removed those.
