### ISSUE TITLE
increased item drop chance

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#427]
Starting to feel like this ancient wisdom needs a cap or reduction in value. Getting more than 10 artifacts a day and a few thousand items doesn't feel very rewarding.

**Comment by TravisGesslein** [comment]
True, also makes it insanely hard to balance crafting costs, and creates more inventory management overhead for the player per day. What level of the upgrade are you at currently?

**Comment by ImperialUser** [comment]
Im at lvl 10, getting about an artifact a day.

(added)
That's with 24 hour gameplay, but not fighting something I can 1-shot kill. So I could boost those drops further.

**Comment by Profputricide** [comment]
I'm currently at lvl 60, might have exaggerated a little bit in the amount of drops, but that's just how it feels right now. 
Farming on 34/98/etc. depending on killspeed.
Found 72 artifacts in 1 week, and too many other items to count.

**Comment by ImperialUser** [comment]
Lvl 60 item drop rate is a huge investment to item drops, you get what you pay for. :p  I think an artifact a day per 10 levels is a good drop rate, so maybe reduce the effect by half? (25% per level instead of 50% per level)

**Comment by Profputricide** [comment]
That sounds ok i guess, but would need to gather some data on how many artifacts people actually get right now then. As there's still some RNG involved in droprates.

**Comment by Plop86** [comment]
It needs to be balanced indeed i currently have 400 artifact t8 lol in a matter of a week of farming. the thing is they are ok at lower upgrade but get ridiculously crazy. You should just fix the price of the upgrade to be significantly higher then or lower the chance. I could still get full artifact i needed even before it got fixed. it was super slow but rewarding to find it. now it take me 1h to fill a full raider set of artifact.

**Comment by ImperialUser** [comment]
What about a cap of 1 artifact every 24 hours then?

I'd suggest a daily boolean, after an artifact drops a_drop=true;
When an artifact drops, if (a_drop) don't give it to the player
At the end of the day a_drop = false;

Shouldn't count unique drops, quest rewards etc, just mob drops of artifacts for both the check and triggering a_drop = true.

**Comment by Plop86** [comment]
Just tune it down and actually put a max upgrade to drop chance so we don't end up with +10000% chance.

**Comment by TravisGesslein** [comment]
Upgrade will be capped in next patch!
