### ISSUE TITLE
Bosses not dropping loot

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#428]
Just ran tomb of the pharao and lair of the seer.
Second boss in tomb and seer both dropped nothing for me (unless it tried to drop a unique set item i aleady own and not give out something else)

**Comment by TravisGesslein** [comment]
Could you submit a log (via email, or upload it somewhere) when you see this happening? Those bosses definitely have several non-unique items in their loot table. Not dropping would be indicative of errors happening.
