### ISSUE TITLE
dropped prophecies

### ISSUE THREAD

**Issue by hyro77** [Heishe/idleraiders-second-run#430]
see also http://www.kongregate.com/forums/615157-idle-raiders-second-run/topics/694873-dropped-prophecies

Issue with "Find the Dawn Fortress"
Found it already, used the map, raiding it, but i guess before the prophecy showed up, so already used the map, would need another one to complete the Prophecy

**Comment by TravisGesslein** [comment]
I think there are a bunch of prophecies like this. They're supposed to be completeable even if you haven't found them (i.e. they are hidden). Will fix.

**Comment by TravisGesslein** [comment]
I made a pass over all existing prophecies, should be fixed now (in next patch, that is)!
