### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#431]
Where did my level go?
![](http://puu.sh/tmphj/9368f9cbf9.png)
Just got to 1000, guessing it no longer fits or something?

**Comment by TravisGesslein** [comment]
Yup, we just didn't account for the fact that players would reach it this quickly. It's invisible but it's basically pushed to the 'next line' of that piece of text. Will be fixed.

**Comment by TravisGesslein** [comment]
Fixed in next patch!
