### ISSUE TITLE
auto-saving crashes

### ISSUE THREAD

**Issue by ImperialUser** [Heishe/idleraiders-second-run#433]
Had to refresh game, couldn't connect to game servers.  Auto-saving causes the game to freeze, unless you have the save game options window open.  Then you can uncheck the auto-save game option and it will continue as normal

**Comment by ImperialUser** [comment]
Can't save the game at all right now.  Tried saving and refreshing, 10 minutes of progress lost.

**Comment by TravisGesslein** [comment]
This is possibly related to some server side issues we've been experiencing the past few days. Does it work again now?

**Comment by ImperialUser** [comment]
Connected, Working again.
