### ISSUE TITLE
Cloud Save not showing up

### ISSUE THREAD

**Issue by Sevenday77** [Heishe/idleraiders-second-run#435]
Online saves not showing up since yesterday, are there any problems with the server ? Seems like it's not showing for others too.

**Comment by TravisGesslein** [comment]
Yes, it looks like a lot of people are having problems reaching our API servers. We're investigating the issue.

**Comment by TravisGesslein** [comment]
Should be working again. I'll leave this open until tomorrow in case something goes wrong.
