### ISSUE TITLE
What does colors of item counters mean?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#44]
I've seen brown, green, yellow and white numbers so far. Here's all but green:

![image](https://cloud.githubusercontent.com/assets/4981659/15746364/8c099002-28d6-11e6-8053-9fbff76fc603.png)

I haven't tested it, but I think it vanishes when I refresh the page, so I'm guessing it's a bug.

**Comment by TravisGesslein** [comment]
Yeah that's a bug. @Talisca  Might be related to #17

**Comment by askebv** [comment]
Additionally found that "new item" icons can be affected too. They both get a border and a color:

![image](https://cloud.githubusercontent.com/assets/4981659/15791864/1295b980-29da-11e6-9661-f0cae6caa777.png)
