### ISSUE TITLE
Save file disapeared/can't access it

### ISSUE THREAD

**Issue by ImperialUser** [Heishe/idleraiders-second-run#440]
Had to refresh game, when it comes to loading screen the leaf icon doesn't go away and it doesn't show my save file.

*added*
it's working now

**Comment by TravisGesslein** [comment]
We will pull the servers down next week to switch the beta to the new server architecture which should hopefully get rid of these performance problems. Until then, unfortunately we can't do much to prevent these irregular timeouts. Sorry this happened.
