### ISSUE TITLE
Extracting

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#445]
The game gets stuck for a while when extracting lots of items, took a few minutes to extract 150k items in 1 go. Any chance on improving extracting performance maybe? (or is this just an issue for me only?)

**Comment by ImperialUser** [comment]
Agreed, it's like it does each item individually.  Even more then 2k is enough to cause the game to freeze while the extractor does it's thing.

**Comment by TravisGesslein** [comment]
That's  indeed the way it currently works! I'll take a look at it.

**Comment by TravisGesslein** [comment]
Yup, will be improved.
