### ISSUE TITLE
Extractor Issue

### ISSUE THREAD

**Issue by ImperialUser** [Heishe/idleraiders-second-run#449]
The new extractor wont extract common rarity items.

Examples: 
Ancient Sword
Worn Leather Armor
SkillBook: Shield Block Lvl 2

**Comment by TravisGesslein** [comment]
Thanks, I will look into it.

**Comment by TravisGesslein** [comment]
Fixed internally. We'll try to apply a small hotfix patch later today, should be fixed then.
