### ISSUE TITLE
Reseting and gold

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#45]
Reseting sets gold to 0, something that is not at the description ...

Ouch...

**Comment by TravisGesslein** [comment]
Sorry, that should not happen. As a quick fix you could cheat it back: Open dev console (F12 on most browsers), type "gameSystem.setGold(whatever your gold amount was)". We'll have various forms of cheat protection in the final rerelease but in the closed beta its fine.

**Comment by TravisGesslein** [comment]
I fixed this internally already, we will upload a patch relatively soon now. I'll leave this issue open until then in case someone else runs into it.
