### ISSUE TITLE
Minor suggestion: The "View Base" button in Building mode is really a back button

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#454]
It has the same icon as the "View Base" but in reality it's really a back button:

[Short clip of what I mean](https://i.gyazo.com/60be55310684a55d3e3f82a6d33c1f28.mp4)

This is the intuitive, expected and desired behavior to me, but the icon might need to either reflect whatever we go back to, or be a an arrow back:

![baseback](https://cloud.githubusercontent.com/assets/4981659/23477301/d99c279a-febd-11e6-8905-69a2e5617a6c.png)

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
