### ISSUE TITLE
Bug: Prophecy reward amount is incorrect

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#457]
![incorrectrewardamount](https://cloud.githubusercontent.com/assets/4981659/23478085/6dc0391e-fec0-11e6-9ffb-37da2acbbc09.png)

Either I misunderstood, or the amount is incorrect. It says I would get 110 ancient artifacts from fulfilling the prophecy, but it only says I'll get 90 when I soft reset.

**Comment by TravisGesslein** [comment]
See #534
