### ISSUE TITLE
Reseting and auto raiding.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#46]
When you reset the game there is the option to auto raid while there are no raids open until level 10, doing that just makes your raiders sit at base. 

In the mean time auto farming (that would actually be useful because of the new gear you have) is not enabled until farm area 8.

In my opinion it should be the opposite. Reset, auto farm enabled from start, then auto raid enabled at 10.

**Comment by askebv** [comment]
I agree, but I'd say auto farm enabled from start (of a reset) and auto raid enabled after clearing the crypt. It won't do anything before you clear the crypt anyway.

**Comment by TravisGesslein** [comment]
Yes I think the relevant code just lacks some checks for whether or not the player is above SR level 0. I will implement the suggested behavior.

**Comment by askebv** [comment]
Additionally I don't understand why auto-raiding remember which raids you cleared in your previous resets. Surely you'll always start out weaker than your initial reset, right?
