### ISSUE TITLE
Town Hall Skill Priority window won't close

### ISSUE THREAD

**Issue by drekalicious** [Heishe/idleraiders-second-run#466]
Can't close the window. It disappears when you enter build mode, but is back when you exit.

**Comment by TravisGesslein** [comment]
The X doesn't work? That's strange. Could you get your savegame to us (for example via email to social@pitforest.de)?

**Comment by drekalicious** [comment]
I haven't had the issue since refreshing the page. Do you still want it?
First time there were no tooltips for the question mark, and I wasn't able
to change the order of the abilities. After refreshing, no issues.

**Comment by TravisGesslein** [comment]
No, it's fine if it works for now. I'll close this issue until someone else has the same problem.
