### ISSUE TITLE
trader bug ?

### ISSUE THREAD

**Issue by shwooshy** [Heishe/idleraiders-second-run#467]
After beating the Chamber of the sealer raid, for some reason all the items the trader had disappeared and its blank every time he comes back as well.

![image](https://cloud.githubusercontent.com/assets/26174489/23570660/3d31c2f8-0033-11e7-912c-eea30d4949bb.png)

**Comment by TravisGesslein** [comment]
Hi,
is it possible that you just exhausted his supply for now? Though admittedly it makes no sense for the trader to still come to town without any items :)

**Comment by UnSquish** [comment]
Having the same issue though I can't confirm when it started. The trader no longer stocks goods even after reset. I believe this was an issue with my save file well before I beat the chamber of the sealer raid. It started on reload after the crash screen recommending restarting the game came up.

**Comment by vthrenee** [comment]
Same isue here, merchant with 0 items always.

**Comment by TravisGesslein** [comment]
Will be fixed in 1.0d :)
