### ISSUE TITLE
Visual bug: White overlay stays after clicking farm enemies

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#469]
![image](https://cloud.githubusercontent.com/assets/4981659/23578960/bc8fb866-00e2-11e7-9c54-f21b9b3c4346.png)

**Comment by Gazyn** [comment]
This was fixed in 1.0d but now it affects every enemy except the nobles
![ss 2017-03-04 at 04 46 40](https://cloud.githubusercontent.com/assets/26186257/23579692/7e4239be-0103-11e7-9ec5-9a469f42247a.png)

**Comment by TravisGesslein** [comment]
This should be fixed as of 1.0e
