### ISSUE TITLE
What's the point in summoning merchant?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#47]
My Market just made the consumable "Summon Merchant" available:

![image](https://cloud.githubusercontent.com/assets/4981659/15748880/b5c351bc-28e0-11e6-8ed3-a264251321ae.png)

If it's just the standard merchant, then what's the point? He's been empty since I bought all the plans a long time ago. And spending 100 gold on summoning a merchant, that summons itself over time, doesn't seem very useful, since gold is by far the most scarce thing at that point:

![image](https://cloud.githubusercontent.com/assets/4981659/15748970/097d9cea-28e1-11e6-9514-b0857f764848.png)

**Comment by TravisGesslein** [comment]
I admit its kind of useless right now. The merchant is just a dumpster for various building plans right now, but he'll trade a ton more stuff soon enough.

**Comment by TravisGesslein** [comment]
We may just prevent the scroll from spawning if you truly exhaust all of his offers.
