### ISSUE TITLE
Inventory item backgrounds not staying darkened

### ISSUE THREAD

**Issue by GregTheTraceur** [Heishe/idleraiders-second-run#470]
If I select a single raider type I want to see the potential equipment for, all of the items it cannot equip get darkened. If I move an item, any uncommon or better items which were grayed out get their background color back.
![bug](https://cloud.githubusercontent.com/assets/14863102/23580050/171e4916-00c8-11e7-875e-e3cf4f02ace3.png)

**Comment by TravisGesslein** [comment]
Thanks, will look into this.

**Comment by TravisGesslein** [comment]
Fixed in next patch :)
