### ISSUE TITLE
Bug: Wall missing or collusion left in farm level 6

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#471]
I see you removed the southern wall of level 6 - but raiders and enemies still act as if it's there:

![clip](https://i.gyazo.com/e69f95b41b0ce000db454d0eaba5082c.gif)

**Comment by TravisGesslein** [comment]
Oh thanks for that, did indeed forget to update the collision map.

**Comment by TravisGesslein** [comment]
Fixed next patch.
