### ISSUE TITLE
Suggestion: Hotkeys for toggling common windows

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#473]
Hotkeys for toggling the windows we most commonly open and close often would be nice. Here's my suggestions on the keys:

- L/l : **L**oot chests
- E/e : **E**quipment and statistics
- I/i : **I**nventory
- U/u Raider **U**pgrades and Ancient Wisdom

Some could be nice to have's as well:

- M/m : **M**arket (if owned)
- T/t : Scholar's **T**ower (if owned)
- G/g : Mercenary' **G**uild (if owned)
- Q/q : Prophecies (**q**uests)
- V/v : Traveling merchant / **v**isitor (if present)

Probably also the **r**unesmith/enchanting building, but I haven't gotten to that on this yet. I think the rule of thumb is that there should be one for any window you often either check for updates or manage things in.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
