### ISSUE TITLE
Question: Burned out seal

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#481]
I don't see essences of rage drop. Is there a new way to "activate" this sword that we need to discover? Or is there a bug?

**Comment by askebv** [comment]
After auto-raiding for 8 hours I got one essence of rage, so it seems drop rates are just lowered.

**Comment by TravisGesslein** [comment]
Yup, that's a bit too low for our taste. Will buff next patch.

**Comment by askebv** [comment]
@Heishe Don't buff it too much though. Since it's only 3 you need now, it should still take a few hours to get the 3, I think. There's no need to rush a uniquely upgradable, is there?
