### ISSUE TITLE
Trader Issue Part 2

### ISSUE THREAD

**Issue by UnSquish** [Heishe/idleraiders-second-run#489]
The game crashed a couple days ago and the trader stopped carrying items afterwards. The 1.0D patch attempted to fix this and succeeded to a point. Now the trader carries only healing potions and another item type has not shown up since before the 1.0D patch. Can I assume that my save file is broken or is there a way to fix this?

**Comment by askebv** [comment]
I had only health potions for a almost 10 hours straight as well. Could just be bad luck.

**Comment by UnSquish** [comment]
Thanks Muskar I think you were right. I'm not sure what exactly "fixed" my bad luck but after loading my game on a different computer and buying the 70 health potions to empty the trader he was carrying some crafting materials on his next time through.

**Comment by TravisGesslein** [comment]
Hi, this wasn't bad luck or anything, it's just that the merchant has a limited stock for some items (in often cases just 1), and some of it is locked off until you've unlocked the relevant in game features (for example, mercenary contracts don't appear until you build a mercenary guild, crafting mats don't appear until you unlock the crafting system, etc.). Health potions are actually a kind of pity item that is spawned in case you have already bought everything he has to offer for the moment.
