### ISSUE TITLE
Equipping two Witch's Twigs leaves a green background in the empty spot

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#49]
Here's the step to produce the issue:

Start with at least 2 Witch Twigs to equip:
![image](https://cloud.githubusercontent.com/assets/4981659/15749605/44ad804e-28e3-11e6-8219-65b39a132965.png)
Drag the first Witch Twig into one of the slots with a cloak:
![image](https://cloud.githubusercontent.com/assets/4981659/15749636/5f9fe3e2-28e3-11e6-8290-fb3087dda32a.png)
Drag the second Witch Twig into one of the other slots with a cloak:
![image](https://cloud.githubusercontent.com/assets/4981659/15749707/a2ea5862-28e3-11e6-97c3-30989d2900c5.png)

As you can see, it has left behind a green background. And in the first image, I later noticed there's a darker brown background left from the cloak as well. It doesn't seem to happen if I only have one Witch's Twig to begin with.

I'm guessing it also happens with all other items.

Note, the background clears back to normal when you move items on top of the glitched background.

**Comment by TravisGesslein** [comment]
Thanks for the detailed description, I'll try to squeeze this into beta patch 1.

**Comment by Ethismos** [comment]
The same thing happens if you remove a skill and then try to use Town Hall for skill priority list! For example, i had flash heal, rejuvenation and ofc the passive Basic Heal. When i removed the flash heal EVERY priest was left with a green background at skill priority list!

**Comment by TravisGesslein** [comment]
Yup, both issues should be fixed next patch.
