### ISSUE TITLE
Mercenary Upgrade: Experienced Bandit criteria too difficult

### ISSUE THREAD

**Issue by midgetmafia** [Heishe/idleraiders-second-run#492]
At level 50, Mad Dog does 14 damage per swing which is about 1% of the health of the target he needs to kill.  Factor in that these enemies regen more than this amount of health every tick with about 4 or 5 ticks occurring between his swings and it takes an astronomically unlikely set of circumstances for him to get a kill, and he needs 10 of them.  Some combination of buffing Mad Dog's damage output, nerfing health regen rates of enemies, or changing the quest criteria is needed for this quest to upgrade him to be doable.

**Comment by GregTheTraceur** [comment]
It's doable. No one said it's supposed to be easy. I think I got it in well under an hour, though.

**Comment by osiato** [comment]
Do lv12 and just wait a while. It took me about 30 minutes.

**Comment by TravisGesslein** [comment]
Buffed both the base Bandit and her upgraded version. Should make it easier + more rewarding when you finally get it :)
