### ISSUE TITLE
Saving Throw Spellbook

### ISSUE THREAD

**Issue by wagenerator** [Heishe/idleraiders-second-run#493]
I remember this spellbook from the original idle raiders, and it still says that the warriors will taunt enemies who are "attacking priests and archers". With the new addition of mages, you should probably add mages alongside the priests and archers in the description, to avoid confusing newcomers about when the warriors will use Saving Throw.

**Comment by TravisGesslein** [comment]
True, should be a quick fix as well. Will do!

**Comment by TravisGesslein** [comment]
Yup, fixed in next patch.
