### ISSUE TITLE
Blood lust / Unrelenting Assault not refreshing on Primal Rage / EnrageBuff refresh

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#503]
Shouldn't it refresh if EnrageBuff is refreshed before the Unrelenting Assault buff is timed out?

**Comment by TravisGesslein** [comment]
Yup someone in chat recognized the same issue. Will look into it.

**Comment by TravisGesslein** [comment]
Fixed next patch. Although I actually allowed it to trigger multiple times on the same raider (instead of just refreshing the old buff). Potentially OP for fast attack speed raiders, but seemed cooler. I would ask you and other players to keep an eye on it :D
