### ISSUE TITLE
tent bonus at tent destroying

### ISSUE THREAD

**Issue by svendief** [Heishe/idleraiders-second-run#51]
Hallo ich habe ausversehen ein paar zu viel gebaut bzw nicht gesehen das es ein limit geht und dachte ach komm zerstör ich die anderen mal ja jz hab ich noch 2 stehen aber der boni hat sich mit abgebaut mit den ersten 2 ich habe das jetzt nur mit den mana reg zelten bemerkt bei den anderen kann ichs noch nciht ausprobieren :D

**Comment by TravisGesslein** [comment]
Jop, Bug ist im Patch gefixed den wir demnaechst (kommende paar Stunden) hochladen! Issue dazu war #6 

Willkommen zurueck uebrigens :D
