### ISSUE TITLE
[BUG] Weapon/Armor/Enchant Research

### ISSUE THREAD

**Issue by Burodsx** [Heishe/idleraiders-second-run#515]
When you purchase the 10% upgrades, the enchants on the skills mostly stay the same. Only a few skills will update to the new %.

For example, when I bought the 20% upgrade my Warcry lvl 2 immediately became a +60% duration enchant, but all my other skills are the same.

**Comment by TravisGesslein** [comment]
The intended behavior for this is for all existing enchants to NOT update. It's basically an important gold and resource 'sink'. However there exists an issue somewhere on here that references a similar problem, where some enchants get updated and some don't (Can't find the # at the moment). Will reference later.
