### ISSUE TITLE
Missing Bonus Rage Regen

### ISSUE THREAD

**Issue by Arbyter117** [Heishe/idleraiders-second-run#518]
![image](https://cloud.githubusercontent.com/assets/26194449/23749257/52e2bea2-0495-11e7-992e-1bd73d7b2365.png)

I have the full might of the sealer set but my warriors don't get the bonus 100% rage regen. All the other buffs apply, even the other 6 item bonus.

**Comment by TravisGesslein** [comment]
It's generation, not regeneration. Rage generation is what gives you rage when your Warrior attacks or gets attacked :) As you can see the value is at 270%, 40% from the two capes, 30% from the nosering, and 100% from the set bonus.
