### ISSUE TITLE
Inventory slot changes on mouseHold, not on mouseClick

### ISSUE THREAD

**Issue by Guguskis** [Heishe/idleraiders-second-run#523]
So basically, when I drag equipment from inventory to raider and hover over 1-8 inventory slot it gets clicked. To fix this you need to change the way we click on inventory slots by making it mouseClick, not mouseHold

**Comment by CodedNil** [comment]
Agreed, is very annoying

**Comment by TravisGesslein** [comment]
Yup, sorry about this. Next patch will introduce a small delay where you have to hold the item over the tab(this was suggested by someone else in a different issue, but I can't find it at the moment, thanks) before the tabs switch. This makes sure the tab only changes when the player actually intends to put the item into a different inventory tab.
