### ISSUE TITLE
Thoughts and suggestions

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#53]
I already posted a similar topic on reddit, but nothing seems to happen there, so I'll just put it here too:
### 1. UI: Views and Modes

Over time I've gotten more used to it, but I still don't like how we change views and modes. I think we should have an option/button to expand the width of the sidebar/flags, so we could always see all available modes/views.

I think I'd also be in favor of replacing the view options with a toggle button of:
1. Wherever your raiders are (going)
2. The base.

And having the function disabled when the raiders are in sleep mode.
### 2. UI: Notifications

Replace the yellow exclamation mark with an icon that visually represents the event (e.g. head of merchant, for the merchants; a heart, for the love event etc.). This reduces redundant tooltip reading for events you already know, and makes you more conveniently aware of what's happening.
### 3. UI: New items looted

The inventory button in the sidebar should indicate that new items have been looted, just like individual items does now.
### 4. Plans

Plans feel weird. Here's why:
1. When seeing the plan in the trade window, you're only given the name of the building that it will do. It doesn't tell you what that building does, or what that building costs to build. This makes it very hard to judge what is worth buying, since gold is very scarce in the beginning.
2. When you've bought a plan, you have to go into the inventory and use it first to unlock it. I see no reason to keep an unused plan in your inventory, so this doesn't really make sense.
### 5. UI: Sorting icon

The sorting icon probably shouldn't be visible when you only have 1 raider.
### 6. Hovering buffs

When you hover a buff, an indicator arrow appears above all affected raiders. It would be nice to have an indication on which raiders those are in the left sidebar stats overview. E.g. I wanted to check which warrior got the rejuvenation buff on, but it doesn't really show me if it's the one with low hp etc.
### 7. Text tutorials

I know you're thinking about how to make a tutorial now. My biggest advice to you is to use as little text explanation as possible. At least for understanding the basic game mechanics (how to farm, how to raid, what the goal is, how to reset etc.). Juicy Beast Games described it well in this blog post:

http://juicybeast.com/2014/10/designing-a-playable-ui-that-secretly-teaches-how-to-play/
### 8. Levels

I think the raiders' level should be visually represented more than just in the tooltip. Especially because it's a very important indicator of current progress. It also gives you a subconscious way to judge how strong you need to be to fight the next boss (e.g. "I tried the 2nd raid in level 6 and failed - so maybe I'll wait until level 8 in this reset). On top of that, it grants you an extra sense of progress after every reset too, since you're given the opportunity to notice that you can defeat more and more bosses at lower and lower levels. Lastly, it makes it easier to remember if you've ever been to a certain level before (e.g. "hmm I don't think I've ever seen that number show 54 before - and it's visible at all times, so I probably never have been. I should probably pay attention to that number").

Ideally I imagine the number being slightly bigger than the current UI buttons, and then giving it a quick shiny/fancy animation effect that grabs your attention whenever you level up.
### 9. More milestone content centered around leveling

The (leveling) path to level 50 is confusing and kinda non-interesting for the most part. In the first run, you don't really know what's gonna happen when you level up. And if you haven't discovered that you can hover the exp bar, you don't even know what level you are. You probably just notice that you get stronger over time, and that the purple bar means exp.

So to spice it up, I would suggest making it more clear that leveling up unlocks a new raider. And other things could require levels too, if they don't already (I got the notion that some plans didn't become available to buy before I reached a certain level, or accomplished certain other things - but I was clueless about what actually did it in the end).
I think item/equipment slots are one of those things that I think should be on that list. E.g. level 15, 30 and 45 could unlock an item slot each (instead of everything only being unlockable by gold). 

You could also grant 10 or X ancient artifacts every 10 or X levels. And perhaps the same or some amount for every level above level 50.

Leveling far above level 50 could also grant you other special/powerful things.

The unlocking plans could also be integrated with this mechanic. But the decoration plans should probably never be unlocked alone. So either they should be unlocked together with other plans, or be unlocked in another way (like the travelling archite.. _ahem_ .. merchant).

And if the next reward was visually represented (or at least a way to view some sort of roadmap), then I think the anticipation and clear milestone goals could be a lot more entertaining in the long periods of waiting time.

Obviously I know this suggestion is a long shot - but I don't really care if you implement it as I describe it. I just hope you make a game that I can enjoy playing alongside enough players for there to be a kongregate chat :P

**Comment by Drakenfeld** [comment]
Adding onto Views and Modes: http://imgur.com/grCqORX Enough said, image speaks for itself.

**Comment by askebv** [comment]
@Drakenfeld I'm not sure I follow. Is it that the text is too small and unreadable?

This is what it looks like to me:

![image](https://cloud.githubusercontent.com/assets/4981659/15753386/0639be12-28f3-11e6-8c11-499b736e49c7.png)

But yeah, I can easily see that as a problem for lower resolutions, if that's what it looks like. Good point.

**Comment by TravisGesslein** [comment]
Thanks for the suggestions, we just uploaded a patch so I'm going to take a break and reply with a bit more detail later!

Regarding reddit btw: For now we only sent beta invites to a few select special people like Ethismos and muskar as well as all of the paypal donators from the alpha. Our analytics show that less than 20 people are playing the beta right now, compared to the roughly 1000 that still play the alpha every day.

A couple of days from now when most of the worst bugs are ironed out we're going to send out more keys and (among other things) announce the beta on the subreddit. I hope discussion increases a bit more there at that point. Github issues list isnt the best medium for it :D

**Comment by askebv** [comment]
@Heishe Should I delete my post on the reddit then? You can also do it yourself it you want to, I don't mind. I think it must be your choice how you want to market/expose your content.

**Comment by TravisGesslein** [comment]
No I don't mind it at all!

**Comment by TravisGesslein** [comment]
Thank you for the suggestions. For once I will try to be concise :hankey:
1. We will add this as another button below the activity UI at the top mid of the screen, which toggles between the two views (view base/view wherever raiders are). We will also add a toggle to let the camera automatically follow raiders similarly. Both of these will be visible whenever the raiders are doing any activity (And invisible when they are resting in the base, like the rest of the activity UI). We will leave the other buttons in. We want to leave separate view buttons if players want to look at farm maps, raid maps, etc. while the raiders are actually doing something different.
2. We'll put this onto a to do list, let's see if we have time to get around to it.

3,4,5,6 good ideas, I will create separate issues for them
1. yep, I find writing text explanations boring anyways
2. already implemented!
3. yep, the primary gameplay vehicle for this stuff will be the book of prophecies... I think I mentioned it in another issue somewhere.

Close one issue, open 4 more...
