### ISSUE TITLE
Bug or Intended? Farm map AA rewards

### ISSUE THREAD

**Issue by BlakeKMcD** [Heishe/idleraiders-second-run#534]
I'm not sure if this is a bug or not, but no one else in the chat had an explanation for it. When ascending farming maps for the first time you get AA the prophecy quests say you'll receive. I've noticed though that reaching those levels after your first time doesn't reward the same amount. I've been receiving 20 AA less than the first time (for example when reaching map 10 i receive 90 AA instead of 110, map 20 rewards 190 instead of 210). If that's the intent then there's nothing wrong, just confused and curious. If it is a bug then I'm glad to have helped.

**Comment by askebv** [comment]
#457 Yeah I've noticed too ;)

**Comment by TravisGesslein** [comment]
Will be fixed next patch!
