### ISSUE TITLE
Temple of Ancients has no use

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#54]
Ethismos already mentioned this somewhere else, but I just tested it myself and confirmed that the Temple of Ancients doesn't do anything. You can "Gain Wisdom", buy and toggle upgrades, without the building. It shows up by itself once you clear the 3rd raid. 

Secondly, the description says the building can do something else too:

> Also allows raiders [sic] trade their experience points and some gold to unlock their earned Ancient Artifacts

As far as I can see, there's nothing that requires/uses exp or gold in the Raider Upgrade menu.

**Comment by TravisGesslein** [comment]
Yeah it's a bug, the icon isn't supposed to show up until you build the temple! 

The description was supposed to hint at the fact that your raider level gets reset ( = trading in all your experience), but I'll update the description.

**Comment by askebv** [comment]
Ah, of course. Yeah, it didn't even occur to me that it was talking about resetting.
