### ISSUE TITLE
Graphics really messed up post refreshing cache for patch

### ISSUE THREAD

**Issue by Sayith** [Heishe/idleraiders-second-run#540]
i refreshed my cache to get the new patch and when i loaded in the login screen looked odd then the game was like this i have refreshed re cleared cache and closed browser not sure what else i can do to fix this

http://prntscr.com/ejz5xu

**Comment by Sayith** [comment]
resolved after a hard reset of the PC

**Comment by TravisGesslein** [comment]
Closing this to tunnel everything into issue #545 (since they all probably have the same root cause).
