### ISSUE TITLE
Small visual bug: Reward not showing when hitting auto-increase

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#541]
![animated gif](https://i.gyazo.com/71fcb902ad8f91f5fabb2798ef02a588.gif)

1.  Go to a lower level map
2. Hit auto-increase
3. Reward isn't showing for getting 10 kills on the map.

But if you change level back and forth, it works.

**Comment by TravisGesslein** [comment]
Should be fixed now.
