### ISSUE TITLE
Holy Warrior buff bug

### ISSUE THREAD

**Issue by Pentro** [Heishe/idleraiders-second-run#542]
[error_report.txt](https://github.com/Heishe/idleraiders-second-run/files/842664/error_report.txt)
So basically to reproduce this recruit Brian and wait till he activates the Spirit of the Righteous buff which creates an error without fail. Didn't notice any other side effects apart from the buff having no duration (not sure if intended).  Attached the error dump that comes with it aswell.

**Comment by TravisGesslein** [comment]
Thanks for the error report. Will be fixed in 1.0.5a
