### ISSUE TITLE
New Update Problems: Lost gear/AA upgrades/snapshots/farm level rewards bar in the way

### ISSUE THREAD

**Issue by Meissner-Effect** [Heishe/idleraiders-second-run#543]
With the most recent update, Great Heal is now unique making my duplicate Great Heals not only unable to be equipped but removed from my inventory, which then breaks all my snapshots that have Great Heal equipped like this one:
![capture](https://cloud.githubusercontent.com/assets/26352345/23925900/4bbc21d6-0909-11e7-9a60-0fb79b3daec5.PNG)

When I try to use a snapshot, it says the following:

![capture](https://cloud.githubusercontent.com/assets/26352345/23926005/c964f9aa-0909-11e7-8466-07b579a016d6.PNG)

It would be great if snapshots could still be used even if items are no longer compatible with the updated version, just remove the affected items from the snapshot. 

Also, next time ancient artifact (AA) upgrades are cancelled, it would be nice to have the AA refunded to the users that previously purchased them. Max Upgrade has been down-graded from 20 lvls max (+100% buff duration; all upgrades costing 63,000 Ancient Artifacts) to 10 lvls max (+50% buff duration; all upgrades costing 16,500 Ancient Artifacts), which means some users lost 46,500 Ancient Artifacts worth of upgrades:

![capture](https://cloud.githubusercontent.com/assets/26352345/23925746/978a47e2-0908-11e7-8ca5-683211e4a5ff.PNG)

Next, the new farm level reward bar gets in the way of the raid map statistics:
![capture](https://cloud.githubusercontent.com/assets/26352345/23924624/4d01bebc-0903-11e7-884d-825e0a40de4d.PNG)

While I can simply move it out of the way to see those, it would be nice to see those by default without having to move windows.

![capture](https://cloud.githubusercontent.com/assets/26352345/23924992/126ac684-0905-11e7-88d4-7b8bae40807d.PNG)

The farm level reward bar also gets in the way of the default equipment window. I cannot change the top right skillbook slot without moving the equipment window somewhere else:

![capture](https://cloud.githubusercontent.com/assets/26352345/23926685/762c1918-090d-11e7-83cb-552d02100267.PNG)

Excellent game, just giving some feedback on the recent changes.

**Comment by askebv** [comment]
The last issue with the windows is probably related to the window issues in general:

#413 , #528 and possibly #393
