### ISSUE TITLE
Save file reset and overwrote

### ISSUE THREAD

**Issue by Hermeus** [Heishe/idleraiders-second-run#555]
Kong ID is Hermeus. Time stamp was around 7pm central time. Notes for progress Max farm level 930, most resent loot was Gold Sword number 16. I had just updated from 1.0.5b as my computer had not cleared the cash when I reset it earlier. 1.0.5 had been glitching and saving error logs, I have some available but chrome stop saving them when more then one was collected when afk.

Events as I recall them for last load of game state. My game was running and studering, as in locking up from time to time. So I did a manual save, as I had just got the gold sword, and did a system restart. Then the save file overwrote.

**Comment by TravisGesslein** [comment]
Hi, can you please get in touch with us at social@pitforest.de? Closing this issue (this tracker isn't meant to be used for support issues, just ingame bugs, etc.)
