### ISSUE TITLE
How does the training facility work?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#56]
I can't seem to interact with the Training Facility, nor do I see any change in any of the menus.

Is this a bug, or am I missing something?

EDIT: Nevermind - it gives a new mode.

**Comment by askebv** [comment]
The survivability mode doesn't seem to work. It just says Enemy dps 0? I was suspecting it to incrementally increase its dps, or being able to adjust it.

**Comment by TravisGesslein** [comment]
It's supposed to give a new mode in the activity UI, but it should also open the same UI if you click on the building. Will investigate. Will also investigate the 0 dps bug. Behavior should be exactly like you suspected.
