### ISSUE TITLE
[Bug] Raiders get stuck in Tomb of the Pharao

### ISSUE THREAD

**Issue by miruk** [Heishe/idleraiders-second-run#562]
In the raid Tomb of the Pharao if the second boss spawns any mummies over a wall, after your raiders killed the boss and any mummies in the room they just stand there trying to aggro the mummies on the other side of the wall, unable to progress anymore until you either manually leave the raid or auto raid moves you out at the next reset
image of this happening:
http://imgur.com/a/ia7O4

**Comment by TravisGesslein** [comment]
Should be fixed next patch.
