### ISSUE TITLE
Old player review

### ISSUE THREAD

**Issue by Plop86** [Heishe/idleraiders-second-run#563]
So i play since the earliest stage of the game.
Game difficulty curve used to be big at the start meaning weeks of farming and reseting to progress a single raid, which most of us liked (even the rough start), the time were artifact came like once a week if lucky and felt very rewarding.
But now since last patch you guys made the game way too easy, i believe a week or 2 playing actively is enought to reach end game and ending into the grinding.
The map pushing is way too rewarding i mean the aa reward is insanely huge and is also free of gold and every 2 map. I pushed throught 5000+ maps got 55+ wair ended with 750+ exp upgrade and 200+ gold.
Even i saw new player getting easily 25+ wair and 200+ exp which took us months + at the start.
I mean i don't know what content you have in mind to conpensate the huge power spike player are having.

Also the holy warrior used to give a damage buff which never happen now when i recruit him.

**Comment by TravisGesslein** [comment]
That end game WAIR explosion was unintended. Next patch will rebalance all of that. Farm map monster HP will scale up much harder, and there will be a timer limit within which you have to kill the farm map monsters. 

This will retroactively apply to current savegames btw, so people's progress will be downscaled to something that makes more sense in the new progression curve, but relative progress will be preserved.

**Comment by Plop86** [comment]
You didn't answer the holy warrior bug, i don't see the buff when recruiting him

**Comment by Meissner-Effect** [comment]
Only the experienced holy warrior seems to give the damage buff. The buff doesn't apply when recruiting him, but rather during battle. So far it is working fine for me:

![capture](https://cloud.githubusercontent.com/assets/26352345/24134685/c7c4f8e0-0dfd-11e7-8b9e-d338d7664089.PNG)

**Comment by TravisGesslein** [comment]
Will look into the buff not triggering for the basic holy warrior!

**Comment by TravisGesslein** [comment]
That bug will be fixed next patch. @Meissner-Effect the basic holy warrior is supposed to give it, too. The experienced one gets an additional ability in addition to the basic buff.
