### ISSUE TITLE
Bug after patch: Cloud save bug and "open a file"-prompt bug

### ISSUE THREAD

**Issue by Jubetsu90** [Heishe/idleraiders-second-run#571]
My game is having a lot of trouble with something related to cloud saving. I keep getting a message that my local and cloud saves are not in sync. Saving doesn't help as long as I have cloud saving on.
When saving new snapshots, there's a message that it wasn't saved to cloud (probably because I turned off cloud saving.)
I keep getting message "succesfully logged in"

Sometimes a part of the window seems to become an invisible button. Clicking this button would open a windows prompt for "open a file from your computer" as if searching for a save file to import or something. The "button" is probably always at the same spot and by moving the map/UI part I want to click away from the invisible area they work fine.

**Comment by TravisGesslein** [comment]
Yes, this will be fixed in an upcoming patch (1.0.4d) that is currently being prepared to upload!
