### ISSUE TITLE
[Suggestion] Bulwark AI broken to the point of uselessness

### ISSUE THREAD

**Issue by GregTheTraceur** [Heishe/idleraiders-second-run#572]
Can the bulwark upgrade be broken into two upgrades? As it stands now I have to choose between my raider using all of them at once (thus being useless) and my raider not activating any because it is so confident that it's not dying (thus being useless). The zombie hits for ~60% of my warrior's health, so after one hit, he's only at 40 and thus not scared. Second hit dunks him. 

The bulwark upgrade should be broken into 1, having it be a last resort, and 2, not activating a second one until a previous one ends. (IMO, upgrade 2 should just be standard, but it's your game)

Thanks for all of the hard work you're doing!

**Comment by TravisGesslein** [comment]
All of them being triggered at once isn't supposed to happen. Standard behavior is that raiders check if they already have a buff, and then not trigger (whatever the buff is) if they do. Bulwark doesn't do this because it's bugged, will be fixed as soon as we can get around to it!

**Comment by TravisGesslein** [comment]
Should be fixed next patch!
