### ISSUE TITLE
Bug: Jumping to black

### ISSUE THREAD

**Issue by BertIgermann** [Heishe/idleraiders-second-run#573]
Clicking on some places on the map (Base/Farm&Raid) will result in a jump to a black area. In Base its mostly the left side and it goes for both left and right clicks. In raids and farms the spots are very random.  Pressing F or B to either focus on raiders or going to base will get you back.
This bug makes it hard to move around on the maps with mouse in fear of hiting such a teleport pixel.

**Comment by TravisGesslein** [comment]
Hi, can you provide me with a savegame (and exact locations where to click) where this is easy to reproduce? I currently fail to make this happen.

**Comment by BertIgermann** [comment]
Bug already resolved in one of the updates I could not reproduce it anymore. But Thx for the response

**Comment by TravisGesslein** [comment]
Good to hear :)
