### ISSUE TITLE
Time pressure triggered by Hail of Arrows

### ISSUE THREAD

**Issue by Kukkaherra** [Heishe/idleraiders-second-run#577]
All the kills done by Hail of Arrows count as kills for one of the archers. The kills done by the skill can trigger Time Pressure (presumably also all other trigger based skills, but none of them have any effect once map is clear of monsters).

If both archers are equipped with 1 x Hail of Arrows and 3 x Time Pressure, it is noticeable that one of the archers consistenty has less cooldown remaining on Hail of Arrows skill than the other right after skill use.

**Comment by TravisGesslein** [comment]
Closing this as the underlying cause is the same as #387
