### ISSUE TITLE
Crash with Error Report lead to empty manual save

### ISSUE THREAD

**Issue by KuKKilicious** [Heishe/idleraiders-second-run#581]
while the connection issues were going on the game did it's crash error report popup thing. 

error report:

http://chopapp.com/#vy2032ro

i did a manual save afterwards, restarted the game with clearing cache, tried to import and it didn't work. 
While the connection issues were going on, i tried to load the game, which resulted into a new game, which overwrote the cloud save file. 

I tried to import the save in question again while looking into the console:

http://imgur.com/a/HxyY3

i figured, the save was an empty file..

My Connection to Kongregate was stable the whole time.

I was able to recover my current game with the savegame in the error report. So that one was valid.

**Comment by TravisGesslein** [comment]
Hi,
glad you were able to recover your save with the file inside the error report. Sorry this happened. The bug that caused this should be fixed in the current version of the game that was uploaded this morning (1.0.5f).
