### ISSUE TITLE
Ancient Wisdom:Longer farm map timer

### ISSUE THREAD

**Issue by Julianhau** [Heishe/idleraiders-second-run#582]
http://imgur.com/XAzvVoS
i only add 1 point, timer +20s,in description is +5s
so~which one is right?

**Comment by TravisGesslein** [comment]
1.0.5e also buffed the timer to 75 seconds. We haven't released changelog yet because we didn't want people to reload the game all at once (as we're still dealing with some server load issues caused by external attacks, currently it's going well enough but we didn't want to tempt fate).
