### ISSUE TITLE
Save gone after the ddos

### ISSUE THREAD

**Issue by Plop86** [Heishe/idleraiders-second-run#583]
When the ddos occured i loaded my save which was like 20 days old since my current one didn't show (i played the day before so shouldn't have been that far away). Anyways the game overwrite my file as i load this save. So i'm thinking it's ok my actual save will come back when the cloud is back up, unfortunately it doesn't show my latest save still load the one from 20+ days old losing me a major progress. I do not own any current that close to that savepoint.
So how will this be fixed ?

**Comment by TravisGesslein** [comment]
If the save was truly deleted (and you can't restore it), we can send you a backup if you give us an email to send it to.

**Comment by Plop86** [comment]
Sure how do i do that ? i mean at which adress

**Comment by TravisGesslein** [comment]
Oh, sorry, of course it would be unwise to post yours publically like this. Shoot us an email to social _at_ pitforest.de!

**Comment by Plop86** [comment]
Sent thank you for answering.
