### ISSUE TITLE
Farm Map Exp

### ISSUE THREAD

**Issue by Hermeus** [Heishe/idleraiders-second-run#584]
Farm maps above 200 do not give exp, this has been tested by multiple accounts on multiple levels above 200.

**Comment by TravisGesslein** [comment]
Thanks, I will look into it.

**Comment by TravisGesslein** [comment]
Yes I found the error, thank you for reporting it. Will be fixed next patch. This is quite an urgent issue (in the sense that it's annoying that those monsters don't give XP) so I will see about getting that patch out there as soon as I can.
