### ISSUE TITLE
Witness of the Ancients Set Description Correction

### ISSUE THREAD

**Issue by Meissner-Effect** [Heishe/idleraiders-second-run#590]
The Witness of the Ancients set descriptions states, "(4) Permanently increases all XP gained by 100%."

![capture](https://cloud.githubusercontent.com/assets/26352345/24326372/010c9a90-11a5-11e7-9b3c-696f5144f32e.PNG)

However, upon testing this set, it only provides double XP when the set is equipped. Thus, the 100% XP gain is not "permanent" - should probably be changed to something like "(4) Increases all XP gained by 100%."

**Comment by TravisGesslein** [comment]
Makes sense. Will be fixed :)

**Comment by Meissner-Effect** [comment]
Thanks - looks like the recent update has the corrected text now :)
