### ISSUE TITLE
Crypt Key stuck in quick-actions

### ISSUE THREAD

**Issue by explodes** [Heishe/idleraiders-second-run#603]
When I started 2nd run for the first time, one of the first things I did was added Crypt Key to my quick actions bar. 

I've since used it, and I'm unable to replace it or remove it from my bar.

![image](https://cloud.githubusercontent.com/assets/782367/24586518/6a047804-1760-11e7-9ac6-a60310df108b.png)

**Comment by Meissner-Effect** [comment]
Try double-right clicking on it.

**Comment by explodes** [comment]
That did work.
