### ISSUE TITLE
[BUG} item dup 

### ISSUE THREAD

**Issue by vorakk** [Heishe/idleraiders-second-run#613]
just found this by chance really i put one cane in, i'm labeling them mage 1 and mage 2, mage 1 cosmetic slot then i draged a cane from mage 2's equipment slot right to the cosmetic slot of mage 1 then put it back but now i have 2 of the same cane that i put in the cosmetic slot the first time

**Comment by Meissner-Effect** [comment]
While I can place two of an item in a cosmetic slot using this bug, it does not seem to duplicate the item as I still have the same number of the item before and after. However, this bug would allow players to get more than 9x of unique items by stacking them in the cosmetics slots, which allows more unique items to drop.

![dupitem](https://cloud.githubusercontent.com/assets/26352345/25067612/bbb300d6-2240-11e7-8a4d-742bef3531a2.PNG)

**Comment by vorakk** [comment]
i knew that once i get back home away atm for easter partys i'm gonna try to do what i did and record it cause i could have swore i had just 1 staff then somehow i got 2 and they both came from cosmtic slot i'll let ya know

**Comment by vorakk** [comment]
ok checked it 3 times and yes it duped everytime mage1 gets item in cosmetic weapon slot then i  tried to switch the item in mage1's cosmetic weapon slot to mage2's 4th equip slot look like it didn't switch then in switched mage2's  4th equip slot to mage2's cosmetic weapon slot  and some how through all that i duped the item in the cosmetic slot i got a video of it if a dev wants me to email them cause this board won't accept video files

**Comment by Meissner-Effect** [comment]
[moved contents to beta bug report page]

**Comment by vorakk** [comment]
well now it's confirmed maybe we should get rid of this post so no one repeats the process for ill gains

**Comment by Meissner-Effect** [comment]
Okay - I have moved post contents to beta bug report page for pitforest to see. You can close this issue here by clicking the "Close Issue" button at the bottom of the page, which will at least take the post out of the spotlight.
