### ISSUE TITLE
Sealer's burden

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#62]
http://imgur.com/4rlHot6

I equipped the ring and it didn't update as a set item (at any of the 3 items equipped). 99% caused by the fact that i had 1 more in my inventory.

When i tried to equip the second it got deleted (and left an empty purple box) and re-equiping my ring fixed the issue!

**Comment by TravisGesslein** [comment]
Mhm... can't reproduce. You had two Sealer's Burden in your inventory?

**Comment by TravisGesslein** [comment]
OK was hard to reproduce but I managed eventually... should be fixed in patch 3.
