### ISSUE TITLE
[BUG] Cloud saves seems to have issues.

### ISSUE THREAD

**Issue by nukeit** [Heishe/idleraiders-second-run#620]
Hello,

I have the game running like always and if I try to save to the cloud and to load that save on another tab, the game status is not the same as the one I just saved. It's like every save I make now are the same exact state and make me rollback like 2-3 days or so ...
I also cannot do any new cloud save (only have 2/5 so far).

Could you please check this issue? It seems I'm not the only one have this problem at the moment.

Thank you :)

**Comment by TravisGesslein** [comment]
Sorry about that, will investigate.

What browser do you use btw?

**Comment by nukeit** [comment]
I tried it on Chrome & Firefox (both up to date), none seem to work so far.
I also tried to export the game directly and to load that file but without success.
It seems I was able to save normaly by desactivating the cloud option for now (and I can't reactivate this option now)

**Comment by TravisGesslein** [comment]
OK, thanks for the info. One last question, what country do you play from? Would be helpful to know if we should check for any latency related issues.

**Comment by nukeit** [comment]
I'm playing from France.

Thanks for your fast feedback, I'm sure you'll find out the issue, keep up the good work ;)

**Comment by f8cker** [comment]
Same happen to me. Is it possible to have all the data back ? According to the kongregate chat it happened to many people. I have rollback my whole play from morning(11hours).
Using Chrome browser.

**Comment by TravisGesslein** [comment]
Hi, can you check if it's working again now?

**Comment by nukeit** [comment]
Wow that was fast, it seems to work fine now :)

Thank you very much for your fix. 👍

**Comment by f8cker** [comment]
saving works again, but data are lost yes?

**Comment by nukeit** [comment]
Yeah, I lost a bit of data there but for me at least it's not too bad.
I mean I lost like 3-4M gold, no big deal.

**Comment by TravisGesslein** [comment]
Yes, unfortunately we're unable to restore that lost progress, I'm very sorry.

**Comment by TravisGesslein** [comment]
Should note that anything store related can just be unpacked again in savegames that are set back (so you will have unopened chests, etc.)
