### ISSUE TITLE
[Bug] Expirienced Holy Warroir dont cast anything.

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#642]
[Bug] Expirienced Holy Warroir dont cast anything.

**Comment by zaqaz123** [comment]
He dont cast attack speed

**Comment by hamburml** [comment]
Thanks for your report.

This issue will be fixed when the next patch is uploaded.

Thank you very much!

**Comment by hamburml** [comment]
@zaqaz123 Patch was released today. Experienced Holy Warrior should cast his ability when his holy rage reaches 100. He does not decrease rage like a normal warrior.

Please try it out and let us know if everything works as expected.

**Comment by zaqaz123** [comment]
dont cast when rage =100
unknown trigger for cast. 
when cast - no buff icon 

Also no icon with +10dmg buff

**Comment by hamburml** [comment]
He does cast his ability.

![image](https://user-images.githubusercontent.com/7239350/29735936-2884b564-89fd-11e7-8d2b-6fa7f5e6729b.png)

His ability currently doesn't show a buff icon and the global +10 dmg buff icon is also there. When all temporary buffs are also shown on the top side it will be full very fast. We are working on a better visualization. 

The Experienced Holy Warrior casts the ability when he is near an enemy in a fight.

![image](https://user-images.githubusercontent.com/7239350/29735963-692c1788-89fd-11e7-8244-fa0853282af1.png)

**Comment by zaqaz123** [comment]
okay om try again

EHW stay near battle 60 or more sec with 100 rage, and dont cast anything.  in second min EHW cast, but there is no buff icon.

after i restart gam buff + 10 dmg apperead, but EHW stay with rage again 1 min and then cast . i check dmg - he add ~25%, but there is no buff icon for it

**Comment by zaqaz123** [comment]
you can get this "bug" - no icon - if hire EHW when your warroirs on farm map

**Comment by zaqaz123** [comment]
dont finished, 
but im close
