### ISSUE TITLE
[Bug] Vampire drop bug

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#643]
On Castle of Undiing vampire drop unkonw item and it generete exception (red message on game).

**Comment by hamburml** [comment]
Hello zaqaz123,

thanks for your work and the created issues.
Sadly I am unable to reproduce this error. What browser did you use? Do you have a screenshot of the red message?

Thanks!

**Comment by Talisca** [comment]
I think this is related to #653

**Comment by Talisca** [comment]
Should be the same issue. The loot of the vampire is alright.

One of its skills got a bug. I will close this issue for now. 

If you got further informations or if you are sure its completly unrelated to the mentioned issue and problem, let us know.
