### ISSUE TITLE
Cones not received on first purchase

### ISSUE THREAD

**Issue by MBVindicator** [Heishe/idleraiders-second-run#647]
The first purchase of cones on my profile, MB_Vindicator were not received even though the kreds were spent, this was 12000 cones on August the 4th, please resolve this.

**Comment by hamburml** [comment]
Hello MBVindicator,

I just checked our transaction-records and I saw all your cone-pinecone-transactions. We are sorry for the inconvenience caused, I just credited your account the missing cones. Please reload the game, the pinecones should be displayed correctly.

Thanks for playing Idle Raiders: Second Run.

**Comment by MBVindicator** [comment]
Thank you very much.

**Comment by hamburml** [comment]
Your welcome. Currently I investigate why this happened.
