### ISSUE TITLE
[Bug] False Courage give 10%, not 20%

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#650]
in description  - 20%, in buff list 10%.

**Comment by hamburml** [comment]
Thanks for your report.

This issue will be fixed when the next patch is uploaded.

Thank you very much!

**Comment by hamburml** [comment]
@zaqaz123 Patch was released today. False Courage description should now mention 10% buff.

Please try it out and let us know if everything works as expected.
