### ISSUE TITLE
 [Bug] Tier 11 corrupts save data

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#651]
players says Tier 11 corrupt save data if set is weared

**Comment by hamburml** [comment]
Thanks for your report.

This issue will be fixed when the next patch is uploaded.

Thank you very much!

**Comment by Fkscorpion** [comment]
@hamburml any ETA when the patch will arrive?

I'm not able to play till then 😞

**Comment by hamburml** [comment]
@Fkscorpion Patch was released today. 

Please try it out and let us know if everything works as expected.

**Comment by Fkscorpion** [comment]
It does! :)
