### ISSUE TITLE
 [Suggestion] Archers - sucks

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#656]
![e362d-clip-89kb](https://user-images.githubusercontent.com/30842520/29630252-f9f8c2f2-8854-11e7-95cf-71478bdf4c9f.png)

Warrior have good items with speed attack and spell mightly blow which deal x10 DMG 
with good Speed Attack warriors have +many rage regen and can cast Blow 4-10 times every sec.
Mages have fireball with 0 cost, it deal x9 dmg with passive magic missiles +0.5x dmg =x15 dmg per cast and items with speed attack  x Crit

Archers havnt good spell without focus use, archer complect items bad, bcse archer need   2 item with focus regen (for cast quick shot or focused ).

Balance archers.

**Comment by zaqaz123** [comment]
also tripple shot useless in pushing - mobs regen give more HP to mobs than randers deal. 
You can change mechanics - disable regen and increase HP for example.  It make tripple shot and hail useful.

**Comment by derpxiaoping** [comment]
Archers are balanced. You're just assuming that they are a DPS class, when they are not. Archers are dispel/suuport bots, and they do that perfectly well. The DPS stats on their items is just there because there are no support stats in the game.

**Comment by derpxiaoping** [comment]
Archers are balanced. You're just assuming that they are a DPS class when they are not. Archers are dispel/suuport bots, and they do that perfectly well. The DPS stats on their items are just there because there are no support stats in the game.

**Comment by TravisGesslein** [comment]
Should also be noted that actual DPS skills are a huge improvement. If you had 4 Focused Shots in there instead of Mark Enemy the numbers would look quite different. Of course you have to trade that off with possibly less buff/debuff skills.
