### ISSUE TITLE
Suggestion: Mana regen in base

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#66]
It would be nice to have some form of additional mana regeneration in base. Maybe a new building or just improve the existing mana regen ratio. Waiting a 210 mana mage (full damage with 0 regen) to go to full mana takes ages.

**Comment by askebv** [comment]
There is already additional mana regen in base (I think maybe 2 or 3 times the normal speed). But yeah, it would be nice if we could improve it even further.

Or perhaps it could regenerate a percentage of the max mana when in the base.

**Comment by TravisGesslein** [comment]
Yup, already have an upgrade for the red priestesses on our to-do list to give them another spells which regenerates raider energy points. I'll leave this issue open until it's implemented.
