### ISSUE TITLE
 [Suggestion] easy change Area level

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#660]
im on level 1700. 
i must kill mouse to go to area 1.

Make text edit plz. clicking +100, +1000 not good solve\.

**Comment by Talisca** [comment]
I am not sure if its mentioned somewhere, but you can jump over 10 farm maps with pressed ctrl.

Nevertheless, you are right regarding the switch between the first farm level and the last farm level. I think this is also the only useful scenario. I can not think of any reason why a user would like to go to e.g. farm level 800 if the max unlocked farm level is 1700.

Will introduce such a feature in the upcoming content update.

**Comment by vd2b** [comment]
Middle-low farm maps (around 70-1000 range depending on WAIR level and items) are useful for their increased experience gains while also not losing on gold and items amount. E.g. for me it is currently map 647.

**Comment by zaqaz123** [comment]
@vd2b. it is not good for farm - for farm better farm on new raid with 1-7 opened (for better chance double rate respawn). exp not important after 1.10 patch/

**Comment by zaqaz123** [comment]
fucking developers with 1.3 patch
