### ISSUE TITLE
[SYSTEM BUG]

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#663]
http://clip2net.com/clip/m0/9b47d-clip-109kb.png?nocache=1

**Comment by hamburml** [comment]
Thanks for your report.

This is a problem with skill duration and cooldown settings. We are currently working on this. The [issue 631](https://github.com/Heishe/idleraiders-second-run/issues/631) already mentioned this. I would advice not using this combination right now, it freezed my browser.
