### ISSUE TITLE
Save Issues

### ISSUE THREAD

**Issue by musaii** [Heishe/idleraiders-second-run#666]
Occassionally, I'll get an error when I save.  Part of the error log contains "Maximum call stack size exceeded".  I will then have to either delete some items, or remove a gear set (I now only have 2 sets of gears).  Attached is the full error log.

**Comment by musaii** [comment]
[error_report (9).zip](https://github.com/Heishe/idleraiders-second-run/files/1254334/error_report.9.zip)

**Comment by Talisca** [comment]
Thank you for your report.

Will be fixed with the next patch!
