### ISSUE TITLE
Warrior Received damage bug.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#667]
After a few tries i think that "Sanctuary of the Forgotten" sometimes bugs your tanks to take 10% more damage permanently.

Edit: Also happens at Burning Cave. Probably some issue with 10% damage debuffs.

Before this raid (after refresh) my tanks can reach 10% damage received, after it 1-3 tanks always cap at 20%.

**Comment by hamburml** [comment]
Thanks for your report.

When the ability ShieldBlock was used by an enemy and the Guardian Shield permanent upgrade is active all raiders were buffed. The Guardian Shield should only be casted when the attacker, who has the ability ShieldBlock, is a raider or mercenary.

This will be fixed.

Thank you very much!
