### ISSUE TITLE
Frozen Coast raid

### ISSUE THREAD

**Issue by Drakenfeld** [Heishe/idleraiders-second-run#67]
Seems to be an bug with the last set of bosses, just killed them the last one to die ended with -1 Hp then all the raiders didn't get teleported out nor any item drops, then raiders just ran to the start then keep warping in and out none stop. canceled raid at that point then it says Cannot be started until next reset without an new raid unlocking.

**Comment by TravisGesslein** [comment]
Can't seem to reproduce. This might happen because something crashed when the boss was killed. If this happens to you or anyone else again, it would be helpful if you could open the browser console with F12 and see what kinds of errors it's throwing around.

**Comment by TravisGesslein** [comment]
Since nothing more came of this I'm pretty sure this happened because something unrelated crashed while the boss died. Will close until it happens again.
