### ISSUE TITLE
10% => 20% from Sanctuary of the Forgotten

### ISSUE THREAD

**Issue by ghost** [Heishe/idleraiders-second-run#671]
Sanctuary of the Forgotten changes warrior damage reduction from 10% to 20% permanently. This happens very consistently each time I have entered the raid and can only be reverted by refreshing the game. Possibly caused by some debuff, which doesn't properly resolve itself later.

This is not a visual bug, it actually reduces the damage reduction cap and not just the numbers on the sheet.

Very detrimental bug because it doubles the damage taken by your tanks.

**Comment by hamburml** [comment]
Thanks for your report.

Can you make a screenshot of your raiders and show your equipment?

Thanks!

**Comment by ghost** [comment]
Noticed just after posting that the same thing happens at the end of Burning Cave as well. Doesn't happen to all warriors at the same time, but usually affects at least one warrior after each pass.

![equipment](https://user-images.githubusercontent.com/31588175/30025425-2abecb04-9181-11e7-9d3a-c76630f45b00.png)
![normal without buffs](https://user-images.githubusercontent.com/31588175/30025438-3f04b010-9181-11e7-848a-aad0b07502a0.png)
![bugged without buffs](https://user-images.githubusercontent.com/31588175/30025447-439354ba-9181-11e7-9fee-488923369437.png)
