### ISSUE TITLE
Bug when purchasing Mercenaries: Negative gold.

### ISSUE THREAD

**Issue by Vadigix** [Heishe/idleraiders-second-run#674]
What I did and how to reproduce:
1) Have 1600-1650 gold.
2) Purchase Experienced Necromancer, do not close the window.
3) Purchase the regular Necromancer. You now have negative gold.

This appears to be a non-major bug, as waiting in a farm map put me back into the positives for gold. I did not test to see if I could purchase more things while having negative gold.

**Comment by hamburml** [comment]
Thanks for the issue!

This will be fixed with the next patch.
