### ISSUE TITLE
Since 1.1.3 killing ice golem crashes the game.

### ISSUE THREAD

**Issue by ghost** [Heishe/idleraiders-second-run#676]
Basically immediately when I kill the ice golem in Mountain Refuge the game crashes. Started happening instantly after the 1.1.3 patch. Visually the place where the golem dies is filled with a blanket of those falling ice spikes the golem summons. (So could be something like after death the golem summons the ice spikes without cd until the game crashes?)

This means I can't progress past that after I gain wisdom. So, would be nice to get a hot fix soonish. XD

**Comment by Talisca** [comment]
Thank you for your report. 
My bad. Had some typos in the implementation for disabling combat related effects :( 
Will be fixed today!
