### ISSUE TITLE
Since 1.1.3 killing bird in Witch Woods crashes the game. 

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#677]
[error_report.txt](https://github.com/Heishe/idleraiders-second-run/files/1288729/error_report.txt)
[error_report(1).txt](https://github.com/Heishe/idleraiders-second-run/files/1288730/error_report.1.txt)

**Comment by Greytallon** [comment]
[error_report-1.txt](https://github.com/Heishe/idleraiders-second-run/files/1289517/error_report-1.txt)

Same here.

**Comment by Talisca** [comment]
Thank you for your report.
This will be patched today!
