### ISSUE TITLE
Scholars tower skillbook level 1 from T9-T11

### ISSUE THREAD

**Issue by vd2b** [Heishe/idleraiders-second-run#681]
I have noticed that after you clear T9 raid (and also after T10 and T11) all books in Scholars Tower become level 1, while before there is a chance to get level 2 or level 3 depending on book, cleared tier and luck. So I think there is a bug where skillbook level is not set for T9-T11 raids. I think that it should be set to at least to the same value as for T8 raid.

**Comment by zaqaz123** [comment]
http://clip2net.com/clip/m0/5831f-clip-32kb.png?nocache=1
