### ISSUE TITLE
[BUG] Strange Damage on Area 9906

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#684]
My warrior have 2.8 mln dmg

After i join to area mobs dont make any damage, but after -10 sec they make 1mln dmg, 1.1 mlm dmg, 1.2, 1.4 etc

Then i make boss run and goblin priest kill all my mobs (2.8 mln dmg)

When i restart browser mobs in first sec make low damage again, but after seconds kill my tank on hit.

**Comment by zaqaz123** [comment]
http://clip2net.com/clip/m0/18cf3-clip-339kb.png?nocache=1
i try it again - priest kill my raiders again

**Comment by vd2b** [comment]
This is probably a Guardian Shield bug - when you take much of damage against your guardian shield it permanently becomes negative and adds to enemy damage instead of reducing it. This bug seems to start happening in version 1.1.5

**Comment by Qwjetag** [comment]
Something similar in my game... My warriors (about 40k hp - farm eq) are really easily killed by trash mobs at lvl 10 farm map, just in a few hits...

**Comment by Talisca** [comment]
Thank you for the report. Fixed with patch 1.1.6!
