### ISSUE TITLE
[BUG] Servant's Soft Gloves

### ISSUE THREAD

**Issue by R3D5T4R** [Heishe/idleraiders-second-run#692]
I noticed that there is a problem with the item "[Servant's Soft Gloves](https://imgur.com/a/H8kBG)". I have equipped a warrior with these gloves.
With 1 glove equipped, the Item functions as desired.(Received damage = 10%)
With 2 gloves the value for the damage received changes again to 89% damage.
With 3 reverts to 10% and with 4 it changes to 108%.
So if I do not want my warrior to die, I have to wear 1 or 3 of the gloves, but I can not wear 2 or 4.

https://imgur.com/a/hShls

Can someone confirm and fix it if possible.

Regards R3d5t4r

![bildschirmfoto 2017-09-28 um 15 12 36](https://user-images.githubusercontent.com/9904914/30968693-6944f546-a460-11e7-89a6-5ae7f1f16dc2.png)
![bildschirmfoto 2017-09-28 um 15 12 26](https://user-images.githubusercontent.com/9904914/30968696-69469b58-a460-11e7-8ece-cf9d2d25f18d.png)
![bildschirmfoto 2017-09-28 um 15 12 10](https://user-images.githubusercontent.com/9904914/30968698-6960fde0-a460-11e7-9d85-7c59d91ff201.png)
![bildschirmfoto 2017-09-28 um 15 11 48](https://user-images.githubusercontent.com/9904914/30968695-69462fb0-a460-11e7-8a07-c3ef8e0fe975.png)
![bildschirmfoto 2017-09-28 um 14 57 44](https://user-images.githubusercontent.com/9904914/30968694-6945b210-a460-11e7-8fbd-64c3b402e3c2.png)

**Comment by Talisca** [comment]
Thank you for the report. 
We were missing an additional check for just this raider attribute. Will be fixed with the next patch.
