### ISSUE TITLE
[BUG] Never received Gold Cones

### ISSUE THREAD

**Issue by SamsonCKG** [Heishe/idleraiders-second-run#693]
I purchased 500 Gold Cones for 50 Kreds. I was charged 50 Kreds but never recieved the cones.
<img width="513" alt="conereceipt" src="https://user-images.githubusercontent.com/32441207/31059527-976b51cc-a6d1-11e7-8165-4eee1856fabe.png">

**Comment by hamburml** [comment]
Hello Ajbael,

Thanks for your report.

I credited the missing cones to your account. I am very sorry this happened and I will check the logfiles.

Thanks for playing.

**Comment by SamsonCKG** [comment]
Thank you for the quick response
