### ISSUE TITLE
Often Crashes

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#694]
Two days ago game begin repatly crashes when far map(
[ErrorLogs.zip](https://github.com/Heishe/idleraiders-second-run/files/1348213/ErrorLogs.zip)

**Comment by Talisca** [comment]
Thank you for your logs!

The crashes are related to spears which are equipped as cosmetics. Should be fixed with the upcoming patch.

**Comment by DaemoniaV** [comment]
Thx. I remove spear. 
p.s. Much more critical is crash at Coven. May be Yuy can describe cause. Some people say tha it is realted to mini-witch attack spell. There is some My bugreports in "Seat of the Coven crashes after 1.1.7" - and if You need can send even more.
