### ISSUE TITLE
Raid bosses above raid 3 seems to drop excessive amounts

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#71]
Is it intended that the first boss (row) of raid 4 is supposed to drop 4 rare items and also a handful of uncommon drops in just one kill? The second time I killed them, they dropped 2 more. And these items are drastically better than what I already had.

**Comment by TravisGesslein** [comment]
Hi! No that seems to be a bug. The very first kill fo any boss encounter after a fresh soft reset is supposed to drop some extra items (intended default is 2 with Ancient Wisdom upgrades to increase that count) but that code is relatively flesh and likeyl buggy!

**Comment by askebv** [comment]
I've killed the other 3 bosses in raid 4 now, and they didn't drop excessive amounts - so it only seems to be the first 3 bosses. Perhaps due to the fact that there's 3 bosses?

**Comment by askebv** [comment]
I just cleared the Dawn Fortress for the first time and got 1 sunlight cape and 3 Basic Crossbows from it. Even though they're not super good items, that's still 4 rare items in one encounter.
