### ISSUE TITLE
Huge memory leak and no respond

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#710]
After 1.2 game memory grow very fast for 4 hours it grow to 3,2 gigabytes and then just no respond. I try 4 different browsers. Until that patch I easy can farm 47 hours without any problems. Please fix.

**Comment by hamburml** [comment]
Do you still have huge memory leaks? We found some leaks and closed them.

**Comment by DaemoniaV** [comment]
Now it is ok. 12 hours only 600 mb memory usage.

**Comment by hamburml** [comment]
Thanks for your response. Spread the word ;)
