### ISSUE TITLE
[BUG] Scholars tower dont add new items

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#711]
dont add 1/2/3 level items

**Comment by zaqaz123** [comment]
for players who opened 12 raid

**Comment by Izerous** [comment]
Can confirm i'm also seeing this issue with 1.3

**Comment by hamburml** [comment]
Can you export your savegame and send it to social@pitforest.de?
Thank you!

**Comment by Izerous** [comment]
I sent an export off to that address just a few moments ago. I also cleared out the spell tower like a week ago? to separate existing stock from new stock as a way to confirm comments about this being an issue again.

**Comment by hamburml** [comment]
This should be solved with v1.3.1. Thanks for creating this issue.

**Comment by Izerous** [comment]
With 1.3.1 release on my first vender refresh a flash heal 3 did show up.

**Comment by zaqaz123** [comment]
added 3 new items and stopped now again

**Comment by Talisca** [comment]
This is fixed with version 1.3.1. If you got any more problems, please let us know.
