### ISSUE TITLE
Why is there attack speed on a mage item?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#72]
What does attack speed do on mages? Are casting animations sped up?

![image](https://cloud.githubusercontent.com/assets/4981659/15774272/cc713b7c-297b-11e6-8e7d-bf576565b6ab.png)

**Comment by TravisGesslein** [comment]
Indeed, it works the same as for other classes: Casting speed is increased, and cooldown of abilites is decreased (by the same amount). I'll change the description to "Attack and Casting Speed". Also we should introduce some mouse-over helper popups when hovering over text in the statistics screen and explain what each stat does in a bit more detail.

**Comment by askebv** [comment]
@Heishe Fair enough. I certainly didn't anticipate that cooldowns were reduced though. As a minor note, I'd prefer it if you could make it say casting speed for mages/priests and attack speed for warriors/archers. The same with damage and healing. It's unnecessary information - and all it really does is suggest how it's coded :P

**Comment by TravisGesslein** [comment]
Oh, we support that behavior already, we use it for rage, focus and mana. We kept the "damage and healing" instead of separate descriptions because the same raiders might get both healing and damaging abilities (likely going to happen for priests soon).

**Comment by TravisGesslein** [comment]
I suppose we might artificially split them, i.e. show Damage and Healing as separate stats with the same underlying stat being shown, but I don't like that solution because it takes up one line of space in the UI!

**Comment by askebv** [comment]
Well, then just make an exception for the priests! Or are archers and mages expected to receive healing abilities? And casting abilities for warriors and archers?

**Comment by TravisGesslein** [comment]
No, you're right, would probably be smart to change it for those classes.

**Comment by askebv** [comment]
Oh by the way - the same goes for critical hit damage and healing
