### ISSUE TITLE
[BUG] bugreports

### ISSUE THREAD

**Issue by zaqaz123** [Heishe/idleraiders-second-run#720]
1

**Comment by zaqaz123** [comment]
1

**Comment by zaqaz123** [comment]
1

**Comment by zaqaz123** [comment]
[error_report (77).txt](https://github.com/Heishe/idleraiders-second-run/files/1498068/error_report.77.txt)
[error_report (78).txt](https://github.com/Heishe/idleraiders-second-run/files/1498069/error_report.78.txt)
[error_report (79).txt](https://github.com/Heishe/idleraiders-second-run/files/1498070/error_report.79.txt)
[error_report (80).txt](https://github.com/Heishe/idleraiders-second-run/files/1498071/error_report.80.txt)
[error_report (81).txt](https://github.com/Heishe/idleraiders-second-run/files/1498072/error_report.81.txt)
1

**Comment by zaqaz123** [comment]
i think it is drop errror - it trigger on pushing on global, not often

**Comment by hamburml** [comment]
Hi,

I'll look into it. Can you exactly explain what you did? What browser?

Thanks

**Comment by zaqaz123** [comment]
browser chrome

did nothing, only autopush. area 45000+ now and lower week ago.(have 70 errorreporsts now).

**Comment by hamburml** [comment]
I found an issue that when the trader is visiting the base some raider abilities change his behavior and he is the cause of crashes.

I will search for more causes. Thanks.

**Comment by hamburml** [comment]
Hello again,

v1.3.2 was released today and it could fix your problem. Please reload your game, try it out and hopefully the crashes are gone.

**Comment by zaqaz123** [comment]
thank you.
maybe you remove item drop chance function?
