### ISSUE TITLE
Game not loading after update

### ISSUE THREAD

**Issue by Itsonlyreeves** [Heishe/idleraiders-second-run#721]
the game said there was an update for the game so i reloaded the page and now it just gives me an error report when the game trys to load which i have added to this report
[error_report.txt](https://github.com/Heishe/idleraiders-second-run/files/1502266/error_report.txt)

**Comment by hamburml** [comment]
Hi,

have you cleared your browser cache? Maybe your browser has still some old files cashes. Hope this helps, it loads for me, other developers and players.

**Comment by Itsonlyreeves** [comment]
Ahhh yes i tried that and it's working fine now thank you, not sure why i didn't think about that first

**Comment by hamburml** [comment]
Have fun with v1.3.2 and spread the word ;)
