### ISSUE TITLE
Second Hand Earring not showing tier level

### ISSUE THREAD

**Issue by cpritchard** [Heishe/idleraiders-second-run#733]
For some reason the "Second Hand Earring" is not showing it's tier value in the item description. 

![screen shot 2018-01-18 at 2 47 42 pm](https://user-images.githubusercontent.com/4931855/35123237-a078e4ae-fc5e-11e7-823e-0641eb4783b6.png)

**Comment by Talisca** [comment]
Thank you for the report. Shall be fixed with the upcoming content update.

**Comment by cpritchard** [comment]
Just wanted to confirm this was fixed with latest update
