### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by gumlix** [Heishe/idleraiders-second-run#735]
I am Japanese and I speak using Google translation.

[error_report.txt](https://github.com/Heishe/idleraiders-second-run/files/1677756/error_report.txt)
After getting a new raid item and loading Brother, opening the Inventory will freeze the game.

I am using cloud save data.
There is timing when you open several tabs several seconds when reloading.
I am using a Google chrome.

**Comment by gumlix** [comment]
The state of the inventory is like this.
It will freeze when opened.
![inv](https://user-images.githubusercontent.com/35961226/35568297-cfa43966-060b-11e8-95f9-15f0083fcebe.png)

**Comment by Talisca** [comment]
Thank you for the report! This was fixed with the new version 1.4.1!
