### ISSUE TITLE
T13 raids are not working with auto raid

### ISSUE THREAD

**Issue by cpritchard** [Heishe/idleraiders-second-run#736]
Using auto raid the raiders stop progressing after clearing t12 and go back to the farm map without attempting to run t13 raids at all.

**Comment by cpritchard** [comment]
Still an issue in 1.4.2

**Comment by Talisca** [comment]
Thanks for the issue. Could you please send us your savegame? 
I tried it several times, but can't reproduce this behavior :(

**Comment by hamburml** [comment]
Send it to social(at)pitforest.de please. Thanks!

**Comment by cpritchard** [comment]
Sent that in just moments ago

**Comment by Talisca** [comment]
My bad. The Halloween raid blocks the progression for auto raiding.
Will be fixed with 1.4.3!

**Comment by cpritchard** [comment]
Confirmed fixed in 1.4.3
