### ISSUE TITLE
Clicking on a view while having equipment window open

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#74]
I've had this happen many times now. I'm checking out the descriptions of my current skills and then want to check that the priority list is right. So I click View Base, but it instantly puts my view back to the raider. I don't think that should be how it works:

![image](https://cloud.githubusercontent.com/assets/4981659/15774990/a3a25ca4-297f-11e6-8263-19fc02c40fd2.png)

For starters, you should probably just make it close the Statistics window at least. But it's further on, it's probably a interface design decision you want to discuss further.

**Comment by TravisGesslein** [comment]
I think when any windows are open and the player switches views to something different, the intention is probably to close the windows anyways. I'll add a functionality to just close all open windows when the player changes views and we'll see how players like it.

**Comment by askebv** [comment]
@Heishe Most of the times, yes. But sometimes I've had my equipment menu up, and realized I wanted to check the priority list - and in that case, I'd like the windows to stay open. But that's also because there's no direct way to check the priority list outside of the base.

**Comment by Talisca** [comment]
Maybe we should provide some kind of lock in the windows to let the users decide which windows shall be left open
