### ISSUE TITLE
Experienced Druid HP is really low

### ISSUE THREAD

**Issue by cpritchard** [Heishe/idleraiders-second-run#744]
![screen shot 2018-02-05 at 11 35 04 am](https://user-images.githubusercontent.com/4931855/35822237-ce5beea8-0a68-11e8-900e-e5eb5c752791.png)

I'm around lvl 24k at the time of the screenshot and he stays at 100hp forever.

**Comment by Talisca** [comment]
Thank you for the issue. Will be fixed with the upcoming patch.

**Comment by cpritchard** [comment]
Confirmed fixed in 1.4.3
