### ISSUE TITLE
The F-hotkey

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#75]
So I got curious and tried tapping every button on the keyboard to see what had any noticeable effect. And besides the harsh WASD camera control, I found the F-hotkey, which apparently centers the camera on the middle of the raid group. It's even possible to hold it down.

I tested what would happen if I was in a view with no raiders, and sadly nothing happened.

So instead, I would suggest a second functionality, in the case where you have 0 raiders on your current map:

Change view to wherever raiders are. And if they're more than one place, then change it to where the mode is currently dictating them to go.

**Comment by askebv** [comment]
Also, I would love it if there was a way to toggle constant following of the raiders.

And as a minor note, I also found that the Alt key works as a 'cancel building'-function, just like the Escape key. And I don't understand why the arrow keys wouldn't at least mirror the controls of the WASD.

**Comment by TravisGesslein** [comment]
Good ideas. Let's see... I'll probably split this up into separate issues later. Wanna squash some bugs first.
