### ISSUE TITLE
Town Hall doesnt work

### ISSUE THREAD

**Issue by thefaint94** [Heishe/idleraiders-second-run#754]
Town hall doesnt do anything when clicked, even after demolishing and rebuilding

[error_report.txt](https://github.com/Heishe/idleraiders-second-run/files/1811354/error_report.txt)

**Comment by cpritchard** [comment]
Confirmed town hall is no longer working however maybe intentional with skill book change.

**Comment by cpritchard** [comment]
As a side effect to this Basic Heal seems to be taking priority over most heals

Edit I'm wair 144ish presit spell setup is rejuvination, flash, flash, heal prop. Checking healing combat meter flash almost never fires but there is a lot of basic heal firing.

**Comment by cpritchard** [comment]
In regaurds to the issues with basic heal taking priority I created a separate ticket #755 for that issue.

**Comment by thefaint94** [comment]
gonna close as #755 is the only problem with the new system
