### ISSUE TITLE
savegame tochkas@gmail.com acount unblocking

### ISSUE THREAD

**Issue by Raider911** [Heishe/idleraiders-second-run#756]
please unblock latest attached savegame file for tochkas@gmail.com acount
i see your email when try to import and play
thanks in advance
alex didur
[saveGame.txt](https://github.com/Heishe/idleraiders-second-run/files/1822969/saveGame.txt)

**Comment by hamburml** [comment]
Hi!

I am going to answer you via mail. Thanks for reaching out!
