### ISSUE TITLE
Mysteriously lost 2 buildings

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#76]
I mysteriously lost 2 out of 3 inns. I think it happened when I quickly checked the functionality of the alt-key and the escape-key but I can't reproduce it with my last one remaining. If it matters, the two ones that disappeared were both taking advantage of the 3D thing where the two upper tiles of the 2x2 were occupied.

**Comment by askebv** [comment]
I opened up the console to [cheat money back](https://github.com/Heishe/idleraiders-second-run/issues/45#issuecomment-223299134) to try to reproduce it, and before I continue, I just wanted to share the errors in the console. Anything unexpected or important to you?

http://i.imgur.com/aQUu9Rv.png

I won't refresh or close the page unless I have to, so I can expand the errors and take a new screenshot if you'd like.

**Comment by TravisGesslein** [comment]
No, the errors look unimportant. Just a warning because we're syncing time from a time server with HTTP instead of HTTPs and some audio errors which happen when the browser can't decode an audio file (shouldn't make a difference).

**Comment by askebv** [comment]
Alright. And I couldn't reproduce the bug mentioned in the title by the way. I don't recall using or clicking near the deletion tool, so I still think it's a bug. But I'll just leave it here, unless I encounter it again.

**Comment by Ethismos** [comment]
I also just lost my Obelisk. Rip 5k...

It was placed right in the middle, next to where the first bonfire is, with dirt road on 3 of his sides and temple of the ancients to the right... if it makes any difference.

**Comment by TravisGesslein** [comment]
Did it happen while the game was running and you were building other stuff? Or was the building just gone after a restart?

**Comment by askebv** [comment]
For me, I am almost certain it was gone while the game was running (and I didn't do a soft reset). It was around the time where I talked about hotkeys and briefly entered build mode to test the alt and escape key, but that was it for building.

**Comment by Ethismos** [comment]
Actually, i also lost my time warped cave, just was never using it to notice it. Not 100% sure if it was at a reset or not, but if it happens again i will try to find out...

**Comment by askebv** [comment]
I just lost a lot of things:
- 1 well
- 1 inn
- 3 churches
- 1 town hall

Curiously enough, the inn I lost was the one that survived the last time. And I rebuilt the well recently too, when testing its buff. The 3 churches are also semi-old, but it's the newest one that survived. The town hall is one of the first buildings I bought - after the tents, market and scholar tower.

Their absolute positions don't seem to matter since some are in the center, and some are near the edges and such.

And this time I can say for sure that I went offline a few times, but haven't soft reset.

**Comment by askebv** [comment]
Lost another 2 churches, an inn and a well. I think it was after a soft reset, but I must admit I still don't pay enough attention to deduct it yet.

I'm heading to bed now, and will leave it running. When I check next time sometime tomorrow, I'll try to pay attention to see if more buildings are lost. And then perhaps do another soft reset just to test if that's the cause.

**Comment by askebv** [comment]
This time I captured it happening. It was definitely because I refreshed the page - so it's probably due to incorrect saving. This is what my base looked before I refreshed the page:

![image](https://cloud.githubusercontent.com/assets/4981659/15798576/ee89d388-2a3c-11e6-9b68-5fcd8636f558.png)

And this is after:

![image](https://cloud.githubusercontent.com/assets/4981659/15798579/04cc8c12-2a3d-11e6-85cb-c070bfcab61e.png)

I did some building and demolishing a few minutes before I refreshed, but I made sure to save the game - and wait some extra time before refreshing.

**Comment by TravisGesslein** [comment]
Thank you for that capture. Should hopefully make it easy to reproduce. Will investigate.

**Comment by thorbrian** [comment]
I've lost a town hall and well - FWIW, I'm pretty sure they were the last two things I built before I lost them

**Comment by TravisGesslein** [comment]
Yep was an easy fix thanks to the detailed descriptions above.

**Comment by askebv** [comment]
@Heishe I'm sorry - it's not entirely fixed just yet :stuck_out_tongue: 

I just refreshed to get the 3rd patch, rebuilt the things that had saved incorrectly and then refreshed again. Now I'm only losing one building.

Before refresh:
![image](https://cloud.githubusercontent.com/assets/4981659/15807000/e20e055a-2b51-11e6-9e71-cde8d1fb5784.png)

After refresh:
![image](https://cloud.githubusercontent.com/assets/4981659/15807014/28208752-2b52-11e6-901d-d265d7eee174.png)

The only thing I lost was a Training Facility. And I still lose it every time I rebuild, save and refresh.

**Comment by TravisGesslein** [comment]
Could you send us a savegame with the building intact to social _at pitforest.de? Might be left-over in your savegame from the buggy version.
