### ISSUE TITLE
1.5 Mercenaries Bug

### ISSUE THREAD

**Issue by Lavizth** [Heishe/idleraiders-second-run#761]
Hello,

I can buy MANY of them:
Buy 1 Mad Dog, 1 is shown.

Buy another one, still shows 1, but the "sort raider" icon goes down as if it obtained another, but with an invisible icon.
Buy another one, show 2, 2 icons and 1 invisible icon, and they appear on the base map and on the farm map at the same time.

![chrome_2018-04-24_18-27-28](https://user-images.githubusercontent.com/38699116/39201282-d59c485c-47ee-11e8-83c0-76da11f7602b.png)

Buy a LOT MORE, show even 3, and they gain super speed.
It work on all mercenaries.
Mercenaries Active / maximun is still 0/2.

![chrome_2018-04-24_18-10-47](https://user-images.githubusercontent.com/38699116/39201343-0b2e8dae-47ef-11e8-9a41-ea64625f8250.png)

Browser: google chrome.
Cache deleted but bug still running.

PD: english not mother language, use my knowledge and google translate for this post xD if i explain myself bad(90% sure XD), reply and i will try again xD

**Comment by cpritchard** [comment]
Just a confirmation that I was able to replicate this

**Comment by hamburml** [comment]
Thanks!
Found the error. It was introduced with the 'faster savegame loading' stuff.

**Comment by hamburml** [comment]
We just published v 1.5.1. This should work now.
