### ISSUE TITLE
Raider names = undefined and won't focus on raider

### ISSUE THREAD

**Issue by cpritchard** [Heishe/idleraiders-second-run#764]
I have names for all my raiders and they appear correctly in the combat windows however they are undefined in the equipment window, and clicking onf the raiders in the equipment windows doesn't focus on them or create the bracket effect around their face.

**Comment by hamburml** [comment]
Should be fixed with the next patch. Thanks!

**Comment by cpritchard** [comment]
Confirmed as fixed
