### ISSUE TITLE
Buff description: Corrode Armor

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#77]
#26 Another missing newline:

![image](https://cloud.githubusercontent.com/assets/4981659/15775999/7cef0868-2985-11e6-9628-dfe5a6da1629.png)

This is the one you get from the last boss in the 4th raid, I believe.

**Comment by askebv** [comment]
Still there as of Beta Patch 4 :P

**Comment by askebv** [comment]
And Beta Patch 5 :grin:

**Comment by TravisGesslein** [comment]
:hankey:
