### ISSUE TITLE
bug: stat page not updating after skills are used

### ISSUE THREAD

**Issue by SirRedan** [Heishe/idleraiders-second-run#780]
make the stat panel poll the raiders stats once per second... i'm noticing that only when i deselect and reselect the raider that i see possible changes from primal rage, etc.

if i select a raider before primal rage his stats say 9X% damage reduction.
he "rages" and it does not change
if i select someone else and reselect the raider who "raged" his damage reduction is now 10X%

**Comment by TravisGesslein** [comment]
@Talisca 
@hamburml 
Should be simple fix: In statscreen.js, add a GameWatch, in update() every 1 second call if(this.currentEntity && this.isVisible()) this.updateStatDescriptions(this.currentEntity); 

Will probably port this fix to **secret project** .

**Comment by hamburml** [comment]
Closed, was added in one of the previous patches.
