### ISSUE TITLE
High Sores not updating

### ISSUE THREAD

**Issue by brerpenguin** [Heishe/idleraiders-second-run#781]
I am at WAIR 146, but the board still has me at 144. I cleared my cookies after last update, but it still didn't change when I went up today.

**Comment by brerpenguin** [comment]
I am now at WAIR 147 with no change.

**Comment by hamburml** [comment]
Hi brerpenguin,

thanks for the issue.

Normally the High Score List is managed by Kongregate. The game sends this information to them.
I will check if something has changed and come back to you.

PS: Do you use the current version?

Thanks!

**Comment by hamburml** [comment]
v1.5.6 fixed Highscores on Kongregate 👍 
Thanks for the issue @brerpenguin
