### ISSUE TITLE
Grammar: grammar fix

### ISSUE THREAD

**Issue by SirRedan** [Heishe/idleraiders-second-run#783]
when entering a valid key that has been used the text

"Key is already used! did you bought this key and tried to redeem it? If so, please message us and give us all details about where you got the key, We will investigate this matter!"

i'd suggest:

"Key **has already been** used! Did you **buy** this key and **try** to redeem it? If so, please message us and give us **the details** about where you got the key. We will investigate this matter!"

**Comment by hamburml** [comment]
Done and Thanks 👍
