### ISSUE TITLE
Feature Request: WAIR purchase counter

### ISSUE THREAD

**Issue by SirRedan** [Heishe/idleraiders-second-run#789]
i currently have lost track of how many WAIR's I've bought, it wouldnt be hard to add a "purchased: #" to the tooltip

**Comment by cpritchard** [comment]
Currently you can view you actual wair level in the high scores. It may not be high enough to make it into the daily/weekly/alltime but if you go to the friends tab it will always show your personal score. Not saying this is a fix just mention  it will show the accurate number there without having to work back from the percentage manually.

**Comment by hamburml** [comment]
Will be added with the next patch.

Thanks for the issue 👍

**Comment by hamburml** [comment]
We released v1.6. We added a wair counter to the tooltip.
Thanks!
