### ISSUE TITLE
Invisible target on farm level 24

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#79]
There seems to sometimes be an invisible target appearing when you kill a caster that you've been fighting for a long time. My raiders keep attacking the same spot for a few seconds after it dies (and after the coin animation starts). I haven't seen any coin gain from it though, so it's probably not an enemy.
I've only seen it happen very few times, and usually it's when I've been fighting it for a minute or longer.

**Comment by askebv** [comment]
I just noticed something similar happening on the trash mobs of Gardens of Eternity as well, and realize that I might have seen it happen many different places too. It might just be due to the fact that our raiders (mostly archers, but also somewhat mages) seem to engage an attack and then commit to finishing the entire animation, even when the enemies are already dead.

**Comment by TravisGesslein** [comment]
Does this still happen? We fixed a couple of bugs that could've caused this... internal sprite re-usage... bugged death animations, etc.!

**Comment by askebv** [comment]
I haven't noticed it since, but I have been overpowered for a long time, so it's hard to really tell. And on my new game, I'm still too weak to get to farm level 24. So I don't know, sorry :P

**Comment by TravisGesslein** [comment]
I will follow the way of the ostrich and close this issue until that bug rears its ugly head once again
