### ISSUE TITLE
flickering hpbar on level 29

### ISSUE THREAD

**Issue by SirRedan** [Heishe/idleraiders-second-run#790]
![image](https://puu.sh/AOxvc/6c92f581d8.png)

i spotted a flickering hpbar ( i assume based on the shape) do not know why it's there

**Comment by SirRedan** [comment]
![image](https://puu.sh/AQPZz/1d2a5bb1ea.png)

**Comment by hamburml** [comment]
Sorry for the late response.

This could also be a Sprite issues (as some other Issues). The position and rotation is obviously wrong. With your next Patch we have some fixed and improvements for the used mechanics and hopefully this won't be happening again.

**Comment by hamburml** [comment]
We released v1.6. Please open a new issue if this happens again.
Thanks!
