### ISSUE TITLE
cannot kill anubis

### ISSUE THREAD

**Issue by mortelkill** [Heishe/idleraiders-second-run#793]
anubis, the last boss of tomb of the pharaoh has an absurdly high ability to heal itself. is there some strategy im missing to prevent him from doing that?

edit: i eventually beaten it by just grinding until i could outdamage the heal but if that was the only way to get trough that boss it wouldn t be very good design

**Comment by cpritchard** [comment]
There are 2 serparate guides that help explain how to beat him

**Comment by hamburml** [comment]
I hope you were able to finish tomb of the pharaoh. Will be closed for now.
