### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by ChibiDenDen** [Heishe/idleraiders-second-run#795]
steps to reproduce:
-have exactly one copy of an equipable item (weapon/clothing) in your inventory
-hold left mouse button to drag
-drag to relevant spot
-while holding left mouse button to drag, click the right mouse button once

the item will be equipped and a copy will be left in the inventory.

while fun to abuse, still a bug =]

**Comment by hamburml** [comment]
I was able to reproduce this when hovering the item above a cosmetics slots. Can you confirm that or does it happen on equipment slots also?

**Comment by ChibiDenDen** [comment]
I might be confusing the names
I'm talking about the 6 slots for robes/weapons/headgear etc

**Comment by hamburml** [comment]
Yeah, that is the one. Thanks for the issue! <3

**Comment by hamburml** [comment]
Will be fixed with the next patch. Thanks!

**Comment by hamburml** [comment]
We released v1.6. Please open a new issue if this happens again.
Thanks!
