### ISSUE TITLE
Witch Wood access glitch

### ISSUE THREAD

**Issue by collander** [Heishe/idleraiders-second-run#796]
Twice now when I clear the Crypt, Witch Wood does not show up in my available Raids window.    Attaching the save file of the second time this happened.

[WitchWoodGlitch.txt](https://github.com/Heishe/idleraiders-second-run/files/2205765/WitchWoodGlitch.txt)

**Comment by collander** [comment]
Ah it seems like just the icon isn't showing up, but on mouseover I realized it was still there and clickable.

**Comment by hamburml** [comment]
Unfortunately we have some Sprite/Texture issues, which we hopefully have fixed with the next patch. 

You should see the icon after you saved your game and reloaded it. Sorry for the inconvenience.

**Comment by hamburml** [comment]
We released v1.6. Please open a new issue if this happens again.
Thanks!
