### ISSUE TITLE
Monk got stuck returning from raid

### ISSUE THREAD

**Issue by eridal** [Heishe/idleraiders-second-run#797]
When any raid is finished, all the raiders are transported except the monk .. which needs to go back walking.

My monk got stuck returning from _Gardens of Eternity_ .. he's blocked on the `L` corner, trying to walk into the wall.

**Comment by hamburml** [comment]
Thanks for the issue!

Do you have a screenshot of that situation?

**Comment by eridal** [comment]
Yeah, I dont have a picture of the situation .. but here's some quick sketch ...

![the X marks the spot](https://i.imgur.com/bP8ZN8f.jpg)

I believe the problem is that the raiders were teleported back into the base, but the poor monk needed to walk back

**Comment by hamburml** [comment]
Normally all entities are transported back when a raid is finished :/ Hopefully I can reproduce this.

**Comment by hamburml** [comment]
Sadly I wasn't able to reproduce this. Would be helpful if this can be reproduced easily :/
