### ISSUE TITLE
Target Enemy

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Heishe/idleraiders-second-run#799]
Often the raiders spread out and try to kill 3 different enemies at the same time, with the enemies healing faster than you do damage in this situation it would be nice if you could either click an enemy to make all raiders attack that one or have a setting (maybe both?) to always force them to concentrate on one enemy.

**Comment by Talisca** [comment]
There is an ai-upgrade which is called "Concentrate Attack". On activation it will add a Command-Skillbook to your inventory, which enables the carrier to set the target of all other raiders to the same target.

**Comment by hamburml** [comment]
If you still have questions please open a new issue.
