### ISSUE TITLE
Auto-raid not working

### ISSUE THREAD

**Issue by neuralien** [Heishe/idleraiders-second-run#800]
Currently running 1.6.2 in Chrome 67.0.3396.99 (64-bit). I've cleared my cache and the issue still persists.

Selecting auto-raid doesn't seem to do anything. If my raiders are resting, switching to auto-raid will make them farm the currently selected farm map. If my raiders are auto-farming, switching to auto-raid will make them continue to auto-farm. If I'm farming a map, switching to auto-farm will keep my raiders on the current farm map.

Manually selecting a raid then switching to auto-raid doesn't do anything. At the end of the selected raid map, it will go back to farming.

**Comment by Yaongura** [comment]
i have the exact same problem, but i'm runing it in Chrome 68.0.3440.106. I tried to clear the cache, restart the game, pc, soft reset but nothing solved the problem.

**Comment by hamburml** [comment]
We fixed the auto-raid-mode in 1.6.3.

Unfortunately you need to manually clear the raids once - but after that the auto-raid-mode works like it used to be.
