### ISSUE TITLE
Can't progress in raiding

### ISSUE THREAD

**Issue by Yaongura** [Heishe/idleraiders-second-run#801]
I'm only have the Sanctuary of the forgotten, Dawn fortress throne room and the Crypt and i can't unlock the other raids, even if i complete those 3. This issue is probably somehow linked to the issue with the auto raiding not working(someone else posted that one already, it's #800 where i also commented on having the same problem).

**Comment by hamburml** [comment]
We fixed the auto-raid-mode in 1.6.3 - could you please try again?

**Comment by hamburml** [comment]
Please open another issue if this still happens.
