### ISSUE TITLE
No farm or raid drops

### ISSUE THREAD

**Issue by imacairpro** [Heishe/idleraiders-second-run#805]
Since 1.6.5 raids no longer drop any items. Neither do farm maps drop the map specific drops, but will still drop global item drops.

Soft resetting, restarting, etc. doesnt seem to fix the issue.

**Comment by imacairpro** [comment]
Guess it's the same issue as #806 - but I'm haven't gotten far enough into the game to do a full map cycle.

**Comment by AZimmermann89** [comment]
Got the same problem, currently testing if finishing map 67 does help.

**Comment by AZimmermann89** [comment]
I can confirm that going all the way to floor 67 'enables' drops.
I get drops on floor 10/12 again.

**Comment by hamburml** [comment]
The issue should be fixed, please reload the game.
We are terribly sorry.
