### ISSUE TITLE
No normal map drops or raid drops unless atleast 1 map cycle is performed

### ISSUE THREAD

**Issue by Didroin** [Heishe/idleraiders-second-run#806]
Normal map drops (like the staves on map 7) and raid boss drops do not drop until a player clears map 67.

Once a player clears map 67, all previous maps and all raids drop items again. One doesn't need to complete a rotation for a certain map to regain the drops. For example, it is not needed to clear the 2nd version of map 7 (74) to get basic map 7 drops.

Global drops still seem to function normally

**Comment by Hydrology16** [comment]
I have this same problem, started playing the game a few days ago and im stuck in levels 1-12 probably could push but im not working with much.

Also my Spell and Merchant buildings havent cycled any new items, it has been the same choices since the patch.  

Thanks,

**Comment by AZimmermann89** [comment]
Can confirm the issue, also with the 'fix' to push after map 67 to get drops again.
See also #805

**Comment by hamburml** [comment]
The issue should be fixed, please reload the game.
We are terribly sorry.
