### ISSUE TITLE
Map items don't drop

### ISSUE THREAD

**Issue by schwitzelbakon** [Heishe/idleraiders-second-run#808]
So I've been farming for the skeleton key for about a week into playing Second Run and it hasn't dropped on either map 3 or 4. I decided to jump onto different maps and let the game run while I'm at work (12 hours or so at a time) and while I sleep. I've never received a single map item where it says "enemies can drop this". Not one single item with the exception of different items. Either the drop rate is so incredibly low, or there's a bug not allowing enemies to drop the map-specific item.

**Comment by hamburml** [comment]
Hey @schwitzelbakon 

you need to reload the game (don't forget to clear your browser cache). This bug was fixed two days ago.

Thanks for playing!

**Comment by hamburml** [comment]
Please create a new issue if this still happens. Thanks!
