### ISSUE TITLE
Tall buildings don't display the top after deletion

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#81]
This happens after you press OK to the confirmation dialog:

![image](https://cloud.githubusercontent.com/assets/4981659/15779534/381b2b8c-299d-11e6-821b-a737e61d6f7e.png)

This only persists in demolition mode. Once you exit out or change to build mode, it goes away.

**Comment by askebv** [comment]
This is the error I get when it happens:

![image](https://cloud.githubusercontent.com/assets/4981659/15798511/4c51e07a-2a3b-11e6-895f-8ee604aa0785.png)

**Comment by TravisGesslein** [comment]
Yep this is a renderer bug. Can't fix this for Patch 3, I will tackle it for Beta Patch 4. Afaik a simple workaround is to toggle between the viewed maps or basebuilding/normal mode once.

edit: Oh yes you said as much as well.

**Comment by askebv** [comment]
@Heishe So far Beta Patch 5 then? :stuck_out_tongue:

**Comment by TravisGesslein** [comment]
Whoops, I almost forgot about this bug.
