### ISSUE TITLE
Reproducable Crash

### ISSUE THREAD

**Issue by cpritchard** [Heishe/idleraiders-second-run#816]
Refresh game have all raiders in town
Send raiders to single target training room
send camera only not raider back to town to hire Miyaow + Experienced Miyaow
send raiders to single target training room again to force mercs to join in
trying to open combat meter results in a crash 4 out of 4 times so far

**Comment by hamburml** [comment]
I can't reproduce this :/ Did you opened the combat meter before or after you hired miyaow?

**Comment by cpritchard** [comment]
did not open combat meter until very end. I can try to replicate again with video capture if that would help.

**Comment by hamburml** [comment]
That would be great <3

**Comment by cpritchard** [comment]
Trying to capture the video of this happening I cannot replicate it myself anymore. Had it only happened once the first time around I wouldn't have even brought it up but had happened 4 out of 4 attempts.
