### ISSUE TITLE
Scout Tower Crash

### ISSUE THREAD

**Issue by AZimmermann89** [Heishe/idleraiders-second-run#818]
I am farming T11 stuff and didnt even visit the T12 bosses yet.
When I open the scout tower and press on the 'left' arrow (while looking at the T1 items) I will get a crash every time.

**Comment by hamburml** [comment]
Thanks, will check this in some hours.

**Comment by hamburml** [comment]
Will be fixed with the next patch.

**Comment by AZimmermann89** [comment]
Isn't fixed yet.
I'm still getting the error.

**Comment by hamburml** [comment]
We haven't patched the game and therefore the fix isn't live :)
