### ISSUE TITLE
Tier 9-15 set items drop more than once

### ISSUE THREAD

**Issue by pedter** [Heishe/idleraiders-second-run#819]
This appears to be due to using only .unique() instead of both .unique() and .uniqueSpawnCondition() when registering the items. Tier13ArtifactWarriorHelmetEyepatchKenpachi is the only exception; it uses both during item registration.

**Comment by hamburml** [comment]
That's not an error. Some items can be unique (only one raider can wear it) and some items can be unique and have a uniqueSpawnCondition (can only drop once).
