### ISSUE TITLE
Melee enemies have super long attack range in level 33-36

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#82]
I didn't reach to capture it in time, but you can see that the enemy doesn't really move. That's because he can attack at a ridiculous range:

![image](https://i.gyazo.com/3cf71210c08dff2b72ff645c93199199.gif)

**Comment by askebv** [comment]
Same goes for farm level 34 - and probably all the other levels where these two enemies exists.

**Comment by askebv** [comment]
Yup level 35 as well:

![image](https://i.gyazo.com/6da75317bce592a4c84cbcb8e822c255.gif)

**Comment by askebv** [comment]
These enemies often also stay for a few seconds after they're dead. Don't know if that's intended.

**Comment by TravisGesslein** [comment]
They are standing around because they're supposed to play death animations. Will be fixed.
