### ISSUE TITLE
Farm level 49 is empty.

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#89]
Title

**Comment by askebv** [comment]
Do you have 1 increased mob count (like I do)? In that case, it could be because we need 2 (or more) to get at least 1 to spawn.

**Comment by Ethismos** [comment]
Nope, i don't have it.

**Comment by askebv** [comment]
@Ethismos And you also just have a maximum of one monster in level 40, right? Because I do, and I have one of that ancient wisdom unlocked.

I'm on 47 right now, so I'll check 49 too in a bit. But I expect it to be empty for me as well -even with that upgrade.

**Comment by Ethismos** [comment]
Yes, also one maximum in 40.

**Comment by askebv** [comment]
Level 49 is definitely bugged. It doesn't seem to have its own map. Go to whichever map and then select auto-increase-farm, and level 49 will have the same layout as the one you were just on:

![image](https://i.gyazo.com/a6b8dab8f0e24aea213eb04458c56394.gif)
