### ISSUE TITLE
[Minor] Sorting doesn't apply properly to equipment & statistics window

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#9]
If new raiders join after the sorting method has been set, it will just get added to the bottom of the list, in the equipment & statistics window. Sorting again fixes it.

Sadly I didn't manage to take a screenshot in time, sorry.

**Comment by TravisGesslein** [comment]
Welcome back Muskar!

**Comment by Ethismos** [comment]
Hello!

I think he means this: http://imgur.com/SODyq9A !

Reproduce by sorting by class before a new raider joins. Happened 3 out of 3 tries for me!

**Comment by TravisGesslein** [comment]
And welcome back Ethismos! :+1:

**Comment by askebv** [comment]
Thanks. I must say.. you were right, I think your new version is getting close to a very fun game for me too. Obviously the beginning needs tweaking, and some minor UI changes need to be made - but other than that, I think you've made some great changes since I last checked it out!
