### ISSUE TITLE
0 Drops

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#91]
Occasionally i get 0 drops from some boss encounters, is this supposed to happen?

For example i just did the first 2 bosses (all 6 enemies) at raid 6 with no drop...

**Comment by askebv** [comment]
I cleared Ravaged Abode for the first time, and got no drops. #70 
EDIT: And I don't think I got any in my next many raids either. Maybe the drop rates just slow heavily down in the higher raids for now.

**Comment by TravisGesslein** [comment]
We forgot to add loot tables to two of the bosses in the raid, should be fixed with patch 3
