### ISSUE TITLE
Offline progress?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#96]
Is there no offline progress in the beta? It doesn't seem like it, because I had 3.84k when I saved and closed the game. And then after 2 minutes offline, I had 3.83k and my raiders were set to sleep mode (they were in auto-raid mode when I closed the game).

I know offline progress is a difficult beast to handle in a game like this, but I'm just wondering if you no longer want to support it - or if it's left out for now - or if it's supposed to be there, but is bugged.

**Comment by TravisGesslein** [comment]
No, it's just not re-implemented yet. We just disabled it so far because we haven't gotten around to rebalancing it (the old values are way too high for the new version of the game). We'll patch it in as soon as we can, but we want to get the first wave of bugs out of the way first.

**Comment by askebv** [comment]
@Heishe Yes, I want that too.

Also, now that this has a question tag: Is it alright that I'm "spamming" this issue tracker with all issues I can find? I know a lot of them are pretty minor. And some of them are issues that I know you probably won't deal with until way later (like the pathfinding stuff). I've basically just been defensive by posting everything, because I know I'd forget the things as I went on (especially if they related to a stage of the game I will never be at again). But it's quite evident that the number of issues are rising faster than you can deal with them, at the moment.

**Comment by TravisGesslein** [comment]
No problem at all, appreciated actually :+1:

**Comment by TravisGesslein** [comment]
Also just in case: My replies aren't meant to sound serious, I just can't find any suitable emojis! :hankey:

**Comment by Ethismos** [comment]
You went offline? HERETIC!

**Comment by askebv** [comment]
@Heishe I know the feeling :grinning: 

Here's all the emoji in the world btw:

http://www.emoji-cheat-sheet.com/

**Comment by Drakenfeld** [comment]
Well since this is the now the quick question section ill add on little, Is Ravaged Abode the last raid we can currently run?

**Comment by TravisGesslein** [comment]
Yup!

**Comment by TravisGesslein** [comment]
I'm leaving this issue open as 'game bug', basically offline farming isn't there even though it's supposed to be.

**Comment by TravisGesslein** [comment]
Forgot to close this, offline farming is implemented.
