### ISSUE TITLE
Suggestion: Show active raid finishing time

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#98]
Since we can see how fast we completed the raid, and have a record as well, it might be nice to be able to view the current raid time.

Depending on how important the mechanic is (if you'll e.g. have a time-limited raid), it could be shown in the raid view in general, or just inside the tooltip of each raid, where the current times are as well.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
